dfinity/sdk

src/dfx/src/actors/icx_proxy.rs

When dfx starts, it logs "Stopping icx-proxy..." "Stopped" when it didn't actually do that.

fix: remove extraneous log output wrt stopping icx-proxy

---

CHANGELOG.adoc
src/dfx/src/commands/canister/create.rs
src/dfx/src/commands/canister/update_settings.rs
src/dfx/src/util/clap/validators.rs

Also changed the help descriptions for `dfx canister create` and `dfx canister update-settings` to describe the meaning of a setting of 0.

fix: changed maximum value of --memory-allocation to 12 GiB

---

nix/sources.json

This PR uses a newer commit for the ic-hs repo so that the Darin `ic-ref` binary that we distribute with `dfx` won't depend on /nix/store, and will therefore have a chance to run when nix isn't installed.
Before:
```
$ otool -L ic-ref
ic-ref:
/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-Libsystem-osx-10.12.6/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
@executable_path/libz.1.2.11.dylib (compatibility version 1.0.0, current version 1.2.11)
@executable_path/libiconv.dylib (compatibility version 7.0.0, current version 7.0.0)
@executable_path/libgmp.10.dylib (compatibility version 15.0.0, current version 15.0.0)
@executable_path/libffi.7.dylib (compatibility version 9.0.0, current version 9.0.0)
```
After:
```
$ otool -L ic-ref
ic-ref: …
```

chore: Update ic-ref to fix /nix/store dependency

---

scripts/write-dfx-asset-sources.sh

This fixes new errors of the form:
```
warning: 'to-base16' is a deprecated alias for 'hash to-base16'
error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override
```
Example failed build: https://github.com/dfinity/sdk/runs/4074667958?check_suite_focus=true

chore: use nix-hash --to-base16 not nix --to-base16

---

.github/workflows/lint.yml
src/dfx/src/commands/new.rs

This is for branch protection rules, so that we can require a single status check rather than several.

chore: aggregate all lint checks into a single status

---

.github/workflows/cargo-build.yml
.github/workflows/consistent-sources.yml
.github/workflows/shellcheck.yml

The default is usually right (opened, reopened, synchronize)

chore: remove unneeded pull_request event types

---

cargo-audit.nix

`chrono` depends on `localtime_r`, which has issues.
We have a couple direct dependencies on chrono in 'sign.rs` and `signed_message.rs', but slog-term also depends on chrono.

chore: disable some unavoidable cargo audit errors

---

.github/workflows/fmt.yml
.mergify.yml

Also renamed status name to `fmt:required` to match the other required statuses.
The 'aggregate' step removes the matrix parameters from the status name.

chore: add github workflow-based e2e and fmt as required mergify status checks

---

Cargo.lock
src/dfx/Cargo.toml

Fixes this cargo audit failure:
```
Crate:         tokio
Version:       1.11.0
Title:         Data race when sending and receiving after closing a `oneshot` channel
Date:          2021-11-16
ID:            RUSTSEC-2021-0124
URL:           https://rustsec.org/advisories/RUSTSEC-2021-0124
Solution:      Upgrade to >=1.8.4, <1.9.0 OR >=1.13.1
Dependency tree:
tokio 1.11.0
```

chore: fix RUSTSEC-2021-0124

---

.github/workflows/cargo-build.yml
.github/workflows/e2e.yml
.github/workflows/fmt.yml
.github/workflows/lint.yml
scripts/workflows/e2e-matrix.py

In our nix builds (which are what we still ship), we are now using rust 1.55.0 from https://github.com/dfinity-lab/common/blob/master/pkgs/overlays/rust/1_55.nix

chore: build with rust 1.55.0 to match common

---

src/dfx/src/lib/builders/motoko.rs

moc 0.6.14 generates did file while compiling to Wasm, so we no longer need to run moc twice in the build process.

fix: only run moc once for dfx build

---

.mergify.yml

For:
The configuration uses the deprecated strict mode of the merge action.
A brownout is planned for the whole December 6th, 2021 day.
This option will be removed on January 10th, 2022.
For more information: https://blog.mergify.com/strict-mode-deprecation/
The configuration uses the deprecated commit_message mode of the merge action.
A brownout is planned for the whole March 21th, 2022 day.
This option will be removed on April 25th, 2022.
For more information: https://docs.mergify.com/actions/merge/
Also added two new required checks (audit and prepare-dfx-assets)

chore: Update mergify configuration to account for deprecations

---

rust-toolchain.toml

Prevents developers from having to run `rustup override set 1.55.0` for accurate lints and lang/library features.

chore: Add rust-toolchain.toml

---

src/dfx/src/config/cache.rs

When dfx installs a cache directory, it first copies all of the files into a directory `_<version>_<random>`, and once all files have been copied, renames the directory to `<version>`.  This prevents dfx from later using partially copied cache directories.
This change makes `dfx cache list` ignore these temporary directories, rather than exiting with an error message like `unexpected character '_' while parsing major version number`.

fix: dfx cache list: skip cache directories being installed

---

public/install/200_downloader.sh

When installing on macos Montery (12.1) the installer told me that 12.1 is older than 10.13

chore: add Monterey as a recognised macos version in install.sh

---

CHANGELOG.adoc
e2e/tests-dfx/identity_command.bash
src/dfx/src/lib/identity/identity_manager.rs

`quill generate --pem-file <pem file>` generates .pem files that don't include an `EC PARAMETERS` section, in contrast to .pem files created by keysmith.  `dfx identity import` misidentifies these as Ed25519.
Since `dfx identity import` still checks that these keys are secp256k1, this change identifies .pem files that begin with either an `EC PARAMETERS` or `EC PRIVATE KEY` section as EC private keys, and therefore imports them.
Fixes https://dfinity.atlassian.net/browse/SDK-296

fix: dfx identity import now handles pem files generated by quill

---

Cargo.lock
Cargo.toml
src/dfx/Cargo.toml

Nothing user-facing, but won't break when we next upgrade the certified assets canister.

chore: update to agent-rs 0.12.1

---

src/dfx/src/commands/ping.rs
src/dfx/src/lib/builders/assets.rs
src/dfx/src/lib/network/network_descriptor.rs
src/dfx/src/lib/provider.rs

Replaces pull #2007 with an internal pull since Hydra doesn't approve of external ones.
Jira: [SDK-279](https://dfinity.atlassian.net/browse/SDK-279)
Previously: dfx only allowed to access the main IC net with two reserved strings for `--network`.
New: main IC net can also be accessed by an alias that looks like this: `"staging": { "providers": [ "https://ic0.app" ], "type": "persistent" }`

chore: respect provider when determining whether on IC or not

---

Cargo.lock

Fixes this cargo audit failure, in order to un-stick https://github.com/dfinity/sdk/pull/1966
```
Crate:         thread_local
Version:       1.1.3
Title:         Data race in `Iter` and `IterMut`
Date:          2022-01-23
ID:            RUSTSEC-2022-0006
URL:           https://rustsec.org/advisories/RUSTSEC-2022-0006
Solution:      Upgrade to >=1.1.4
Dependency tree:
thread_local 1.1.3
├── slog-term 2.8.0
│   └── dfx 0.9.0
└── slog-async 2.7.0
└── dfx 0.9.0
```

chore: update thread_local to 1.1.4

---

src/dfx/assets/new_project_rust_files/src/__project_name__/Cargo.toml

`candid` is included in the `dependencies`

chore: update cdk version in new rust project

---

public/install/200_downloader.sh

This is so that we display an error about the minimum supported OSX version being Catalina, rather than an error message about an expired cert.

fix: High Sierra, Mojave no longer supported

---

.github/workflows/publish.yml
src/dfx/assets/build.rs

As a first step, this publishes binary tarballs when a release tag is pushed.  The linux binary is statically linked.
A follow-up PR will either also publish these to s3, or make the install script download these releases from github.com/dfinity/sdk/release.
Also:
- `get_git_hash()`: don't report an empty string if git describe --dirty fails

feat: publish dfx to github release when a version tag is pushed

---

src/dfx/assets/new_project_node_files/package.json

`.most` file are generated by motoko compiler for internal use, it should not be copied to the `declaration` directory.

fix: remove .most file from declaration

---

CHANGELOG.adoc
e2e/tests-dfx/frontend.bash
src/dfx/src/commands/deploy.rs

Example output for local deploy, if dfx.json has `127.0.0.1:8000` as the bind address, which is the default:
```
$ dfx deploy
...
Committing batch.
Deployed canisters.
URLs:
Frontend:
dd_assets: http://127.0.0.1:8000/?canisterId=rdmx6-jaaaa-aaaaa-aaadq-cai
Candid:
dd: http://127.0.0.1:8000/?canisterId=qoctq-giaaa-aaaaa-aaaea-cai&id=renrk-eyaaa-aaaaa-aaada-cai
```
Example output for local deploy, if dfx.json has `localhost:8000` as the bind address:
```
$ dfx deploy
...
Deployed canisters.
URLs:
Frontend:
dd_assets: http://ryjl3-tyaaa-aaaaa-aaaba-cai.localhost:8000/
Candid:
dd: http://r7inp-6aaaa-aaaaa-aaabq-cai.localhost:8000/?id=rrkah-fqaaa-aaaaa-aaaaq-cai
```
Example mainnet output:
```
$ dfx --identity mainnet deploy --network ic
...
Committing batch.
Deployed canisters.
URLs: …
```

feat: dfx deploy shows frontend and candid urls

---

assets.nix
nix/default.nix

The .tar form of the release binary tarball (.tar.gz) was being included as the icx-proxy binary, rather than the contained icx-proxy binary.
Before:
```
$ ( export DFX_CONFIG_ROOT="$(mktemp -d)"; DFX="$(nix-build ./dfx.nix -A build)/bin/dfx" ; "$DFX" cache install ; $("$DFX" cache show)/icx-proxy --help )
Version v0.9.2 installed successfully.
zsh: exec format error: /var/folders/vl/2fdfs_116pb82rzcb_s779d80000gn/T/tmp.b2PPAA85/.cache/dfinity/versions/0.9.2/icx-proxy
```
After:
```
$ ( export DFX_CONFIG_ROOT="$(mktemp -d)"; DFX="$(nix-build ./dfx.nix -A build)/bin/dfx" ; "$DFX" cache install ; $("$DFX" cache show)/icx-proxy --help )
building '/nix/store/l2h140b9849clcimy1s2rnmjam4ygv8x-git-ls-files.drv'...
Version v0.9.2 installed successfully.
icx-proxy 0.8.1
DFINITY Stiftung …
```

fix: broken icx-proxy in nix builds

---

CHANGELOG.adoc

Updated the changelog:
- Next version will be 0.10.0
- Moved changes that were made after 0.9.3 into the 0.10.0 section

docs: Move changes made post-0.9.3 into 0.10.0 section of changelog

---

CHANGELOG.adoc
e2e/tests-dfx/call.bash
src/dfx/src/commands/canister/call.rs

`--with-cycles <n!=0>` is only valid in a call if it is proxying through the wallet.

fix: Error if nonzero cycles are passed without a wallet proxy

---

.github/workflows/e2e.yml
CHANGELOG.adoc
e2e/assets/bitcoin/patch.bash
e2e/assets/bitcoin/testnet.config.json
e2e/tests-dfx/bitcoin.bash
e2e/tests-dfx/start.bash
e2e/utils/_.bash
scripts/workflows/e2e-matrix.py
src/dfx/src/actors/btc_adapter.rs
src/dfx/src/actors/mod.rs
src/dfx/src/actors/replica.rs
src/dfx/src/commands/replica.rs
src/dfx/src/commands/start.rs
src/dfx/src/config/dfinity.rs
src/dfx/src/lib/replica_config.rs

`dfx start` and `dfx replica` now launch the `ic-btc-adapter` binary, if either the `--btc-adapter-config <path>` parameter is passed, or the `.defaults.bitcoin.btc_adapter_config` field is set in dfx.json.
If a unix domain socket path is configured (`.incoming_source.Path` in the btc adapter config file), dfx will:
- delete this file before launching ic-btc-adapter,
- wait to launch replica until after this file exists (meaning ic-btc-adapter is listening on the unix domain socket).
If the ic-btc-adapter process exits (crashes), dfx will relaunch it, in the same way that it relaunches icx-proxy if the replica restarts.
Fixes https://dfinity.atlassian.net/browse/SDK-352
Gathering the docs changes here, but not opening a PR until the ic-starter work is done: …

feat: dfx start and dfx replica: launch ic-btc-adapter when so configured

---

.github/CONTRIBUTING.adoc

We don't need nix in order to build dfx anymore, and `cargo build` just works now.
Updated the contributing docs to say how to build dfx and how to run end to end tests without nix.

docs: contributing: cargo just works

---

CHANGELOG.adoc
e2e/tests-dfx/deploy.bash
e2e/tests-dfx/install.bash
src/dfx/src/commands/canister/install.rs
src/dfx/src/commands/deploy.rs
src/dfx/src/lib/operations/canister/deploy_canisters.rs
src/dfx/src/lib/operations/canister/install_canister.rs

Make it so it's possible to "upgrade" a canister's wasm even if the wasm hash did not change.  This has been asked for in order to be able to re-run the upgrade path repeatedly (even though the code didn't change).
Also applies to dfx canister install --mode=upgrade --upgrade-unchanged
Through end-to-end tests, and by running `dfx deploy --upgrade-unchanged` and `dfx install --all --mode=upgrade --upgrade-unchanged`
- [] I have made corresponding changes to the documentation.
closes #2015

feat: dfx deploy --upgrade-unchanged to upgrade wasm even if it did not changed

---

CHANGELOG.adoc
e2e/assets/bitcoin/patch.bash
e2e/tests-dfx/bitcoin.bash
e2e/utils/assertions.bash
src/dfx/src/actors/replica.rs
src/dfx/src/commands/replica.rs
src/dfx/src/commands/start.rs
src/dfx/src/config/dfinity.rs

Set the `bitcoin_testnet_feature` subnet feature if btc integration is enabled.
Add `dfx start --enable-bitcoin` and `dfx replica --enable-bitcoin` command-line arguments for enabling the bitcoin feature.  Note that passing `--btc-adapter-config <path>` on the command line implies these parameters are true.
Also added a dfx.json setting `.defaults.bitcoin.enabled` to control this behavior.
This way, you can set up the btc integration (configuration path) in defaults, without having it enabled all of the time, but can  enable it by running `dfx start --enable-bitcoin`, and it's also possible to set up dfx.json such that it's enabled with just `dfx start`.
Fixes # (unknown)
There are end-to-end tests.

feat: add command-line arg and dfx.json default to enable bitcoin feature

---

scripts/prepare-dfx-assets.sh

We always use x86_64 prebuilt binaries with rosetta
`cargo build` on an M1 machine

fix: now builds on Apple M1

---

CHANGELOG.adoc
e2e/tests-dfx/start.bash
src/dfx/src/commands/start.rs

While writing other tests, I noticed that `dfx start` outputs "Address already in use" instead of "dfx is already running" if dfx is already running.
It turned out that dfx start wasn't actually checking the process list, because the newer version of `system` that we're using requires a call to update the process list.
Worse, it would overwrite `.dfx/pid` with an empty file, then fail with `Address is already in use`, meaning `dfx stop` would later not know which pid to signal.
Fixes # https://dfinity.atlassian.net/browse/SDK-424
Before
```
$ dfx start --background && dfx start
...
Apr 18 10:19:32.478 INFO Starting server. Listening on http://127.0.0.1:8000/
Error: Address already in use (os error 48)
$ dfx stop
$ dfx start
Error: Address already in use (os error 48) …
```

fix: dfx start should detect if dfx is already running

---

src/dfx/src/lib/identity/mod.rs

Missing wallet error message can be more user friendly. Adding instructions how to avoid the error moving forward.
Fixes [SDK-429](https://dfinity.atlassian.net/browse/SDK-429)
Manually, using `dfx deploy --network ic` for an identity without configured wallet.

chore: update missing wallet error message

---

CHANGELOG.adoc
e2e/tests-dfx/update_settings.bash
src/dfx/src/commands/canister/create.rs
src/dfx/src/commands/canister/update_settings.rs
src/dfx/src/lib/ic_attributes/mod.rs

`dfx canister update-settings <canister id>` would fail unless the canister id corresponded to a named canister in the project.  This PR makes it so the command works for any canister id (as long as you are the controller)
Fixes https://dfinity.atlassian.net/browse/SDK-438

fix: dfx canister update-settings <canister id>

---

scripts/release.sh

Make it so the build script no longer requires nix to be installed.
At one point, I had a problem: how to update the first `version =` line in Cargo.toml.  "I know, I'll use sed," I thought.  Well, whichever version of sed nix bundles worked, but sed on OSX had other ideas.  Anyway, you know the rest of the story.  This PR makes the script use `awk` instead.
```
DRY_RUN=1 ./scripts/release.sh 9.8.7-beta.1
```

build: make release script work without nix-shell

---

e2e/tests-dfx/wallet.bash
src/dfx/src/lib/identity/mod.rs

Currently we only allow deploying a wallet if it is not already the configured wallet, even if the canister is empty. This should be a hard state to reach after #2151 is pulled, but it is still a pointless restriction.

fix: Allow deploy-wallet to an empty canister

---

CHANGELOG.adoc
src/dfx/src/util/mod.rs

Before this commit, `deploy`ing a canister with an `opt Foo` init
argument without specifying an `--argument` would lead to an error:
```
$ dfx deploy
Error: Invalid data: Expected arguments but found none.
```
With this change, this isn't an error anymore, but instead `null` is
passed as a value. In general, if the user does _not_ provide an
`--argument`, and if the init method expects only `opt` arguments, then
`dfx` will supply `null` for each argument.
Note in particular that this does not try to match `opt` arguments for
heterogeneous (`opt`/non-`opt`) signatures. Note moreover that this only
impacts a case that would previously error out, so no existing (working)
workflows should be affected.
I've only manually tested this with a canister that expected a single `opt` init argument.

feat: Use null as default value for opt arguments

---

e2e/tests-dfx/wallet.bash
src/dfx/src/commands/canister/deposit_cycles.rs

`dfx canister deposit-cycles` attempts to get the new balance so it can log it, and propagates any errors. This means that if it successfully deposited cycles to a canister it can't query because it doesn't own, it will visually fail with an error while the transaction proceeded just fine. This removes that behavior.

fix: Remove false error from deposit-cycles

---

CHANGELOG.adoc

Adds a section to the changelog for entries that are made after the 0.10.0 release

chore: update changelog for changes post-0.10.0

---

public/install/999_footer.sh

On Linux systems, `shasum` may not be available, and even if it is, it depends on perl being installed.
On OSX, `sha256sum` isn't installed by default, but can be by homebrew.
Use whichever is available, favoring sha256sum.
Also, pushd and popd aren't available in sh, so use a subshell.
Tested manually.

fix: install script: use either of shasum or sha256sum

---

src/dfx/src/commands/canister/install.rs
src/dfx/src/commands/canister/status.rs

Same story as #2169, this time with `dfx canister install` (applicable primarily with `--wasm`) and `dfx canister status`.
Fixes #2050.

fix: Fix more spurious configuration errors

---

src/dfx/src/lib/models/canister_id_store.rs

I don't think these ever needed to be public, but they sure don't now.

fix: make CanisterIdStore struct members private

---

scripts/prepare-dfx-assets.sh

Previous PR neglected to actually add the binary, when built with `cargo build`
```
$ dfx-wip cache install
$ ls $(dfx-wip cache show)
base				ic-canister-http-adapter	libffi.8.dylib			mo-ide
canister_sandbox		ic-ref				libgmp.10.dylib			moc
dfx				ic-starter			libz.1.2.11.dylib		replica
ic-btc-adapter			icx-proxy			mo-doc				sandbox_launcher
```

fix: include ic-canister-http-adapter binary in binary cache

---

CHANGELOG.adoc
src/dfx/src/actors/replica.rs
src/dfx/src/commands/replica.rs
src/dfx/src/commands/start.rs
src/dfx/src/lib/replica_config.rs

Also made the ReplicaConfig `.with_*` methods consistent with each other.
Fixes https://dfinity.atlassian.net/browse/SDK-452

feat: pass uds socket path to ic-starter for btc adapter.

---

src/dfx/src/lib/canister_info/motoko.rs

dfx used to use this field decide whether or not to inject assets into a Motoko canister, but nothing references it anymore.

chore: removed unused field MotokoCanisterInfo.has_frontend

---

.github/workflows/publish.yml
CHANGELOG.adoc

Build the Linux binary dynamically, as was done in dfx 0.9.3 and earlier, in order to avoid the following error when trying to use an HSM:
```
Error: IO: Dynamic loading not supported
```
Other changes to the workflow:
- manually build a static-linked openssl for the linux build
- allow words other than "beta" in the tag name
- removed the "test-#.#.#-*" tag allowance, because those wouldn't be a valid semver (and dfx would panic)
- verify the list of referenced dynamic libraries, to avoid post-release surprises.
Fixes https://dfinity.atlassian.net/browse/SDK-495 
Tested manually with an HSM.  Here's a sample release: https://github.com/dfinity/sdk/releases/tag/0.10.1-hsm.1

fix: HSM support on Linux build

---

CHANGELOG.adoc
scripts/prepare-dfx-assets.sh

dfx can't build at all since icx-proxy releases are no longer available from github.  As a temporary workaround, obtain a release icx-proxy from the latest dfx release.
Tested locally and by CI

build: temporary hack: obtain icx-proxy from dfx 0.10.0 release

---

CHANGELOG.adoc
src/dfx/assets/new_project_node_files/package.json
src/dfx/assets/new_project_node_files/webpack.config.js

CopyPlugin was redundant and leading to 'too many open files' message, as dfx.json already is configured to pull assets from the frontend assets directory
manually tested the changes locally

fix: removes copyplugin

---

.gitignore
e2e/tests-dfx/rust.bash
src/dfx/src/lib/builders/rust.rs
src/dfx/src/lib/canister_info/rust.rs

Cargo supports alternate locations for the build artifacts than `./target`, configured through e.g. `$CARGO_TARGET_DIR`. This changes the artifact path from a hardcoded assumption of `./target` to the configured path via `cargo metadata`.

fix: Support a custom target dir

---

CHANGELOG.adoc
Cargo.lock
Cargo.toml
src/dfx/Cargo.toml

Update agent-rs and other dependencies
Fixes https://dfinity.atlassian.net/browse/SDK-469
`cargo outdated -R` once again reports nothing out of date.

chore: update agent-rs (0.17.0) and other dependencies

---

nix/sources.json
scripts/dfx-asset-sources.sh
scripts/prepare-dfx-assets.sh
scripts/write-dfx-asset-sources.sh

Download the motoko-base library sources from the versioned tarball, rather than from a repo clone.
The `motoko-base` repo entry is still in nix/sources.json because our nix setup still uses it when it builds its version of dfx.
Fixes https://dfinity.atlassian.net/browse/SDK-217
e2e tests cover this, but I also ran before- and after- and verified that everything is the same, including permissions.

build: Use versioned motoko-base tarball rather than copying from a repo clone

---

.github/CONTRIBUTING.adoc
scripts/update-motoko.sh

Adds a script to update Motoko, so that it's easier to make PRs for that
`./scripts/update-motoko.sh 0.6.28` and then inspect diff

chore: add script to update motoko

---

src/dfx/src/commands/canister/create.rs
src/dfx/src/commands/canister/delete.rs
src/dfx/src/commands/canister/install.rs
src/dfx/src/commands/canister/sign.rs
src/dfx/src/commands/deploy.rs
src/dfx/src/commands/diagnose.rs
src/dfx/src/commands/fix.rs
src/dfx/src/commands/wallet/mod.rs
src/dfx/src/commands/wallet/upgrade.rs
src/dfx/src/lib/environment.rs
src/dfx/src/lib/models/canister_id_store.rs
src/dfx/src/lib/operations/canister/deploy_canisters.rs
src/dfx/src/lib/operations/canister/install_canister.rs
src/dfx/src/lib/root_key.rs

This eliminates a bunch of unwrap() and expect() calls that can never trigger, because the Environment in question is always an AgentEnvironment anyway.  In practice, Environment::get_network_descriptor can never be called, so it now calls `unreachable!()`.
This is preliminary work for system-wide dfx start
e2e tests will cover it

refactor: Environment.get_network_descriptor() returns a ref, not an option

---

docs/cli-reference/dfx-identity.md
docs/cli-reference/dfx-replica.md
docs/cli-reference/dfx-start.md
docs/cli-reference/dfx-wallet.md

CLI reference moved back to this repo. This pulls back in what was added to the `dfx0.10.1` branch before it moved back here.
Docs. Not tested.

chore: port back from portal what was added for dfx 0.10.1 already

---

src/dfx/src/commands/identity/deploy_wallet.rs
src/dfx/src/commands/identity/get_wallet.rs
src/dfx/src/commands/identity/set_wallet.rs

There were three places that created a new NetworkDescriptor rather than using the one already available from the AgentEnvironment.  This reduces the call points to get_network_descriptor() to the four places where it's actually required:
- create_agent_environment
- start, bootstrap, ping commands
Covered by e2e tests

refactor: use AgentEnvironment.get_network_descriptor() rather than creating a second one

---

e2e/assets/inter/Cargo.toml
e2e/assets/inter/dfx.json
e2e/assets/inter/patch.bash
e2e/assets/inter/src/counter_mo/main.mo
e2e/assets/inter/src/counter_rs/Cargo.toml
e2e/assets/inter/src/counter_rs/counter.did
e2e/assets/inter/src/counter_rs/lib.rs
e2e/assets/inter/src/inter2_mo/main.mo
e2e/assets/inter/src/inter2_rs/Cargo.toml
e2e/assets/inter/src/inter2_rs/lib.did
e2e/assets/inter/src/inter2_rs/lib.rs
e2e/assets/inter/src/inter_mo/main.mo
e2e/assets/inter/src/inter_rs/Cargo.toml
e2e/assets/inter/src/inter_rs/lib.did
e2e/assets/inter/src/inter_rs/lib.rs
e2e/tests-dfx/inter.bash

Implements [SDK-158](https://dfinity.atlassian.net/browse/SDK-158).
Testing inter-canister calls:
- calling motoko canister from rust canister
- calling rust canister from motoko canister
- calling rust canister from rust canister, trough motoko canisters
- calling motoko canister from motoko canister, trough rust canisters
based on: https://github.com/dfinity/cdk-rs/tree/a639e75d31bae959d4dc12f8b6e3e282d55e997b/examples/counter
```console
bats e2e/tests-dfx/inter.bash
```

test: add e2e test for inter-canister calls

---

CHANGELOG.adoc
e2e/tests-dfx/ledger.bash
src/dfx/src/commands/ledger/account_id.rs
src/dfx/src/commands/ledger/balance.rs
src/dfx/src/commands/ledger/create_canister.rs
src/dfx/src/commands/ledger/mod.rs
src/dfx/src/commands/ledger/notify.rs
src/dfx/src/commands/ledger/top_up.rs
src/dfx/src/commands/ledger/transfer.rs
src/dfx/src/lib/nns_types/account_identifier.rs

Addresses SDK-508. dfx allows one to calculate ledger addresses for subaccounts, but has no way to send tokens from a subaccount. This adds a `--from-subaccount` flag to the four relevant ledger commands, as well as a `--subaccount` flag to `dfx ledger balance` for convenience.

feat: `--from-subaccount` flag on ledger commands

---

Cargo.lock
src/dfx/Cargo.toml

This adds a feature flag so you can run `cargo build --features vendored-openssl` to quickly change the compilation mode without needing to edit Cargo.toml. Useful both for development, and for building from source on e.g. Alpine.

chore: Add `vendored-openssl` feature

---

nix/sources.json
scripts/dfx-asset-sources.sh
scripts/prepare-dfx-assets.sh
scripts/update-motoko.sh
scripts/write-dfx-asset-sources.sh

In sources.json:
1. Remove motoko-base definition
2. Rename motoko-base-tarball to motoko-base
The motoko-base definition, which referenced the next-moc branch in the motoko-base repo, was no longer used.
No need for anything in the changelog because these are just internal references

refactor: motoko-base-tarball -> motoko-base

---

CHANGELOG.adoc
docs/cli-reference/dfx-ping.md
e2e/tests-dfx/identity.bash
e2e/tests-dfx/ping.bash
e2e/utils/_.bash
src/dfx/src/commands/ping.rs
src/dfx/src/lib/environment.rs
src/dfx/src/lib/network/network_descriptor.rs

The `ping` command uses the default identity, which means it has side effects: it creates the default identity if it does not exist.
To work around this, the e2e tests run ping with a throw-away config root, in order to discard the newly created identity.  However, with the upcoming system-wide dfx changes, dfx will sometimes use configuration within the config root to find the local server.
We can avoid this altogether by making ping use the anonymous identity.
Fixes https://dfinity.atlassian.net/browse/SDK-505
Updated e2e tests.

fix: dfx ping uses the anonymous identity and does not require dfx.json

---

CHANGELOG.adoc
src/dfx/assets/new_project_node_files/package.json

Resolves an issue with running `npm start` in a fresh project, leading to the message 
```
TypeError: cli.isMultipleCompiler is not a function 
```
Fixes SDK-541
Run locally with a new project

chore: updates webpack dependencies

---

Cargo.lock
src/dfx/Cargo.toml

semver changes: 
- wasmparser 0.85 -> 0.86
- sysinfo 0.23 -> 0.24

chore: bump dependencies

---

e2e/tests-dfx/create.bash
src/dfx/src/lib/operations/canister/create_canister.rs

Currently, `dfx deploy --network ic --no-wallet` or `dfx canister --network ic create --no-wallet` provides this amazingly unhelpful error message:
```
Error: The replica returned an HTTP Error: Http Error: status 404 Not Found, content type "text/html", content: <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.21.3</center>
</body>
</html>
```
This catches the specific case of 404 on canister creation and provides a more useful error message.

fix: Provide useful error when `provisional_create_canister_with_cycles` 404s

---

CHANGELOG.adoc
src/dfx/assets/new_project_motoko_files/__dot__gitignore
src/dfx/assets/new_project_rust_files/__dot__gitignore

Files in `src/declarations` are for use by IDEs, not meant to be edited, and generated from sources so not needed to be added to source control, so add them to .gitignore for new projects.
Tested locally
```
[~/] $ dfx new decl && cd decl
[~/decl] $ dfx start --background
[~/decl] $ dfx deploy
[~/decl] $ git status
On branch master
nothing to commit, working tree clean
```

fix: add src/declarations to .gitignore for new projects

---

CHANGELOG.adoc
Cargo.lock
Cargo.toml
src/dfx/Cargo.toml
src/dfx/src/lib/builders/assets.rs
src/dfx/src/lib/canister_info/assets.rs
src/dfx/src/lib/installers/assets/mod.rs

No longer copies asset source directory contents to an output directory.  Now synchronizes assets directly from asset source directories.
This is to support upcoming changes that place asset configuration files alongside asset files.
Covered by existing e2e tests.

chore: upgrate to agent-rs 0.18.0

---

src/dfx/src/commands/ledger/create_canister.rs
src/dfx/src/commands/ledger/notify/create_canister.rs
src/dfx/src/commands/ledger/notify/top_up.rs
src/dfx/src/commands/ledger/top_up.rs
src/dfx/src/commands/wallet/add_controller.rs
src/dfx/src/commands/wallet/authorize.rs
src/dfx/src/commands/wallet/deauthorize.rs
src/dfx/src/commands/wallet/remove_controller.rs
src/dfx/src/commands/wallet/send.rs

Just to make it easier to find out what wasn't recognized as a principal

fix: when failing to convert a string to a principal, include the string in context

---

CHANGELOG.adoc
e2e/tests-dfx/bitcoin.bash
e2e/tests-dfx/canister_http.bash
e2e/tests-dfx/certificate.bash
e2e/tests-dfx/ping.bash
e2e/utils/_.bash
src/dfx/src/commands/bootstrap.rs
src/dfx/src/commands/ping.rs
src/dfx/src/commands/start.rs
src/dfx/src/config/dfinity.rs
src/dfx/src/lib/provider.rs

If `--host <addr>:0` is passed to `dfx start`, the dfx (icx-proxy) webserver will listen on an ephemeral port.  However, dfx will not connect to the running server unless dfx.json is first modified to reflect the dynamically-allocated port.
This shows up in the e2e test suite: after `dfx start`, the setup functions alter dfx.json.  Reviewers can see this in `_.bash`, which no longer alters dfx.json after `dfx start`.
In the upcoming system-wide dfx server changes, in many (if not most) cases there will not be a `local` network entry in dfx.json (project or shared) at all.  This means that tests would have to add a local network entry, which would change the conditions of the test.
`dfx start` also stores the port of the running webserver port in `.dfx/webserver-port`.  This PR makes dfx …

feat: look up running webserver port

---

src/dfx/src/commands/canister/delete.rs
src/dfx/src/commands/canister/send.rs
src/dfx/src/commands/ledger/create_canister.rs
src/dfx/src/commands/ledger/notify/create_canister.rs
src/dfx/src/commands/ledger/notify/top_up.rs
src/dfx/src/commands/ledger/top_up.rs
src/dfx/src/commands/wallet/add_controller.rs
src/dfx/src/commands/wallet/authorize.rs
src/dfx/src/commands/wallet/deauthorize.rs
src/dfx/src/commands/wallet/remove_controller.rs
src/dfx/src/commands/wallet/send.rs
src/dfx/src/lib/identity/identity_utils.rs

Use `{:?}` to display any special characters in a principal that failed to parse

fix: use debug formatter for principals that fail to parse

---

e2e/tests-dfx/migrate.bash

This test is failing quite often.
Fixes https://dfinity.atlassian.net/browse/SDK-581

test: disable e2e migrate test on ic-ref due to flakiness

---

CHANGELOG.adoc
src/dfx/src/commands/replica.rs
src/dfx/src/commands/start.rs
src/dfx/src/config/dfinity.rs
src/dfx/src/lib/bitcoin/adapter/config.rs

The bitcoin adapter's logging can be very verbose if `debug` logging is enabled, making it difficult to make sense of what's going on. On the other hand, these logs are useful for triaging problems.
To get the best of both worlds, this commit adds support for an additional configuration option in `dfx.json`:
```
"defaults": {
"bitcoin": {
"enabled": true,
"nodes": ["127.0.0.1:18444"],
"log_level": "info" <------- users can now configure the log level
},
```
By default, a log level of "info" is used, which is relatively quiet. Users can change it to "debug" for more verbose logging.
I ran `dfx start` with various configurations of `dfx.json` and verified from the logs that the bitcoin adapter gets initialized with the expected log level.

feat: Allow users to configure logging level of bitcoin adapter

---

CHANGELOG.adoc
src/dfx/src/lib/bitcoin/adapter/config.rs

The underlying issue (panic if the btc adapter was started within `<idle seconds>` after system restart) was fixed in the adapter.
Fixes https://dfinity.atlassian.net/browse/SDK-465
Covered by CI

fix: Remove hardcoded BTC adapter idle seconds setting

---

.github/workflows/e2e.yml

The rust e2e tests sometimes time out after 35 minutes.  This PR widens the timeout to 45 minutes.  This is too long, but we will soon remove the `ic-cdk-optimizer` step, which will reduce the test time substantially.  In the meantime, having to manually rerun failed tests frequently is worse.

test: widen e2e timeout to account for rust test timeouts

---

.mergify.yml

Hydra no longer reports (or checks) any statuses, so remove these from the mergify config
Also, add the `license-check:required` (cargo deny) step

chore: update mergify config for hydra removal, GH-based license check

---

docs/cli-reference/dfx-wallet.md

Moving some things around in the docs. It makes more sense to delete it in dfinity/portal and copy some things here.

chore: move cli reference examples from portal to sdk repo

---

CHANGELOG.adoc
Cargo.lock
e2e/tests-dfx/rust.bash
src/dfx/Cargo.toml
src/dfx/src/lib/builders/rust.rs

Optimize rust canister wasm module via ic-wasm library instead of ic-cdk-optimizer.
This might make CI faster.
`dfx build` in a default rust canister project. The optimized wasm was the same w/o this refactor.

refactor: optimize from ic-wasm

---

.github/workflows/e2e.yml

The rust e2e tests are now taking <25 minutes

test: reduce e2e test timeout to 30 minutes

---

CHANGELOG.adoc
src/dfx/src/actors/replica.rs

Turn on ECDSA signature signing by default with a test key named "Secp256k1:dfx_test_key".
This enables developers to use threshold ECDSA system APIs when deploying code in a local dev environment.
It has been tested manually to be working.

feat: Enable threshold ecdsa signature

---

.github/workflows/publish.yml

Updates to reflect new dynamic library dependencies.
Here is the failed beta build: https://github.com/dfinity/sdk/runs/7259707343?check_suite_focus=true

chore: update expected dynamic-link libraries

---

CHANGELOG.adoc
src/dfx/src/actors/replica.rs

Reverts dfinity/sdk#2318
This change is preventing us from updating to the latest hotfix replica (example: https://github.com/dfinity/sdk/pull/2341 and [build failure](https://github.com/dfinity/sdk/runs/7326295725?check_suite_focus=true#step:8:1357)).  Will re-incorporate this change when future replica releases support it.

chore: Revert "feat: Add additional logging from bitcoin canister in replica."

---

CHANGELOG.adoc

Just updates the changelog so that changes after dfx 0.11.0 go in the right place

chore: update changelog post dfx 0.11.0

---

e2e/assets/custom_canister/dfx.json
src/dfx/src/config/dfinity.rs

Adds a test for https://github.com/dfinity/sdk/pull/2351, and updates the custom deserializer to use a default for the `build` field.
There's no change to the changelog, because this is covered by an existing entry, in the current `UNRELEASED` section.
Updated an existing e2e test.

fix: make sure dfx can load dfx.json with a custom canister with no build step

---

src/dfx/src/commands/bootstrap.rs
src/dfx/src/commands/start.rs
src/dfx/src/lib/models/canister_id_store.rs
src/dfx/src/lib/webserver.rs

Add/refactor `CanisterIdStore::new` to make it possible to create a CanisterIdStore, with mappings for remote canister ids, without having to construct an AgentEnvironment.
See https://github.com/dfinity/sdk/pull/2375 for an example of where one might want to do this.
Covered by existing e2e tests.

refactor: CanisterIdStore::new

---

.github/workflows/update-replica-version.yml

Use https://github.com/dfinity-bot to create the PR produced by `.github/workflows/update-replica-version.yml` workflow. This will help avoid asking GitHub Bot to sign CLA (example https://github.com/dfinity/sdk/pull/2379).
Fixes/continuation of: https://github.com/dfinity/sdk/pull/2377
forked and tested there

fix: use `dfinity-bot` instead of `github bot` to avoid signing CLA in GHA workflow

---

e2e/tests-dfx/mode_reinstall.bash
e2e/tests-dfx/upgrade_check.bash

Two test files were still doing their own setup and teardown.  In particular, this means they didn't set up an isolated $HOME directory.

refactor: standard setup and teardown for mode_reinstall, upgrade_check

---

CHANGELOG.adoc
e2e/tests-dfx/build.bash
src/dfx/src/lib/operations/canister/install_canister.rs

When dfx deploy and dfx canister install upgrade a canister, they ensure that the
new candid interface is compatible with the previous candid interface.  They write
a file with extension .old.did that contains the previous interface.  In some
circumstances these files could be written in the project directory.  dfx now
always writes them under the .dfx/ directory.
Fixes https://dfinity.atlassian.net/browse/SDK-643

fix: always write .old.did under .dfx/

---

CHANGELOG.adoc
e2e/tests-dfx/wallet.bash
src/dfx/src/commands/canister/delete.rs
src/dfx/src/commands/wallet/upgrade.rs
src/dfx/src/lib/identity/mod.rs
src/dfx/src/lib/migrate.rs

If there's no `wallets.json` file, or if `wallets.json` doesn't have a wallet id for a given identity/network, this isn't an error.  It instead means there's no wallet for that identity on that network.
Actual errors could be things like permissions errors, or malformed json.
This PR changes `Identity::wallet_canister_id` to return `DfxResult<Option<Principal>>`.
As can be seen in the PR, most callers discard any error details and assume that any error means that there was no wallet.  But we should report things like permissions problems or malformed errors as errors.
before
```
$ dfx --identity alice wallet upgrade
Error: Failed to get wallet canister id for identity 'alice' on network 'local'.
Caused by: Failed to get wallet canister id for identity 'alice' on network …
```

refactor: Identity::wallet_canister_id returns DfxResult<Option<Principal>>

---

src/dfx/src/commands/language_service.rs
src/dfx/src/lib/models/canister_id_store.rs

Use Config.get_temp_path() rather than Environment.get_temp…_dir() for canister id store path lookup.
They are the same value (`.dfx/` directory next to `dfx.json`).
If there's no Config, we can use None for the canister id store path.  Anywhere that might call CanisterIdStore.save() has already checked get_config_or_anyhow().
This removes another caller of Environment.get_temp_dir()
Handled by existing e2e tests

refactor: canister id store: use config temp path

---

CHANGELOG.adoc
src/dfx/src/actors/replica.rs

The mainnet runs with canister sandboxing, so dfx also should
run with canister sandboxing to be consistent otherwise some
upcoming features like deterministic time slicing would not
work in dfx.

feat: enable canister sandboxing

---

CHANGELOG.adoc
docs/cli-reference/dfx-canister.md
e2e/tests-dfx/update_settings.bash
e2e/tests-dfx/wallet.bash
src/dfx/src/commands/canister/update_settings.rs

Resolves SDK-583.
A user mistakenly entered `--controller`, in `dfx canister update-settings`, instead of `--add-controller`, removing the DFX principal as a controller. This solves such a confusion by renaming it to `--set-controller`.

feat: Change `--controller` to `--set-controller`

---

CHANGELOG.adoc
e2e/tests-dfx/wallet.bash
src/dfx/src/commands/start.rs
src/dfx/src/lib/environment.rs
src/dfx/src/lib/identity/mod.rs

This PR renames `Environment::get_temp_dir()` to `get_project_temp_dir()`.  It returns either the `.dfx/` directory in the same directory as `dfx.json`, or None if there is no project.
`Environment::get_temp_dir()` is only used in two places:
- when looking up the wallet id for a network with ephemeral canister ids, which only makes sense within a project directory
- when renaming an identity, which already allows for the wallet configuration file to not exist
This also means that dfx no longer creates a temporary directory if run outside of a project directory.  These temporary directories were never cleaned up.  It would never make sense to write or read a wallets.json file within such a temporary directory.
before
```
$ dfx wallet upgrade
dfx.json not found, using default.
Error: …
```

refactor: make temp dir optional

---

src/dfx/src/commands/canister/update_settings.rs

Fixes a panic in `dfx canister update-settings` that only happens when run in a debug build.
before
```
$ dfx canister update-settings
thread 'main' panicked at 'Command update-settings: Argument or group 'set_controller' specified in 'conflicts_with*' for 'add-controller' does not exist', /Users/ericswanson/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.2.12/src/builder/debug_asserts.rs:237:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
after
```
$ dfx canister update-settings
error: The following required arguments were not provided:
--all
USAGE:
dfx canister update-settings --all
```

fix: update-settings conflicts controller -> set-controller

---

e2e/tests-dfx/call.bash
e2e/tests-dfx/ping.bash
e2e/tests-dfx/sign_send.bash
e2e/utils/_.bash

Just a small change for brevity.
Upcoming changes add a few more environment variables, and they will also use prefix `E2E_`

refactor: rename DFX_E2E_TEMP_DIR -> E2E_TEMP_DIR

---

e2e/tests-dfx/dfx_install.bash
e2e/tests-dfx/error_context.bash
e2e/tests-dfx/usage_env.bash
e2e/utils/_.bash

You can now set `E2E_CACHE_ROOT` to some directory that is separate from your normal `$HOME/.cache`, but still isolated for tests.  If set, e2e tests will use that instead of an empty directory per-test.
- speeds up tests (because dfx doesn't have to install the cache for each test)
- fewer pop-up messages asking if you want to allow replica to open a network listener
A few tests needed to use a unique cache directory no matter what.
Improves the local e2e testing experience a little if you do something like
```
export E2E_CACHE_ROOT=$HOME/.e2e-cache-root
```

test: allow E2E_CACHE_ROOT to provide a cache root for tests

---

e2e/tests-dfx/bitcoin.bash
e2e/tests-dfx/canister_http.bash
e2e/tests-dfx/start.bash

The intent of this PR is to reduce test flakiness in CI in a few tests.
After a test restarts the replica, and waits until a `dfx canister call` succeeds, sometimes the next`dfx canister call` fails with this replica error:
```
IC0515: Certified state is not available yet. Please try again...
```
This PR adds a small delay after `dfx canister call` succeeds the first time, then waits again until `dfx canister call` succeeds, before proceeding.
Also renamed some tests to not have parenthesis in the name, to make it easier to use `bats -f "<name of test>"` to run a single test.

test: retry canister call, after a delay, when restarting replica

---

docs/cli-reference/dfx-bootstrap.md

#2427 removed parameter. This removes the param from the docs

chore: remove --root from docs

---

src/dfx/assets/language_bindings/index.js.hbs
src/dfx/src/lib/builders/mod.rs

The JSDOC export for create actor was not injecting the path to canister_name.did.js. Also the comment for the export was included unneccesarily for type:node declarations
manual testing for node_compatibility true and false

fix: resolves jsdoc service typing and trailing comment

---

scripts/release.sh

This matches the step already documented in the release process notes.

fix: release process should start --clean

---

.github/workflows/shellcheck.yml
e2e/assets/canister_args/patch.bash
e2e/assets/default_args/patch.bash
e2e/assets/empty_canister_args/patch.bash
e2e/assets/invalid/patch.bash
e2e/tests-dfx/basic-project.bash
e2e/tests-dfx/certified_info.bash
e2e/tests-dfx/identity_command.bash
e2e/tests-dfx/remote.bash
e2e/tests-dfx/sign_send.bash
e2e/tests-dfx/usage.bash
e2e/tests-dfx/wallet.bash
e2e/utils/_.bash
e2e/utils/assertions.bash

Currently we only shellcheck the explicit e2e tests. This extends shellcheck to the entire e2e directory, including asset patch scripts and the utils scripts.

chore: run shellcheck on the rest of the scripts

---

docs/cli-reference/dfx-canister.md

I messed up in #2448, need to redo some links

chore: redo docs links again

---

CHANGELOG.md
src/dfx/assets/language_bindings/index.js.hbs
src/dfx/src/lib/builders/mod.rs

If you have a pre-initialized agent in your JS code, you can now pass it to createActor's options. Conflicts with the agentOptions config - if you pass both the agent option will be used and you will receive a warning.
```js
const plugActor = createActor(canisterId, {
agent: plugAgent
})
```
Manual testing of output

feat: createactor options accept pre-initialized agent

---

CHANGELOG.md
e2e/assets/expect_scripts/create_identity_with_password.exp
e2e/assets/expect_scripts/import_export_identity_with_password.exp
e2e/assets/expect_scripts/rename_identity_with_password.exp
e2e/assets/expect_scripts/wrong_password_rejected.exp
src/dfx/src/lib/identity/pem_encryption.rs

When testing something else, I noticed that when prompting for the decryption password for an identity, the prompt is `Please enter a passphrase for your identity`.  However, at that point dfx is not asking for **a** passphrase, it's asking for **the** passphrase. 
Updated e2e tests

fix: Small grammar change to identity password decryption prompt

---

.github/workflows/e2e.yml
CHANGELOG.md
docs/cli-reference/dfx-info.md
docs/cli-reference/dfx-start.md
docs/cli-reference/index.md
docs/dfx-json-schema.json
docs/networks-json-schema.json
docs/process/release.adoc
e2e/tests-dfx/bootstrap.bash
e2e/tests-dfx/describe_local_network.bash
e2e/tests-dfx/info.bash
e2e/tests-dfx/remote.bash
e2e/utils/_.bash
scripts/release.sh
src/dfx/assets/new_project_motoko_files/README.md
src/dfx/assets/new_project_node_files/webpack.config.js
src/dfx/assets/new_project_rust_files/README.md
src/dfx/src/commands/info/mod.rs
src/dfx/src/commands/info/webserver_port.rs
src/dfx/src/commands/mod.rs
src/dfx/src/config/dfinity.rs
src/dfx/src/lib/network/local_server_descriptor.rs
src/dfx/src/lib/provider.rs

Make the default shared local network use port 4943 ("hex for `IC`"), so that if a project-specific network happens to be running, dfx won't connect to it when trying to connect to the local shared network.
Also added command `dfx info webserver-port` to display the port, since it may come from one of several places.
Fixes https://dfinity.atlassian.net/browse/SDK-216
Tested locally and added e2e tests

feat: change port for default shared local network from 8000 to 4943

---

CHANGELOG.md
src/dfx/src/config/dfinity.rs
src/dfx/src/lib/operations/canister/create_canister.rs

Installing NNS canisters involves operating on canisters not listed in dfx.json.
In two places, the existing code checks for canister data in dfx.json.  It doesn't matter if the data is missing, but if the canister is not listed at all, the cli bails out.  E.g. it checks whether the canister has a remote canister ID; it doesn't need to have one, but if the canister is not listed, we crash.  Instead, we would like to treat this in the same way as the data being absent.
We wish to support the case where one dfx server is shared across multiple projects and explicitly do not want to add entries to the dfx.json of a particular project unless the user chooses to do so.
In the development branch `dfx nns install` this change allows NNS canisters to be installed without listing them in dfx.json.

feat: Support installing canisters not in dfx.json

---

CHANGELOG.md
src/dfx/src/lib/operations/canister/create_canister.rs

dfx contains the wrong fee. 0.1T is correct

fix: creating a canister costs 0.1T

---

.github/workflows/update-docs.yml

Continuation of #2494 since #2490 still does not pass CI.

chore: fix forked PR docs workflow

---

Cargo.lock
src/canisters/frontend/ic-asset/Cargo.toml

The pathdiff dependency from ic-asset is unused. This removes it.

chore: remove unused dependency pathdiff

---

CHANGELOG.md
e2e/tests-dfx/frontend.bash
src/dfx/assets/new_project_node_files/package.json
src/dfx/assets/new_project_node_files/webpack.config.js

for default node starter template: adds webpack copy plugin to copy `.ic-assets.json*` file from `src` to `dist`

fix(frontend-canister): copy `.ic-assets.json` file from `src` to `dist`

---

.github/workflows/audit.yml
.github/workflows/consistent-sources.yml
.github/workflows/deny.yml
.github/workflows/e2e.yml
.github/workflows/fmt.yml
.github/workflows/lint.yml
.github/workflows/prepare-dfx-assets.yml
.github/workflows/publish-manifest.yml
.github/workflows/publish.yml
.github/workflows/shellcheck.yml
.github/workflows/unit.yml

Upgrading from `actions/checkout@v1` or `actions/checkout@v2` to `@v3`.
I had an interesting CI failure today: https://github.com/dfinity/sdk/runs/8102506163?check_suite_focus=true
When the e2e build_dfx (ubuntu) step [ran](https://github.com/dfinity/sdk/runs/8101880196?check_suite_focus=true#step:2:666), it checked out one merge commit, and built the dfx binary:
```
HEAD is now at 57088df8 Merge 00bb8ac0c5298534ef68ca49a5dd3f03f5cb4105 into 21048c4b76896316b72b05288a1231267bdc47d3
```
Then, another PR was merged to master.  The merged PR contained a new test, and a new dfx command.  The binary built above did not contain the new command that the new test required, because it was built from a commit when that command did not exist.
Next, the dfx/info tests …

chore: use actions/checkout@(v1, v2) to v3

---

CHANGELOG.md
public/install/200_downloader.sh

Adds retry logic to the install script so that downloading dfx is less flaky. Added flag:
```
- curl
- connect-timeout: max time allowed to set up the connection
- retry: number of retries performed if something goes wrong
- wget
- tries: number of retries performed if something goes wrong
- timeout: number of seconds to wait for anything (dns, connection set up, any data received during download) before retrying
- waitretry: number of seconds to wait before retrying
```
Fixes [SDK-671](https://dfinity.atlassian.net/browse/SDK-671)
Some manual tests with @smallstepman show that the added flags do the right thing.

chore: add retry logic to download script

---

src/dfx/src/lib/canister_info.rs
src/dfx/src/lib/canister_info/assets.rs
src/dfx/src/lib/canister_info/motoko.rs

Removes the `build_root` and `canister_root` fields from CanisterInfo.
- `build_root` was only used by joining the canister name to it.   However, `build_root.join(canister_name)` is already known as `output_root`, so used that instead.
- The method names (unchanged in this PR) `get_build_wasm_path()` and `get_build_idl_path()` aren't great, because they refer to files within the `output_root` (also unchanged in this PR, though more obvious now).  However, there is another method named `get_output_idl_path()`.  I hope to untangle this in a PR to follow.
- `canister_root` wasn't used by anything.
Covered by existing e2e tests

refactor: remove CanisterInfo build_root, canister_root

---

CHANGELOG.md
e2e/tests-dfx/wallet.bash
src/dfx/src/commands/canister/deposit_cycles.rs

> I think the default behavior if a wallet-id or name is not provided would be to use this default wallet for the developer’s identity.
Fixes [feature request on the forum](https://forum.dfinity.org/t/dfx-0-10-0-dfx-canister-deposit-cycles-returns-error/13251/6).
Added an e2e test, also tested manually

chore: deposit-cycles uses default wallet if none is specified

---

CHANGELOG.md
src/dfx/src/commands/start.rs

Now, only the foreground process cleans.
The cleaning by the background was causing the foreground process to fail sometimes, because the webserver port file would be deleted.  The foreground process creates that file as empty, then waits until the background process populates it with the webserver port.
Intended to fix https://dfinity.atlassian.net/browse/SDK-720, though there may be an underlying cause that this bug hides.
Manually.
1. `dfx start --clean --background`
2. `kill -9 <dfx pid> <replica pid>`
3. Notice that `icx-proxy` is still running
4. `dfx start --clean --background`
Before:
```
$ dfx-wip start --clean --background
There is no project-specific network 'local' because there is no project (no dfx.json).
Using the default definition for the 'local' shared network because …
```

fix: for dfx start --clean --background cleaning twice

---

CHANGELOG.md
src/dfx/src/lib/operations/canister/install_canister.rs

If an error occurs during parsing Candid or stable signature, dfx will error out. This blocks canister upgrade if the generated .did or .most file has bugs that fails the parser.
The fix is to move the checking code into a separate function, dfx checks if the error comes from the 
the actual checking or the preparation steps, and allow users to skip the checking if parsing fails.
Tested manually, but it's hard to test in CI, as it requires pulling in ic-wasm binary as a dependency.

fix: compatibility check error should not block canister install

---

CHANGELOG.md
src/dfx/src/lib/nns/install_nns/canisters.rs

Previously the governance canister wasm was being used in place of the swap canister wasm by mistake.
With this fix, and another that deals with ic commit mismatches, I am able to create an SNS, which was previously not possible.
Testing SNS creation is to be done in another repo, as most of the complexity is outside the scope of the sdk.  The error was discovered while preparing such a test.

fix: Correct swap wasm file

---

CHANGELOG.md
e2e/tests-dfx/project_local_network.bash
src/dfx/src/commands/start.rs
src/dfx/src/commands/stop.rs
src/dfx/src/lib/network/local_server_descriptor.rs
src/dfx/src/lib/provider.rs

dfx 0.12.x stores the pid file for a project-specific network in `.dfx/network/local/pid`, while dfx <= 0.11.x store it in `.dfx/pid`. 
This change makes it so `dfx start` and `dfx stop` look in both places.
Fixes https://dfinity.atlassian.net/browse/SDK-726

fix: dfx stop and dfx start take into account processes from dfx <= 0.11.x

---

CHANGELOG.md
e2e/tests-dfx/install.bash
src/dfx/src/commands/canister/install.rs
src/dfx/src/lib/operations/canister/deploy_canisters.rs
src/dfx/src/lib/operations/canister/install_canister.rs

`dfx deploy` automatically determines whether to use the `install` or `upgrade` modes depending on the canister state. This provides that same functionality to `dfx canister install`, by passing `auto` for the `--mode`. The default remains `install`. 
Fixes #2013 and SDK-590. This was chosen over the suggested feature, `dfx deploy --no-build`, for better consistency with semantics.

feat: Add `--mode=auto` to `dfx canister install`

---

.github/workflows/audit.yml
.github/workflows/consistent-sources.yml
.github/workflows/deny.yml
.github/workflows/e2e.yml
.github/workflows/fmt.yml
.github/workflows/lint.yml
.github/workflows/motoko-updater.yml
.github/workflows/niv-updater.yml
.github/workflows/pr.yml
.github/workflows/prepare-dfx-assets.yml
.github/workflows/publish-manifest.yml
.github/workflows/publish.yml
.github/workflows/shellcheck.yml
.github/workflows/unit.yml
.github/workflows/update-docs.yml
.github/workflows/update-replica-version.yml
CHANGELOG.md

CI sometimes, perhaps even often, has to wait minutes to tens of minutes for runners to be available.  Reducing the total number of CPU minutes we spend is a way of freeing up compute capacity.
If a developer (e.g. myself) pushes a branch, then notices a change that needs to be made and pushes again, the earlier job still runs to completion even though it is no longer of interest.  It would be nice to kill the earlier job when it is superseded.
Github's concurrency provides setting to do just this:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
I have opted for the configuration where each workflow has its own groups, so that a kill command from one workflow doesn't kill others. …

chore: If pushing twice to the same branch, later jobs kill earlier ones

---

CHANGELOG.md
e2e/tests-dfx/build.bash
src/dfx/src/config/dfinity.rs
src/dfx/src/lib/builders/custom.rs
src/dfx/src/lib/canister_info/custom.rs

We recently added the ability to specify a URL for a custom canister's wasm field.  This adds the same support for a custom canister's candid field.
Fixes https://dfinity.atlassian.net/browse/SDK-732
Updated an e2e test.

feat: custom canisters: allow candid field to specify a URL

---

scripts/workflows/provision-darwin.sh
scripts/workflows/provision-linux.sh

Make the provision scripts check against the actual test name.  The tests worked anyway because the tests build icx-asset if it wasn't built already, but building it in the provision step gives us more information about how long it took to build.
By inspection of test run

fix: build icx-asset in the provision step

---

e2e/tests-dfx/nns.bash
src/dfx/src/commands/nns/import.rs

`dfx nns import` sets only some NNS canister IDs, as not all back end NNS canister IDs are included in the upstream dfx file we use.
Upstream now includes those canisters.  It will be 1-2 weeks before the code in master is blessed, but we can verify now that we will have those canister IDs.
Note: This PR dos not address the fact that dfx nns install does not set front end canister IDs.  The front end canister IDs are more complicated.  The canister IDs created by `ic-nns-init` don't match prod, but ic-nns-init also manages to use some of the front end canister IDs for other purposes.  The only reliable source for those canister IDs is the code for `dfx nns install`.
- `ic nns import` now respects an environment variable `DFX_IC_SRC` that tells `dfx nns import` to pull the canister details …

test: Import more NNS canister IDs

---

CHANGELOG.md
docs/cli-reference/dfx-info.md
e2e/tests-dfx/info.bash
src/dfx/src/commands/info/mod.rs

Having a universal way to figure out where networks are defined will make writing tutorials much easier.
Added e2e.

feat: dfx info networks-json shows path to networks.json

---

docs/dfx-json-schema.json
docs/networks-json-schema.json

I thought we had some github workflows triggering to add these changes to PRs in flight, but a few recent changes are not reflected in the JSON schema docs.
n/a

chore: update JSON schema docs

---

CHANGELOG.md
src/dfx/assets/new_project_motoko_files/dfx.json
src/dfx/assets/new_project_rust_files/dfx.json

As discussed in yesterday's meeting we discussed removing the version pin from the default project.
tested manually

chore: remove dfx version pin from default project

---

scripts/update-nns.bash

This is needed by the next replica release candidate.  See test failures: https://github.com/dfinity/sdk/actions/runs/3103188746/jobs/5026356601
Tested locally.

fix: add new nns wasm: ic-ckbtc-minter

---

CHANGELOG.md
src/dfx/src/lib/call_bundled.rs
src/dfx/src/lib/mod.rs
src/dfx/src/lib/sns/create_config.rs
src/dfx/src/lib/sns/deploy.rs
src/dfx/src/lib/sns/mod.rs
src/dfx/src/lib/sns/validate_config.rs

There are several bundled binaries, including `ic-admin` and `sns`.  We have a wrapper for calling `sns` but it works perfectly for other bundled binaries as well.  So let's reuse it.
Move the function for calling sns into src/dfx/lib and make the name of the bundled binary a variable.
There is no change in functionality.  Existing tests should suffice.
- This is a noop as there is no change to user-facing functionality

refactor: Factor out code for calling arbitrary bundled binaries

---

CHANGELOG.md
e2e/tests-dfx/generate.bash
src/dfx/assets/language_bindings/index.d.ts.hbs
src/dfx/src/lib/builders/mod.rs

fixes #2615
This fixes two issues, the first was reported in https://github.com/dfinity/sdk/issues/2615.
The 2nd was an issue where the `canister.declarations.bindings` array in `dfx.json` was not always working as expected. 
Fixes #2615 
e2e tests have been provided and it has been manually tested in a new `dfx` project.
- No documentation changes necessary

fix(generate): add missing typescript types and fix issues with bindings array in dfx.json

---

src/dfx/src/commands/canister/info.rs

`dfx canister info` reports an uninformative 'lookup path was unknown' message if the canister doesn't exist, unlike `dfx canister status` whose 404 contains the direct information that the canister doesn't exist. This PR provides a more useful error message in this case.
Fixes SDK-651.

fix: Add useful error message to `dfx canister info`

---

CHANGELOG.md
src/dfx/src/commands/nns/mod.rs
src/dfx/src/lib/nns/install_nns.rs

The `dfx nns`commands are technically ready to use but can be confusing or hard to use, even though they should be very simple.  The following issues are addressed.
`dfx nns install` needs to be run with particular network settings.  There is an existing check that the network type is "system" and an error message but the error message doesn't seem to be helping; it is not clear or explicit enough, it doesn't give people the information they need to configure the network.
**Change:** Expand the error message with explicit steps the user needs to take.
`dfx nns --help` was not showing subcommands.  This was intentional as the nns subcommands were stubbed in, however now the subcommands have been implemented.
**Change:** Make the subcommands public and tweak their descriptions.
No current …

feat: nns usability improvements

---

CHANGELOG.md
e2e/tests-dfx/install.bash
src/dfx/src/commands/canister/install.rs
src/dfx/src/commands/deploy.rs
src/dfx/src/lib/nns/install_nns.rs
src/dfx/src/lib/operations/canister/deploy_canisters.rs
src/dfx/src/lib/operations/canister/install_canister.rs

Implements SDK-701. Automatically confirms y/n checks.

feat: Add a -y flag to deploy/install

---

e2e/tests-dfx/sns.bash
src/dfx/src/lib/nns/install_nns.rs
src/dfx/src/lib/nns/install_nns/canisters.rs

Fix issues wit the latest ic update:
- Add sns index canister but not, strangely, the archive canister.
- Small tweaks to update the tests
See CI

fix: Sns index

---

.github/workflows/e2e.yml

The publish workflow already performs this, so we don't need to duplicate the logic.

refactor: e2e workflow: do not check dynamic-linked libraries

---

src/dfx/src/commands/build.rs

This removes a variable that wasn't being used (warnings were silenced because name was `_all`).

chore: remove unused variable

---

CHANGELOG.md
e2e/assets/remote/envvar/dfx.json
e2e/tests-dfx/remote.bash
src/dfx/src/commands/build.rs
src/dfx/src/commands/generate.rs
src/dfx/src/lib/builders/mod.rs
src/dfx/src/lib/builders/motoko.rs
src/dfx/src/lib/models/canister.rs
src/dfx/src/lib/operations/canister/deploy_canisters.rs

If a canister config specifies a “remote” canister ID, like the NNS subnet canisters do, or if the canister is deployed from another directory locally, it should skip the build step.
Fixes [SDK-766](https://dfinity.atlassian.net/browse/SDK-766)
Added checks to CI that remote canisters are not processed in:
- `dfx deploy`
- `dfx build`
- `dfx generate`

fix: do not build remote canisters

---

docs/cli-reference/dfx-canister.md

It's correctly documented in the dfx cli help
Here's what that looks like:

docs: dfx canister request-status requires canister to be specified

---

.github/workflows/audit.yml
.github/workflows/build-frontend-canister.yml
.github/workflows/e2e.yml
.github/workflows/fmt.yml
.github/workflows/lint.yml
.github/workflows/prepare-dfx-assets.yml
.github/workflows/publish.yml
.github/workflows/unit.yml

There are currently a lot of warnings that make it hard to see real problems.
Some easy-to-fix problems stem from:
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/cache, actions/upload-artifact, actions/cache
- Bump github actions to use later versions of node
See CI
- noop as there are no user facing changes
- noop as there are no user facing changes

chore: Bump github actions that use node v12

---

.github/workflows/pr.yml

It turns out that version 2.4.4 doesn't exist, so all PRs will fail, like here:
https://github.com/dfinity/sdk/actions/runs/3272056132/jobs/5382599495
The workflow actually tests vs the base branch (pull_request_target), so the altering PR used the old version:
https://github.com/dfinity/sdk/actions/runs/3271406085/jobs/5381159987
We actually can't test this on CI, because the workflow runs against `pull_request_target`, and the workflow on the master (base) branch will never pass.   It will have to be merged manually by administrator action.

chore: revert conventional pr title action to 2.2.3

---

CHANGELOG.md
docs/cli-reference/dfx-info.md
e2e/tests-dfx/info.bash
src/dfx/src/commands/info/mod.rs
src/dfx/src/commands/info/replica_port.rs
src/dfx/src/util/network.rs

Adds a command to display the replica listening port.
Fixes https://dfinity.atlassian.net/browse/SDK-777

feat: dfx info replica-port

---

scripts/nns-canister.Dockerfile

To match https://github.com/dfinity/ic/commit/6be560c9b965d9b76e5b85aa052fff5a2937c0c1
See this failed workflow run: https://github.com/dfinity/sdk/actions/runs/3373225804/jobs/5597564891
Run `./scripts/update-replica.sh 669673d380de01c08b7b52b08f57a02367d9096d --update-nns` before and after

fix: update location of icp ledger canister ledger.did

---

docs/migration/dfx-0.12.0-migration-guide.md
docs/migration/index.md

Document the process for upgrading from dfx 0.11.2 to dfx 0.12.0.  Separating these from the changelog is desirable because it presents only the information that a developer needs to know.  We should do this for all versions going forward.
Fixes https://dfinity.atlassian.net/browse/SDK-850
1. With dfx 0.11.2, I created a new project, ran `dfx start` and `dfx deploy`, then verified that the project worked locally.
2. Followed instructions in the migration guide, verified app worked with frontend url
3. Ran `npm start`, opened http://localhost:8080/ , made sure app works
4. Edited src/basic_frontend/src/index.html and verified that changes hotload (is that a verb?)

docs: dfx 0.12.0 migration guide

---

.github/workflows/publish.yml

Use a separate cache for the publish workflow, which does not cache the target directory since it immediately deletes it.

chore: don't cache target on publish

---

src/dfx/src/config/dfinity.rs

Fixes the erroneous doc string reported in [this post](https://forum.dfinity.org/t/dfx-json-actor-with-mandatory-arguments/14454/7) .

fix: clarify doc string for canisters.<canister>.args

---

src/dfx/src/lib/builders/mod.rs

`dfx generate` prints relative paths for all generated files, except for the .did one. This PR makes the .did path relative as well.
Fixes #2768, [SDK-859](https://dfinity.atlassian.net/browse/SDK-859)
Tested manually

chore: dfx generate prints mix between absolute and relative paths

---

CHANGELOG.md
src/dfx/src/commands/canister/delete.rs

[Two reports on the forum](https://forum.dfinity.org/t/cannot-delete-canisters-anymore/11594/15) and code comments indicate that the wallet does not have enough cycles left in the wallet when deleting a canister recently. I'm bumping the margin from 2% to 5% in hopes of avoiding this problem.
Tested manually by Christian on a canister that couldn't be deleted with the previous version

fix: give more cycles margin when deleting canisters

---

.github/workflows/update-docs.yml

The Update Docs workflow breaks on all external PRs, e.g. #2787. I recommend we disable it for now for all PRs from external repos

chore: disable Update Docs workflow on external PRs

---

CHANGELOG.md
docs/cli-reference/dfx-canister.md
e2e/tests-dfx/sign_send.bash
src/dfx/src/commands/canister/call.rs
src/dfx/src/commands/canister/sign.rs
src/dfx/src/util/mod.rs

`dfx canister call` command has an argument `--argument-file` to allow sending the request when argument string is too long for shell. `dfx canister sign` command didn't have this argument so some of the requests possible by `dfx canister call` were not possible to be executed through sign/send workflow. This PR fixes this unfortunate inconvenience:
* add `--argument-file` option to `sign` command
* move the logic related to reading argument string from a file from `call` command to utils so that it can be reused by both `call` and `sign`
* refactor the logic a little to use correct error handling instead of `expect`s
Added e2e test cases. Also did signing manually with compiled `dfx`, including some very long argument strings that didn't fit into CLI arguments.

feat: Add --argument-file option to dfx canister sign

---

e2e/tests-dfx/assetscanister.bash

`ic-hs` can now handle `canister_status` management canister call from a canister querying its own status if the canister does not control itself.

fix: drop an additional step only run by ic-ref in asset canister tests

---

docs/cli-reference/dfx-parent.md

Left out:
- `dfx pull` because it's in progress.
- `dfx toolchain` because we don't exactly support it and it's not clear how it works.

docs: add entries for most top-level commands

---

docs/cli-reference/dfx-canister.md
src/dfx/src/commands/canister/update_settings.rs

Add some detail related to `dfx canister update-settings --set-controller` and multiple controllers.
Fixes https://dfinity.atlassian.net/browse/SDK-823

docs: detail for canister update-settings --set-controller

---

e2e/tests-dfx/identity_command.bash
src/dfx/src/lib/identity/mod.rs

Repeat of #2741, but for `dfx identity import --seed-file`.

fix: Encode curve name in key imported from seed phrase

---

src/dfx/src/config/cache.rs
src/dfx/src/lib/error/cache.rs
src/dfx/src/lib/error/identity.rs
src/dfx/src/lib/identity/identity_manager.rs
src/dfx/src/lib/identity/mod.rs

Renamed error enum names like `Cannot*`, for situations where an operation failed, to the form `*Failed`.
A few names remain of the form `Cannot*`, because they indicate things that one cannot ever do:
- `CannotDeleteDefaultIdentity`
- `CannotDeleteAnonymousIdentity`
- `CannotCreateAnonymousIdentity`
This is in preparation for adding more concrete error types.

refactor: rename error enum names

---

src/dfx/src/lib/error/identity.rs

In order to make it clear where to put new definitions and to avoid merge conflicts.

refactor: alphabetize IdentityError

---

src/dfx/src/lib/identity/identity_manager.rs
src/dfx/src/lib/identity/mod.rs

Remove some explicit calls to `DfxError::new()` which turn out to not be needed.  This is in preparation for upcoming work and will make the diffs a little smaller.
The upcoming work is to remove the identity manager's dependence on `anyhow`, as part of moving it into a crate.

refactor: remove unnecessary explicit calls to DfxError::new

---

.mergify.yml

In order to help avoid commit messages like [this one](https://github.com/dfinity/sdk/commit/d3d2b71c4e60323d48a2ee68ee140bd9f32280a1), alter the mergify configuration to use the "Description" section from the PR description if it's present, otherwise the whole PR description.  Also we don't really need the "How Has This Been Tested" and checklist boilerplate in commit messages.  In any case, we will still have to make sure not to approve PRs with a PR body that is unchanged from the pull request template.
See alsoo https://docs.mergify.com/actions/merge/#commit-message-template
I tried setting up a branch and a [PR against it](https://github.com/dfinity/sdk/pull/2844), but it seems the mergify rules always run against .mergify.yml on the master branch, so that didn't work.  In other …

fix: use Description section for commit message, if it exists

---

Cargo.lock
src/dfx-core/Cargo.toml
src/dfx-core/src/error/identity.rs
src/dfx-core/src/error/mod.rs
src/dfx-core/src/lib.rs
src/dfx/src/lib/error/mod.rs
src/dfx/src/lib/identity/identity_manager.rs
src/dfx/src/lib/identity/mod.rs

Also remove the boxing and dependence on DfxError.
Fixes https://dfinity.atlassian.net/jira/software/c/projects/SDK/issues/SDK-891
[SDK-891]: https://dfinity.atlassian.net/browse/SDK-891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: move IdentityError type to dfx-core crate

---

Cargo.lock
src/dfx-core/Cargo.toml
src/dfx-core/src/error/encryption.rs
src/dfx-core/src/error/identity.rs
src/dfx-core/src/error/io.rs
src/dfx-core/src/error/mod.rs
src/dfx-core/src/fs/mod.rs
src/dfx/src/lib/identity/identity_manager.rs
src/dfx/src/lib/identity/pem_safekeeping.rs

Continuing remove dependencies on the DfxError, DfxResult, and `anyhow` types in preparation for moving the identity manager to a separate crate.
Covered by CI

refactor: pem_safekeeping.write_pem_to_file to return concrete error type

---

src/dfx-core/src/error/identity.rs
src/dfx-core/src/error/structured_file.rs
src/dfx-core/src/json/mod.rs
src/dfx/src/lib/identity/identity_manager.rs

Replacing more `anyhow` usage with concrete error types.
Part of https://dfinity.atlassian.net/browse/SDK-892
Covered by CI.

refactor: identity manager load/save configuration concrete error types

---

src/dfx/src/commands/identity/use.rs
src/dfx/src/lib/identity/identity_manager.rs

Changed IdentityManager::use_identity_named and a few methods that it calls to return std::Result rather than anyhow
Covered by CI

refactor: IdentityManager::use_identity_named to use concrete types

---

src/dfx-core/src/error/identity.rs
src/dfx-core/src/error/io.rs
src/dfx-core/src/fs/mod.rs
src/dfx/src/lib/identity/identity_manager.rs

Preparation to move code to the dfx-core crate.
Covered by CI.

refactor: concrete error types for IdentityManager::remove

---

.github/workflows/e2e.yml
src/dfx-core/src/error/io.rs
src/dfx-core/src/fs/mod.rs

Started to run into clippy warnings about error types being too large, so taking steps to reduce.  Application code doesn't generally match on the types of IO errors, so it shouldn't be a burden to unbox when necessary.
```
$ chmod u-w ~/.config/dfx/identity.json
$ dfx-r identity use alice
Error: Failed to save identity manager configuration: Failed to write JSON file: Failed to write to /Users/ericswanson/.config/dfx/identity.json: Permission denied (os error 13)
```

refactor: IoError is box wrapper for IoErrorKind

---

src/dfx-core/src/error/identity.rs
src/dfx-core/src/error/structured_file.rs
src/dfx-core/src/json/mod.rs
src/dfx/src/lib/identity/identity_manager.rs
src/dfx/src/lib/identity/mod.rs

The size of the IdentityError type was approaching the default limits for clippy warnings about error types being too large.  This PR boxes some data on the critical "path", reducing the size (as measured on darwin build) from 96 bytes to 56 bytes, which is less than half of the default limit.
Covered by CI

refactor: Box some fields in error types

---

src/dfx/src/commands/canister/call.rs
src/dfx/src/commands/canister/create.rs
src/dfx/src/commands/canister/delete.rs
src/dfx/src/commands/canister/deposit_cycles.rs
src/dfx/src/commands/deploy.rs
src/dfx/src/commands/identity/deploy_wallet.rs
src/dfx/src/commands/identity/get_wallet.rs
src/dfx/src/commands/identity/set_wallet.rs
src/dfx/src/commands/wallet/mod.rs
src/dfx/src/lib/identity/mod.rs
src/dfx/src/lib/identity/wallet.rs
src/dfx/src/lib/operations/canister/create_canister.rs
src/dfx/src/lib/operations/canister/install_canister.rs
src/dfx/src/lib/operations/canister/mod.rs

`get_or_create_wallet()` can generate a `DiagnosedError` in some circumstances.  If we were to move this code to the dfx-core crate, I'm not sure how this would fit with concrete error types.  But we don't need to solve that today, because the code we're going to make available in dfx-core doesn't need to create wallet canisters.
This PR moves `get_or_create_wallet()` and the methods that it depends on to a separate file.
Covered by CI

refactor: move wallet canister creation methods to wallet.rs

---

src/dfx/src/lib/identity/identity_manager.rs
src/dfx/src/lib/identity/mod.rs

Its only caller was `IdentityManager::load()`, so also DRY the whole thing by calling `get_identity_config_or_default()` instead.
This does remove a `debug!()` call.  If it's important, happy to add it to `get_identity_config_or_default()`.
This is part of removing dependencies from the identity crate to DfxResult.
Covered by CI

refactor: remove read_identity_configuration method

---

src/dfx/src/lib/identity/identity_manager.rs
src/dfx/src/lib/identity/mod.rs

Simplify a dependency cycle: it doesn't really make sense to have IdentityManager call a method on Identity, passing itself, only to have that method call right back into IdentityManager.  Instead, pass parameters to Identity::new().
Covered by CI

refactor: Identity::new, no dependency on IdentityManager

---

src/dfx/src/lib/identity/identity_manager.rs

Use `filter_map` to simplify an expression.  This removed the need to add context to an error at all.  In addition, errors were not possible anyway, since they were filtered out.
Covered by CI

refactor: get_identity_names: use filter_map to remove Result type

---

e2e/tests-dfx/generate.bash
scripts/workflows/provision-linux.sh
src/dfx/src/commands/generate.rs
src/dfx/src/lib/environment.rs
src/dfx/src/lib/provider.rs

This changes `dfx generate` to not require the current identity, as it does not use it but does use the rest of the AgentEnvironment machinery. 
Fixes #2872, SDK-916

fix: Use an anonymous agent for `dfx generate`

---

src/dfx-core/src/error/keyring.rs
src/dfx/src/lib/identity/keyring_mock.rs
src/dfx/src/lib/identity/pem_safekeeping.rs

refactor: concrete error types for write_pem_to_keyring

---

src/dfx-core/src/error/identity.rs
src/dfx/src/commands/identity/rename.rs
src/dfx/src/lib/identity/identity_manager.rs
src/dfx/src/lib/identity/pem_safekeeping.rs

Preparation to move to dfx-core crate.
Also moves a dfx-specific error message into the dfx command itself, rather than including it in the error message for the type.
Covered by CI, and tested the rename failure case manually.
```
$dfx-r identity use abc1
Using identity: "abc1".
$ chmod u-w identity.json
$ dfx-r identity rename abc1 abc4
Error: Failed to switch over default identity settings.  Please do this manually by running 'dfx identity use abc4'
```

refactor: concrete error types for identity_manager::rename

---

src/dfx/src/lib/identity/identity_manager.rs
src/dfx/src/lib/identity/mod.rs

`IdentityManager::create_new_identity()` used to call `Identity::create()`, passing `self`, which in turn called right back into IdentityManager to do a bunch of things.
This PR inlines `Identity::create()` into this single caller.  There are no changes to the moved code.
There may be some opportunity/rationale for refactoring parts of this method back into Identity, but that is not done here.
Covered by CI.

refactor: inline Identity::create into IdentityManager::create_new_identity

---

src/dfx-core/src/error/identity.rs
src/dfx-core/src/error/io.rs
src/dfx-core/src/fs/mod.rs
src/dfx/src/commands/identity/import.rs
src/dfx/src/commands/identity/new.rs
src/dfx/src/lib/identity/identity_manager.rs

Change `IdenityManager::create_new_identity()` to use concrete error types, in preparation to move to the dfx-core crate.
Tested by making identity.json read-only just before dfx tries to revert back from the anonymous identity:
```
$ dfx identity new forced --force
$ dfx identity use forced
$ dfx identity new forced --force
$ chmod u-w ~/.config/dfx/identity.json
Error: Failed to switch back over to the identity you're replacing. Please run 'dfx identity use forced' to do it manually.
Caused by: Failed to switch back over to the identity you're replacing. Please run 'dfx identity use forced' to do it manually.
Failed to save identity manager configuration: Failed to write JSON file: Failed to write to ~/.config/dfx/identity.json: Permission denied (os error 13)
```

refactor: IdentityManager::create_new_identity

---

src/dfx/src/commands/canister/create.rs
src/dfx/src/commands/canister/update_settings.rs
src/dfx/src/commands/identity/export.rs
src/dfx/src/commands/identity/list.rs
src/dfx/src/commands/identity/new.rs
src/dfx/src/commands/identity/principal.rs
src/dfx/src/commands/identity/remove.rs
src/dfx/src/commands/identity/rename.rs
src/dfx/src/commands/identity/use.rs
src/dfx/src/commands/identity/whoami.rs
src/dfx/src/lib/environment.rs
src/dfx/src/lib/identity/identity_manager.rs
src/dfx/src/lib/identity/mod.rs
src/dfx/src/lib/migrate.rs

Make it so IdentityManager and Identity no longer depend on Environment, in preparation to move them to the dfx-core create.
See [SDK-918](https://dfinity.atlassian.net/browse/SDK-918)
Covered by CI
[SDK-918]: https://dfinity.atlassian.net/browse/SDK-918?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: Remove dependencies on Environment from IdentityManager/Identity

---

src/dfx/src/commands/canister/mod.rs
src/dfx/src/commands/deploy.rs
src/dfx/src/lib/identity/identity_utils.rs

Remove an unused parameter, and by doing so, a dependency on Environment.

refactor: remove unused reference to Environment

---

src/dfx/src/commands/canister/delete.rs
src/dfx/src/commands/identity/set_wallet.rs
src/dfx/src/commands/quickstart.rs
src/dfx/src/commands/wallet/redeem_faucet_coupon.rs
src/dfx/src/commands/wallet/upgrade.rs
src/dfx/src/lib/identity/mod.rs
src/dfx/src/lib/identity/wallet.rs
src/dfx/src/lib/migrate.rs

These don't need to go to the dfx-core crate right away, or maybe ever.

refactor: move more wallet-related methods to wallet.rs

---

src/dfx/src/lib/identity/identity_manager.rs
src/dfx/src/lib/identity/identity_utils.rs
src/dfx/src/lib/identity/mod.rs
src/dfx/src/lib/identity/pem_utils.rs

Move `validate_pem_file()` to a different file than `call_sender()`, in order to later move it to the dfx-core crate along with the identity manager.

refactor: move validate_pem_file to a separate file

---

e2e/tests-dfx/build_granular.bash
src/dfx-core/src/error/dfx_config.rs
src/dfx-core/src/error/mod.rs
src/dfx/src/config/dfinity.rs
src/dfx/src/lib/operations/canister/install_canister.rs

Also removes dependency from dfinity.rs to BuildError

refactor: concrete error types for get_canister_names_with_dependencies

---

src/dfx-core/src/error/dfx_config.rs
src/dfx/src/config/dfinity.rs

refactor: concrete error types for get_remote_canister_id

---

CHANGELOG.md
src/dfx/Cargo.toml
src/dfx/src/commands/sns/download.rs
src/dfx/src/commands/sns/mod.rs
src/dfx/src/lib/nns/install_nns.rs

Adding a new command to download SNS canister WASMs. This is needed for SNS testflight without installing NNS, i.e., without running `dfx nns install`.

feat: Add dfx sns download

---

src/canisters/frontend/ic-asset/src/asset_canister/batch.rs
src/canisters/frontend/ic-asset/src/asset_canister/protocol.rs
src/canisters/frontend/ic-asset/src/sync.rs
src/canisters/frontend/ic-asset/src/upload.rs

Splits up `ic_asset::sync()` into one part that uploads the batch contents and a second that commits it
Covered by existing e2e

refactor: ic_asset:sync to split upload from commit

---

src/dfx-core/src/error/mod.rs
src/dfx-core/src/error/socket_addr_conversion.rs
src/dfx/src/config/dfinity.rs

refactor: concrete error types for to_socket_addr().

---

src/dfx/src/config/cache.rs
src/dfx/src/lib/error/cache.rs
src/dfx/src/lib/error/extension.rs

removing dependencies on anyhow/DfxResult in preparation to move code to the dfx-core crate
covered by CI

refactor: concrete error types for Cache

---

docs/cli-reference/dfx-nns.md

There is a typo "comiled" instead of "compiled" in the text here: https://internetcomputer.org/docs/current/references/cli-reference/dfx-nns#dfx-nns-install
No tests needed.
- There are no changes in function so I guess this is probably not needed.

docs: Fix typo in text

---

e2e/assets/vulnerable_rust_deps/src/hello/Cargo.toml
e2e/assets/vulnerable_rust_deps/src/hello/src/lib.rs

recent yanking of `cdk-rs` versions has affected our e2e tests https://github.com/dfinity/sdk/actions/runs/4187258199/jobs/7257012722
this fixes the problem
CI

fix(e2e): raise `cdk-rs` version in `e2e/assets/vulnerable_rust_deps/src/hello`

---

CHANGELOG.md
clippy.toml
e2e/tests-dfx/install.bash
src/dfx/src/commands/canister/install.rs
src/dfx/src/commands/deploy.rs
src/dfx/src/lib/operations/canister/deploy_canisters.rs
src/dfx/src/lib/operations/canister/install_canister.rs

Adds the `--no-asset-upgrade` flag, which allows installing assets without upgrading the canister module itself. Implements SDK-974.

feat: Allow bypassing asset canister upgrade

---

CHANGELOG.md

We've already released dfx 0.13.1, so add a new `UNRELEASED` section and move changes made after dfx 0.13.1 to that section.

docs: move post-dfx-0.13.1 changes to a new unreleased section

---

src/dfx-core/src/error/io.rs
src/dfx-core/src/error/network_config.rs
src/dfx-core/src/fs/mod.rs
src/dfx/src/lib/provider.rs

Concrete error types for looking up the webserver port, in preparation to move to dfx-core crate.
Covered by CI

refactor: get_running_webserver_bind_address concrete error types

---

e2e/tests-dfx/pull.bash
src/dfx/src/commands/pull.rs

This PR resolves suggestions by Eric in #2940.
1. log `error` when download fail
2. create tempfile using `new_in`
3. e2e test checks fail reason
4. replace hardcode canister id by `dfx canister id`

fix: follow-up review for #2940

---

CHANGELOG.md
docs/cli-reference/dfx-identity.md
e2e/tests-dfx/identity_command.bash
src/dfx/src/main.rs

`dfx identity use` changes global state.  This means that one script that sets a default identity for its own purposes can interfere with another running concurrently.
This PR proposes a mechanism of scoping a default identity to the current shell.  The identity for a command is:
- as specified by `--identity XXX`, if present, else
- as specified by the environment variable `DFX_IDENTITY=XXX`, if present, else
- as specified by `dfx identity use`
The second of these is scoped to the local shell.
- I have run `DFX_IDENTITY=default cargo run -- identity whoami` and similar commands locally.
- I have included a CI test in this PR.

feat: Get identity from env var if present

---

src/dfx/src/commands/build.rs
src/dfx/src/commands/canister/delete.rs
src/dfx/src/commands/canister/mod.rs
src/dfx/src/commands/deploy.rs
src/dfx/src/commands/diagnose.rs
src/dfx/src/commands/fix.rs
src/dfx/src/commands/generate.rs
src/dfx/src/commands/identity/deploy_wallet.rs
src/dfx/src/commands/identity/get_wallet.rs
src/dfx/src/commands/identity/set_wallet.rs
src/dfx/src/commands/ledger/mod.rs
src/dfx/src/commands/nns/mod.rs
src/dfx/src/commands/pull.rs
src/dfx/src/commands/quickstart.rs
src/dfx/src/commands/remote/generate_binding.rs
src/dfx/src/commands/wallet/mod.rs
src/dfx/src/lib/agent.rs
src/dfx/src/lib/mod.rs
src/dfx/src/lib/provider.rs

Move `create_agent_environment()` and `create_anonymous_agent_environment()` out of provider.rs to a different module, in preparation for moving provider.rs to the dfx-core crate.

refactor: move create_agent_environment to agent module

---

src/dfx-core/src/lib.rs
src/dfx-core/src/util/mod.rs
src/dfx/src/lib/builders/mod.rs
src/dfx/src/lib/canister_info.rs
src/dfx/src/lib/provider.rs
src/dfx/src/util/mod.rs

provider.rs references this method, so move it to the dfx-core crate

refactor: move network_to_pathcompat to dfx-core

---

src/canisters/frontend/ic-asset/src/operations.rs
src/canisters/frontend/ic-asset/src/plumbing.rs
src/canisters/frontend/ic-asset/src/sync.rs
src/canisters/frontend/ic-asset/src/upload.rs

I found `container` to be a bit confusing (as if it would refer to `Containerization`). I believe `canister` will reflect intent better.

style(frontend-canister): rename `container_asset{s}` to `canister_asset{s}`

---

CHANGELOG.md
e2e/tests-dfx/assetscanister.bash
src/canisters/frontend/ic-asset/src/retryable.rs

When updating the permissions system in the asset canister, I overlooked a place where `dfx deploy` and `icx-asset` check for a permissions-related error message.
Added an e2e test that exercises `dfx deploy` with a permissions failure, and updated the retryable logic to account for the new error message as well as the old.
Reviewers can test by:
1. check out the first commit in this PR and `cargo build`
2. `bats -f "dfx deploy does not retry forever on permissions failure" e2e/tests-dfx/assetscanister.bash`
3. notice that the test never finishes
4. check out the final commit and `cargo build`
5. repeat bats command and notice that it completes

fix: make dfx deploy and icx-asset not retry permissions failures

---

src/dfx/assets/welcome.txt

The links for the welcome text were out of date. This PR makes them current.

chore: update welcome links

---

CHANGELOG.md
src/dfx/src/commands/identity/new.rs

Clarifies `dfx identity new` help text
This is a quick fix. Proper documentation and validation will happen in [SDK-1032](https://dfinity.atlassian.net/browse/SDK-1032)
Not at all
[SDK-1032]: https://dfinity.atlassian.net/browse/SDK-1032?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: clarify new identity help text

---

.github/workflows/update-replica-version.yml
CONTRIBUTING.md
scripts/update-ic-ref.sh
scripts/update-motoko.sh
scripts/update-replica.sh
scripts/workflows/provision-darwin.sh

- `End-to-End Tests` no longer appears as if it would be a child of `## Developing ic-certified-assets` (i.e. changed from being header-level-3 to header-level-2)
- simplifies the instructions for setting up e2e tests
- replaces all `CONTRIBUTING.adoc` with `CONTRIBUTING.md`
- moves `CONTRIBUTING.md` from `/.github/CONTRIBUTING.md` to `/CONTRIBUTING.md`
N/A

docs: `CONTRIBUTING.md` improvements and fixes

---

src/canisters/frontend/ic-certified-assets/src/evidence.rs

Simple test which ensures the values of each `TAG_` must stay unique

test(frontend-canister-evidence): ensure `TAG_` value uniqueness

---

CHANGELOG.md
docs/cli-reference/dfx-replica.md
docs/cli-reference/dfx-start.md
e2e/utils/_.bash
src/dfx/src/actors/replica.rs
src/dfx/src/commands/replica.rs
src/dfx/src/commands/start.rs
src/dfx/src/lib/replica_config.rs

Adds back the ability to configure the artificial delay, this time with a directly configurable millisecond count. In addition it sets the delay to 100ms in CI for faster test feedback. Effectively reverts #1859. Implements SDK-894 and closes #3005.

feat: `--artificial-delay`

---

e2e/tests-dfx/mode_reinstall.bash
src/dfx-core/src/cli/mod.rs
src/dfx-core/src/error/cli.rs
src/dfx-core/src/error/mod.rs
src/dfx-core/src/lib.rs
src/dfx/src/lib/operations/canister/install_canister.rs

-------
Moves `ask_for_consent` to `dfx-core`. In preparation for moving `install_canister_wasm` to `dfx-core` crate.
covered by CI

refactor(dfx): move `ask_for_consent` to `dfx-core` + introduce concrete error types

---

src/dfx/src/commands/info/mod.rs

-------
adds missing help text to `dfx info` command and it's subcommands 
CI

docs(dfx-info): add CLI help text

---

src/canisters/frontend/ic-asset/src/batch_upload/plumbing.rs
src/canisters/frontend/ic-asset/src/sync.rs
src/canisters/frontend/ic-asset/src/upload.rs

In order to compute evidence for an asset update proposal, we will need to determine the update operations without actually uploading any content chunks.  This is a small refactor makes this possible, though all current code still uploads the content.
Does not affect any public interfaces.
Covered by existing tests

refactor(ic-asset): add Option to not upload chunks

---

src/canisters/frontend/ic-asset/src/batch_upload/operations.rs
src/canisters/frontend/ic-asset/src/sync.rs
src/canisters/frontend/ic-asset/src/upload.rs

Splits up a method into two parts: one that returns only batch operations for synchronization (which will be needed to compute evidence, and does not need a batch id), another that returns the whole `CommitBatchArguments`.  Doesn't affect pub interface.
Covered by existing tests.

refactor(ic-asset): assemble_commit_batch_arguments

---

e2e/tests-dfx/assetscanister.bash
src/canisters/frontend/ic-asset/src/canister_api/types/batch_upload/v0.rs

The asset synchronization code sorts batch operations before submitting them to an asset canister for later commit by proposal.  This is for deterministic hash ("evidence") computation.
I forgot to reorder the BatchOperationKind to reflect the intended sort order of operations in this case.
See [assemble_batch_operations](https://github.com/dfinity/sdk/blob/master/src/canisters/frontend/ic-asset/src/batch_upload/operations.rs#L24) for the expected order:
1. delete assets
2. create assets
3. unset asset content
4. set asset content
The benefit of this ordering is that we delete/remove obsolete data before creating/adding new data, which could have the effect of making room for the new data.  I don't expect that this comes up very much, though.
The previous order (defined by place in the …

fix: order batch operations to delete/remove data before create/add

---

src/dfx/src/actors/mod.rs
src/dfx/src/commands/replica.rs
src/dfx/src/commands/start.rs

The replica configuration was built mutably in phases.  This made it a little too easy to accidentally use before complete.  This PR makes two changes:
1. Build the replica configuration in one place, resulting in an immutable config.  Both `dfx start` and `dfx replica` do this.
2. DRY the configuration-changed `--clean` enforcement logic, now that the complete replica config is available earlier.
Covered by CI

refactor: immutable replica config and DRY --clean enforcement

---

e2e/tests-dfx/rust.bash

The `"rust canister can have nonstandard target dir location"` test is failing in several PRs.
This copies a fix over from https://github.com/dfinity/sdk/pull/3095
Updates an e2e

test: use valid UTF-8 characters in rust nonstandard target dir test

---

docs/migration/dfx-0.14.0-migration-guide.md

Fixed two small problems in the dfx 0.14.0 migration notes:
1. a quadruple-quote instead of a triple-quote, which desynchronized code and prose later
2. replaced three references to "`CANISTER_ID_prefix`" variables with "`CANISTER_ID_<CANISTER_NAME_UPPERCASE>`", matching the description elsewhere

docs: fix mismatched triple-quote and disambiguate new convention

---

CHANGELOG.md
Cargo.lock
src/canisters/frontend/ic-asset/Cargo.toml
src/canisters/frontend/ic-asset/src/canister_api/types/asset.rs
src/canisters/frontend/ic-asset/src/canister_api/types/batch_upload/common.rs
src/canisters/frontend/ic-asset/src/canister_api/types/batch_upload/v1.rs
src/canisters/frontend/ic-asset/src/sync.rs

Deploys to the portal are failing with dfx 0.14.0, by exceeding the per-message instruction limit.  Two factors are in play:
1. dfx 0.14.0 updates asset properties that have changed.  Since many assets were created by dfx 0.12.1 or earlier and have no properties set at all, that means dfx 0.14.0 is trying to update them all at once.
2. dfx 0.14.0 adds v2 certification, which means more calculations for certification.
This PR implements two changes:
1. Submit all `SetAssetProperties` operations separately, in small groups, before submitting other batch operations.  This seems reasonable because updating an asset's properties should be a safe operation independent of changes to other assets or to an asset's content.
2. Submit batch operations in groups of 500 operations.  This is less …

fix: split up asset synchronization batches in order not to exceed the per-message instruction limit

---

CHANGELOG.md
src/canisters/frontend/ic-asset/src/batch_upload/plumbing.rs
src/canisters/frontend/ic-asset/src/sync.rs
src/canisters/frontend/ic-asset/src/upload.rs

In order to help determine what might be reasonable default limits and to show deployers how close they are to those limits, report (under `-v`) how many chunks were uploaded and the total size of those chunks.
```
[portal] aac5b3a $ dfx-wip -v deploy
...
Count of each Batch Operation Kind: {"SetAssetContent": 5903, "CreateAsset": 3582}
Chunks: 5990  Bytes: 379111924
Canister API version: 1. ic-asset API version: 1
...
```

feat: report chunks and bytes uploaded during deploy

---

CHANGELOG.md
nix/sources.json
src/dfx/assets/dfx-asset-sources.toml

Motoko 0.8.8 is ready for inclusion in dfx.
e2e

chore: update Motoko to 0.8.8

---

src/dfx/src/actors/btc_adapter.rs
src/dfx/src/actors/canister_http_adapter.rs
src/dfx/src/actors/emulator.rs
src/dfx/src/actors/icx_proxy.rs
src/dfx/src/actors/replica.rs

No need for a `mut bool` when we can break directly out of the loop.
Manually by pressing Ctrl-C after `dfx start`

refactor: actor threads: break out of loop

---

CHANGELOG.md
src/dfx/src/actors/replica.rs

This was almost a refactor, but it can change the behavior in a subtle way.
Previously, if the replica never reported healthy, `dfx start` would display a `panic!`, and not display the Dashboard URL, but would otherwise continue.
Now, if the replica doesn't report healthy within one minute of starting, dfx will terminate the replica process and try again.  Ctrl-C can still abort this process (cause dfx to exit).  I don't expect that this will result in a healthy replica, but who knows?
The motivation for this change: I want to add more "initialization" type steps that happen after launching the replica, such as installing the bitcoin canister.  This will consist of calling one or more `async fn`.  This provides a place to do it.
Further context: I have some work-in-progress that reworks …

fix: dfx start will restart replica if it does not report healthy after launch

---

CHANGELOG.md
docs/dfx-json-schema.json
docs/networks-json-schema.json
e2e/tests-dfx/bitcoin.bash
src/dfx-core/src/config/model/dfinity.rs
src/dfx-core/src/network/provider.rs
src/dfx/src/actors/mod.rs
src/dfx/src/actors/replica.rs
src/dfx/src/commands/start.rs
src/dfx/src/lib/integrations/bitcoin.rs
src/dfx/src/lib/integrations/mod.rs
src/dfx/src/lib/integrations/status.rs
src/dfx/src/lib/mod.rs

When bitcoin support is enabled, `dfx start` now deploys the bitcoin canister.
This PR doesn't update the replica version or `remove code from ic-starter that enables the bitcoin feature` as mentioned in the ticket.  However, once merged, it should make both of those tasks possible, for example in  https://github.com/dfinity/sdk/pull/3074 or a similar PR.
Part of https://dfinity.atlassian.net/browse/SDK-1037
Added an e2e test and tested manually with `dfx-wip -v -v start --clean --enable-bitcoin` and `dfx-wip -v -v start --clean --enable-bitcoin --background`.

feat: install bitcoin canister when bitcoin support is enabled

---

CHANGELOG.md
src/dfx/src/actors/replica.rs

With the newest replica which uses a separate bitcoin canister, there is no longer a need to enable the bitcoin_regtest feature.
Fixes https://dfinity.atlassian.net/browse/SDK-1123
Covered by CI

fix: no longer enable the bitcoin_regtest feature

---

CHANGELOG.md
e2e/assets/deps/app/src/main.mo
e2e/assets/deps/onchain/src/b.mo
e2e/assets/deps/onchain/src/c.mo
e2e/tests-dfx/build.bash
e2e/tests-dfx/deps.bash
src/dfx/src/commands/canister/install.rs
src/dfx/src/lib/canister_info.rs
src/dfx/src/lib/models/canister.rs
src/dfx/src/lib/operations/canister/deploy_canisters.rs
src/dfx/src/lib/operations/canister/install_canister.rs

Fixes SDK-1084
The onchain part of the `deps` e2e test

fix: motoko canisters can import other canisters with service constructor

---

.github/workflows/update-replica-version.yml

For some reason, this fixes the workflow which would otherwise crash due to `niv command not found` error 
manually, by running CI on my fork

fix(ci): bump `cachix/install-nix-action` from `v18` to `v21`

---

CHANGELOG.md
e2e/assets/canister_http/main.mo
e2e/assets/canister_http/types.mo
e2e/tests-dfx/canister_http.bash

- Updates the http transform to fix a `FIX ME! opt .. <: .. via special opt rule.` error.
- Disables a canister http test which requires at least an icx-proxy update (see [SDK-1129](https://dfinity.atlassian.net/browse/SDK-1129))
The main motivation is to allow other PRs to pass CI until we can fix the underlying problem.
Ran the disabled e2e test manually to make sure the http transform error no longer happens.
[SDK-1129]: https://dfinity.atlassian.net/browse/SDK-1129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Update http transform and disable test

---

CHANGELOG.md
docs/cli-reference/dfx-bootstrap.md
docs/cli-reference/dfx-replica.md
src/dfx/src/commands/bootstrap.rs
src/dfx/src/commands/replica.rs

Adds deprecation warnings for the `dfx bootstrap` and `dfx replica` commands, linking to https://github.com/dfinity/sdk/discussions/3163 to encourage discussion.
Ran the commands manually.

feat: deprecate bootstrap and replica commands

---

src/dfx/src/commands/extension/run.rs
src/dfx/src/commands/mod.rs
src/dfx/src/lib/extension/manager/execute.rs

Some `dfx` extensions depend on binaries from `dfx`'s cache. Previously, extensions depended on the first `dfx` in `$PATH` to locate its cache, which is error-prone for projects that declare a custom `dfx` version in their `dfx.json`. 
Fixes: https://dfinity.atlassian.net/browse/SDK-1107
Depends on: https://github.com/dfinity/dfx-extensions/pull/21
manually, by installing sns and nns extensions and executing commands which depend on binaries from cache

fix(extensions): ensure dfx extensions locate dfx cache accurately 

---

.github/workflows/e2e.yml
.github/workflows/publish.yml
scripts/workflows/e2e-matrix.py

Currently, `macos-latest` corresponds to `macos-12`.  This PR updates our publish workflow to build using `macos-12` directly, rather than `macos-latest`.
It also updates our e2e workflows to build with `macos-12` to match.
Covered by existing workflows

chore: build/test with macos-12

---

e2e/tests-dfx/usage.bash
src/dfx/src/commands/mod.rs

needed for https://github.com/dfinity/dfx-extensions/pull/17
- enables and hides `dfx extension` cmd
- enables `dfx <EXT>` shorthand notation for running extensions (hidden by default cause its clap' `external_subcommand`) 
manually

chore(extensions): enable `dfx extension` commands

---

docs/cli-reference/dfx-deps.md
docs/cli-reference/index.md
src/dfx/src/commands/deps/deploy.rs
src/dfx/src/commands/deps/mod.rs
src/dfx/src/commands/mod.rs

Fill the missing cli document and unhide `deps` from `dfx --help`.
Fixes SDK-1086

docs: dfx deps in cli-reference

---

src/canisters/frontend/ic-asset/src/asset/config.rs
src/canisters/frontend/ic-asset/src/sync.rs

In preparation for replacing `anyhow` results with concrete error types in ic-asset, remove dependencies on anyhow from tests.
Covered by CI.

test(ic-asset): do not use anyhow in tests

---

CHANGELOG.md

Also removed the note about canister http support being broken.  It's still broken, even as far back as dfx 0.13.1, and worked in 0.13.1, 0.14.0, and 0.14.1 at time of their release.

chore: update changelog with dfx 0.14.2 cutoff

---

CHANGELOG.md
docs/cli-reference/dfx-envars.md
e2e/tests-dfx/identity.bash
src/dfx/src/lib/environment.rs
src/dfx/src/lib/mod.rs
src/dfx/src/lib/warning.rs
src/dfx/src/main.rs

Make it possible to disable this warning:
> The {} identity is not stored securely. Do not use it to control a lot of cycles/ICP. Create a new identity with `dfx identity new` and use it in mainnet-facing commands with the `--identity` flag
Also added a documentation section for the `DFX_WARNING` environment variable to dfx-envvars.md.
Fixes https://dfinity.atlassian.net/browse/SDK-962
Extended an e2e test

feat: add DFX_WARNING mainnet_plaintext_identity

---

CHANGELOG.md
src/dfx/src/lib/operations/canister/install_canister.rs

#2407 neglected the `install_wallet` function, which does not use `install_canister` and thus did not benefit from the module hash waiting. This extracts it to shared logic between the two functions.

fix: Wait for new module hash when installing wallet

---

CHANGELOG.md
nix/sources.json
src/dfx/assets/dfx-asset-sources.toml

Also updated the URL templates for the new build artifact paths.
Fixes https://dfinity.atlassian.net/browse/SDK-1158
Covered by CI

chore: update Motoko to 0.9.5

---

e2e/tests-dfx/extension.bash
src/dfx/src/commands/extension/run.rs

Mitigates the anomaly experienced when executing an extension with hyphenated parameters
```console
❯ dfx nns install --ledger-accounts fefe 
error: unexpected argument '--ledger-accounts' found
tip: to pass '--ledger-accounts' as a value, use '-- --ledger-accounts'
Usage: dfx extension run <NAME|PARAMS>
For more information, try '--help'.
```
(same for `dfx extension run nns install...`)
```console
❯ dfx nns install --ledger-accounts fefe 
Error: No config file found. Please run `dfx config create` first.
Error: Extension exited with non-zero status code '1'.
```
manually

fix(extension): when executing ext, allow params with hyphens

---

e2e/tests-dfx/extension.bash
src/dfx/src/lib/extension/manifest/extension.rs

-------
Adds a configuration flag for `extension.json`: `.subcommands.<CMD>.args.<ARG>.multiple`, which allows passing multiple values for one param, e.g.:
```console
dfx extension install nns
dfx nns install --ledger-accounts fefe efef eeff
```
e2e + unit

fix(extension-run): allow params with multiple values

---

.github/workflows/update-replica-version.yml

Using this to make a dfx 0.14.3 beta that is dfx 0.14.2 + an RC replica
See workflow https://github.com/dfinity/sdk/actions/runs/5545890280/jobs/10125497277 and generated [PR #3237](https://github.com/dfinity/sdk/pull/3237)

feat: allow update-replica-version workflow to update a non-master branch

---

e2e/assets/canister_http/main.mo
e2e/tests-dfx/canister_http.bash

This test started failing last month.  It seems that for some reason, canister http outcalls to smartcontracts.org or internetcomputer.org fail with `Could not find a canister id to forward to.`.  While this is interesting, it's not the purpose of this test.  
Use `www.githubstatus.com` instead: within the context of a CI run, one query here seems ok.
Addresses https://dfinity.atlassian.net/browse/SDK-1129

test: re-enable canister http query test

---

src/dfx/src/commands/ledger/create_canister.rs
src/dfx/src/commands/ledger/notify/create_canister.rs
src/dfx/src/commands/ledger/notify/top_up.rs
src/dfx/src/commands/ledger/top_up.rs
src/dfx/src/commands/quickstart.rs
src/dfx/src/lib/error/mod.rs
src/dfx/src/lib/error/notify_create_canister.rs
src/dfx/src/lib/error/notify_top_up.rs
src/dfx/src/lib/operations/cmc.rs

Both `notify_create()` and `notify_top_up()` return `Result<Result<T, NotifyError>, DfxError>`.  This PR flattens each result into a single `Result<T, Concrete Error Type>` for the method.
This avoids in-effect matching for things like `Ok(Ok(principal))` or `Ok(Err(Refunded))`.
Covered by CI

refactor: flatten notify_create, notify_top_up error types

---

CHANGELOG.md

Since dfx 0.15.0-beta.2 incorporates this replica update, moved the changelog entry to reflect that.

chore: move replica update to 0.15.0 section

---

.github/workflows/conventional-commits.yml

In an expression like `"${{ github.event.pull_request.title }}"` in an inline script, nothing escapes quotes, backticks, `$()`, and so forth.
In practice, this means a title like `fix(frontend-canister): Revert "fix(frontend-canister): ..."` would break this workflow at the first single-quote in the title.
Followed the advice here to remedy: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
Fixes https://dfinity.atlassian.net/browse/SDK-1002
Tested some problematic titles; you can see them in the PR history

fix(conventional-commits-workflow): harden against shell injection

---

CHANGELOG.md
docs/cli-reference/dfx-deploy.md
e2e/tests-dfx/fabricate_cycles.bash
e2e/tests-dfx/network.bash
src/dfx/src/lib/network/network_opt.rs

Accept `--ic` in place of `--network ic`
> For most of dfx commands I type --network=ic. Can we create a shorthand to reduce the number of letters and make the command easier to read?
Fixes https://dfinity.atlassian.net/browse/SDK-439

feat: added --ic as shorthand for --network ic

---

src/dfx-core/src/extension/manager/install.rs

-------
Currently dfx (extension command) will execute a binary that is writable by any other user on the system, which is bad from security standpoint. This PR changes the permissions, such that the extension binary is executable and readable only by the owner.
Fixes https://dfinity.atlassian.net/browse/SDK-1199
covered by e2e

fix(extension): change permission mode from 0777 to 0500

---

CHANGELOG.md
src/dfx/assets/new_project_node_files/package.json

Our starter app issued a warning for node 20 erroneously. This updates that.

fix: node engines in starter app

---

CHANGELOG.md
e2e/tests-dfx/start.bash
src/dfx-core/src/network/provider.rs

If you run `dfx start` from a dfx project directory,
and dfx.json does not define a `local` network
then `dfx start` will start the shared network.
If dfx.json defines `bitcoin`, `replica`, or `canister_http` settings in `defaults`,
`dfx start` will ignore them,
because the shared network by definition doesn't use any project settings.
In case it's surprising that `dfx start` ignores project settings in dfx.json when starting the shared network,
`dfx start` now warns about any such ignored project settings.
Fixes https://dfinity.atlassian.net/browse/SDK-1001
Added an e2e test and tested manually.
Example output:
```
$ dfx-wip start
Running dfx start for version 0.15.0-beta.1+rev20.dirty-b335dd995
Using shared network 'local' defined in /Users/ericswanson/.config/dfx/networks.json
WARN: …
```

feat: dfx start for shared network warns if ignoring defaults in dfx.json

---

src/dfx-core/src/fs/mod.rs
src/dfx/src/commands/deps/pull.rs
src/dfx/src/lib/builders/assets.rs
src/dfx/src/lib/builders/custom.rs
src/dfx/src/lib/builders/mod.rs
src/dfx/src/lib/builders/motoko.rs
src/dfx/src/lib/models/canister.rs

Rename set_perms_readwrite to set_permissions_readwrite, move it to dfx_core crate, and use it in places after we copy files.
This is because the source file may not be writable (e.g., installed from system package, or by another user), and we want to make sure the destination file is writable to prevent future writing failures.

chore: Clean up use of set_permissions_readwrite

---

src/dfx-core/src/error/identity/convert_mnemonic_to_key.rs
src/dfx-core/src/error/identity/create_new_identity.rs
src/dfx-core/src/error/identity/generate_key.rs
src/dfx-core/src/error/identity/initialize_identity_manager.rs
src/dfx-core/src/error/identity/mod.rs
src/dfx-core/src/error/identity/rename_identity.rs
src/dfx-core/src/error/identity/save_pem.rs
src/dfx-core/src/error/identity/write_pem_to_file.rs
src/dfx-core/src/identity/identity_manager.rs
src/dfx-core/src/identity/pem_safekeeping.rs

- GenerateKeyError
- ConvertMnemonicToKeyError
- SavePemError
- WritePemToFileError
Covered by CI

refactor: method-specific errors for generating keys and saving pem files

---

scripts/workflows/e2e-matrix.py
src/dfx-core/src/extension/manager/install.rs

https://github.com/dfinity/dfx-extensions/pull/48 changed how the filename of tarball and the name of the dir directly inside it; they no longer contain the version of the extension (meaning, we're going from `{package}-v{version}-{platform}.{ext}` to `{package}-{platform}.{ext}`)
Awaits merging of https://github.com/dfinity/dfx-extensions/pull/51 and https://github.com/dfinity/dfx-extensions/pull/50
covered by CI

fix(extension): update tarball filename format

---

CHANGELOG.md
e2e/tests-dfx/deploy.bash
src/dfx/src/commands/deploy.rs

Currently, we're not printing frontend urls for most asset canisters, and it's inconvenient. Given a dfx config with no "frontend" block such as 
```json
"hello_frontend": {
"dependencies": [
"hello_backend"
],
"source": [
"src/hello_frontend/assets",
"dist/hello_frontend/"
],
"type": "assets"
}
```
we get
After this change, we get 
Tested manually on a dfx new starter

fix: dfx deploy urls printed for asset canisters

---

scripts/workflows/e2e-matrix.py

partially reverts #3307 
ref: https://github.com/dfinity/sdk/pull/3307#issuecomment-1697681904
covered by CI

fix: revert e2e runner from ubuntu-22.04 back to -20.04

---

e2e/tests-dfx/id.bash
src/dfx/src/commands/canister/id.rs
src/dfx/src/commands/canister/mod.rs

`dfx canister id` doesn't use the identity, but displays a warning if the selected identity is stored in plaintext.  
Motivation: to make it easier for a new feature, 'dfx canister url', to also not display this warning.
Added an e2e test.  There are two commits in this PR: the first adds the test, in case you want to see it fail without the code update.
before
```
$ dfx canister id frontend --ic
WARN: The default identity is not stored securely. Do not use it to control a lot of cycles/ICP. Create a new identity with `dfx identity new` and use it in mainnet-facing commands with the `--identity` flag
bd3sg-teaaa-aaaaa-qaaba-cai
```
after
```
$ dfx canister id frontend --ic
bd3sg-teaaa-aaaaa-qaaba-cai
```

fix: dfx canister id no longer warns about plaintext passwords on mainnet

---

Cargo.lock

See failures here: https://github.com/dfinity/sdk/actions/runs/6052522361/job/16426172760?pr=3344
Covered by CI

chore: update webpki and rustls-webpki for cargo audit failures

---

Cargo.lock
Cargo.toml
src/dfx-core/src/identity/mod.rs

This commit bumps `ic-utils`, `ic-agent` and `ic-identity-hsm` from version 0.26.1 to version 0.27.0.
In OpenChat we have just started using dfx-core to load DFX identities and when using the version from this commit everything works as expected.

chore: bump `ic-utils`, `ic-agent` and `ic-identity-hsm` to 0.27.0

---

e2e/tests-dfx/bitcoin.bash
e2e/tests-dfx/canister_http.bash
e2e/tests-dfx/dfx_install.bash
e2e/tests-dfx/leak.bash
e2e/tests-dfx/ledger.bash
e2e/tests-dfx/new.bash
e2e/tests-dfx/signals.bash
scripts/workflows/e2e-matrix.py

There's no need to specify exclusions for the ic-ref for certain tests, since we aren't running any tests vs ic-ref anymore.
Covered by CI

test: remove references to ic-ref from e2e

---

CHANGELOG.md
docs/cli-reference/dfx-start.md
src/dfx-core/src/network/provider.rs

When running `dfx start` with a project-specific network (dfx.json contains a `local` network definition), dfx displays the following warning:
```
WARN: Project-specific networks are deprecated and will be removed after February 2023.
```
It's mid-September, which is not a good look, but also we shouldn't remove project-specific networks until we can support multiple subnet types at the same time.
Ran `dfx start` in a directory where dfx.json defined a local network.

fix: remove project specific network deprecation warning

---

src/dfx-core/src/error/identity/create_new_identity.rs
src/dfx-core/src/error/identity/mod.rs
src/dfx-core/src/error/identity/remove_identity.rs
src/dfx-core/src/identity/identity_manager.rs

Move error causes for remove_identity from IdentityError to RemoveIdentityError
Covered by CI

refactor: RemoveIdentityError

---

src/dfx-core/src/error/identity/create_new_identity.rs
src/dfx-core/src/error/identity/export_identity.rs
src/dfx-core/src/error/identity/get_identity_config_or_default.rs
src/dfx-core/src/error/identity/instantiate_identity_from_name.rs
src/dfx-core/src/error/identity/load_identity.rs
src/dfx-core/src/error/identity/load_pem.rs
src/dfx-core/src/error/identity/load_pem_from_file.rs
src/dfx-core/src/error/identity/load_pem_identity.rs
src/dfx-core/src/error/identity/mod.rs
src/dfx-core/src/error/identity/new_hardware_identity.rs
src/dfx-core/src/error/identity/new_identity.rs
src/dfx-core/src/error/identity/rename_identity.rs
src/dfx-core/src/identity/identity_manager.rs
src/dfx-core/src/identity/mod.rs
src/dfx-core/src/identity/pem_safekeeping.rs
src/dfx/src/commands/canister/create.rs
src/dfx/src/commands/canister/update_settings.rs

Adds concrete error type `NewIdentityError` for `Identity::new()`, and require dependent error types.
Covered by CI

refactor: concrete error type for Identity::new

---

src/dfx-core/src/error/identity/call_sender_from_wallet.rs
src/dfx-core/src/error/identity/create_new_identity.rs
src/dfx-core/src/error/identity/export_identity.rs
src/dfx-core/src/error/identity/instantiate_identity_from_name.rs
src/dfx-core/src/error/identity/mod.rs
src/dfx-core/src/error/identity/new_identity_manager.rs
src/dfx-core/src/error/identity/remove_identity.rs
src/dfx-core/src/error/identity/rename_identity.rs
src/dfx-core/src/error/identity/require_identity_exists.rs
src/dfx-core/src/error/identity/use_identity_by_name.rs
src/dfx-core/src/error/identity/write_default_identity.rs
src/dfx-core/src/identity/identity_manager.rs
src/dfx-core/src/identity/mod.rs
src/dfx/src/lib/error/mod.rs

Move the remaining enumerated types in IdentityError to method-specific error types, and remove IdentityError.
New types:
- CallSenderFromWalletError
- RequireIdentityExistsError
- UseIdentityByNameError
- WriteDefaultIdentityError
Covered by CI

refactor: move remaining IdentityError types to method-specific errors

---

src/dfx-core/src/config/model/dfinity.rs
src/dfx-core/src/error/canister_id_store.rs
src/dfx-core/src/error/dfx_config.rs

Eliminates some boxing and makes it more clear what errors are possible for any given method.
Covered by CI

refactor: split up DfxConfigError into method-specific error types

---

src/dfx-core/src/config/directories.rs
src/dfx-core/src/config/model/dfinity.rs
src/dfx-core/src/identity/identity_manager.rs
src/dfx-core/src/identity/mod.rs
src/dfx/src/lib/identity/wallet.rs

This method is about  `$HOME/.config/dfx/` (on linux/osx.  It will be different on Windows)
Meaning: "get the .config/dfx directory path" -> "get the user's dfx config directory",
Motivation for the change: about to add an error type for this method
Covered by CI

refactor: rename get_config_dfx_dir_path() -> get_user_dfx_config_dir()

---

e2e/tests-dfx/playground.bash

mops 0.27.2 logs extra information to stdout, alongside the expected `--package <path>` output.  This causes our calls to `moc` to fail, and blocks any PR from passing CI.
This PR pins mops to 0.27.1 pending a fix.  Once a reversion of this PR passes CI, that reversion can be merged.
See https://github.com/dfinity/sdk/pull/3394 for a demonstration.

test: pin mops to version that only writes package parameters to stdout

---

e2e/tests-dfx/playground.bash

This reverts commit d2404ec7c60fa9a37cc70eb489a14509e8eee992 now that the extra output has been removed.
CI wouldn't pass without the fix to mops

test: revert: pin mops to version that only writes package parameters to stdout

---

CHANGELOG.md
e2e/tests-dfx/extension.bash
e2e/tests-dfx/ledger.bash
src/dfx-core/src/extension/manager/install.rs
src/dfx/src/commands/extension/install.rs

In order to not break CI every time we release a new dfx version, make it so we can install a specific version of an extension rather than relying on the compatibility matrix.
There is no document for `dfx extension` in docs/cli-reference, so I did not update it.
Updated CI to use this, and tested locally.

feat: install specific extension version

---

src/dfx-core/src/network/provider.rs

Remove two unused imports reported by clippy

refactor: remove unused imports

---

src/dfx/src/commands/canister/call.rs
src/dfx/src/commands/canister/delete.rs
src/dfx/src/commands/canister/info.rs
src/dfx/src/commands/canister/metadata.rs
src/dfx/src/commands/canister/request_status.rs
src/dfx/src/commands/canister/sign.rs
src/dfx/src/commands/deps/deploy.rs
src/dfx/src/commands/deps/pull.rs
src/dfx/src/commands/identity/set_wallet.rs
src/dfx/src/commands/ledger/balance.rs
src/dfx/src/commands/ledger/create_canister.rs
src/dfx/src/commands/ledger/notify/create_canister.rs
src/dfx/src/commands/ledger/notify/top_up.rs
src/dfx/src/commands/ledger/show_subnet_types.rs
src/dfx/src/commands/ledger/top_up.rs
src/dfx/src/commands/ledger/transfer.rs
src/dfx/src/commands/quickstart.rs
src/dfx/src/commands/wallet/redeem_faucet_coupon.rs
src/dfx/src/commands/wallet/upgrade.rs
src/dfx/src/lib/environment.rs
src/dfx/src/lib/identity/wallet.rs
src/dfx/src/lib/migrate.rs
src/dfx/src/lib/named_canister.rs
src/dfx/src/lib/operations/canister/create_canister.rs
src/dfx/src/lib/operations/canister/deploy_canisters.rs
src/dfx/src/lib/operations/canister/install_canister.rs
src/dfx/src/lib/operations/canister/mod.rs
src/dfx/src/lib/operations/canister/motoko_playground.rs
src/dfx/src/lib/root_key.rs

The Environment on the call stack is either an AgentEnvironment, or it isn't.  All of these `.ok_or_else`/`.expect` checks either always fail, or never fail.  They never fail.  They're all unreachable.
This PR changes `Environment::get_agent()` to return an `&Agent` rather than an `Option<&Agent>`, and removes all of the unreachable error checking.
Covered by CI

refactor: Environment.get_agent() returns an agent or panics

---

src/canisters/frontend/ic-asset/src/canister_api/methods/api_version.rs
src/canisters/frontend/ic-asset/src/canister_api/methods/asset_properties.rs
src/canisters/frontend/ic-asset/src/canister_api/methods/batch.rs
src/canisters/frontend/ic-asset/src/canister_api/methods/chunk.rs
src/canisters/frontend/ic-asset/src/canister_api/methods/list.rs
src/canisters/frontend/icx-asset/src/commands/list.rs
src/dfx/src/commands/canister/call.rs
src/dfx/src/commands/wallet/mod.rs
src/dfx/src/lib/operations/canister/mod.rs
src/dfx/src/lib/operations/ledger.rs

Use `Canister.update()` and `Canister.query()` rather than `Canister.update_()` and `Canister.query_()`.
Existing tests

refactor: use query/update rather than query_/update_

---

e2e/assets/cycles-ledger/dfx.json
e2e/tests-dfx/cycles-ledger.bash
e2e/utils/cycles-ledger.bash

Adds an e2e test for the cycles ledger, using `dfx canister call`.  Followup PRs that add new `dfx cycles` subcommands will replace some of those `dfx canister call` commands with those new commands, as well as add new tests that focus on those subcommands.
Since the cycles-ledger repo is not yet public, this PR downloads its build artifacts from a temporary branch in this repo: https://github.com/dfinity/sdk/tree/cycles-ledger-prerelease
Fixes https://dfinity.atlassian.net/browse/SDK-1170

test: e2e test for cycles ledger

---

CHANGELOG.md
Cargo.lock
Cargo.toml
docs/cli-reference/dfx-cycles.md
docs/cli-reference/index.md
e2e/tests-dfx/cycles-ledger.bash
src/dfx/Cargo.toml
src/dfx/src/commands/cycles/balance.rs
src/dfx/src/commands/cycles/mod.rs
src/dfx/src/commands/mod.rs
src/dfx/src/lib/mod.rs
src/dfx/src/lib/operations/cycles_ledger.rs
src/dfx/src/lib/operations/mod.rs
src/dfx/src/lib/retryable.rs

Adds the `dfx cycles balance` subcommand, hidden for the time being.
Fixes https://dfinity.atlassian.net/browse/SDK-1160
Added an e2e test and updated another to use `dfx cycles balance` rather than `dfx canister call`.

feat: add cycles balance command

---

CHANGELOG.md
docs/cli-reference/dfx-cycles.md
e2e/tests-dfx/cycles-ledger.bash
src/dfx/src/commands/cycles/mod.rs
src/dfx/src/commands/cycles/transfer.rs
src/dfx/src/lib/operations/cycles_ledger.rs

Adds `dfx cycles transfer --to-owner <principal>` to transfer from one account to another account.  Transfer from account to canister will follow.
Fixes https://dfinity.atlassian.net/browse/SDK-1162
Updated an e2e test and added an e2e test.

feat: SDK-1162 dfx cycles transfer (to account)

---

e2e/tests-dfx/cycles-ledger.bash

All the other e2e test scripts use 2-space indents.  I created this script before making them all consistent.

test: reformat cycles-ledger.bash to match rest

---

CHANGELOG.md
docs/cli-reference/dfx-canister.md
e2e/tests-dfx/install.bash
src/dfx/src/commands/canister/install.rs

This PR adds support for providing install arguments from a file.
This is motivated by these issues:
* It is impossible to pass a large canister init arg as the length of shell arguments is limited by the terminal (which in turn may be limited by the operating system).
* For shorter arguments, it is more convenient to write `--argument-file somefile.hex` than `--argument "$(cat somefile.hex)"`.
* The `dfx canister call` method supports `--argument-file` for similar reasons.  It would be nice to be consistent.
e2e tests are included in the PR.

feat: Read install arg from file

---

CHANGELOG.md
e2e/tests-dfx/dotenv.bash
src/dfx-core/src/config/model/dfinity.rs
src/dfx-core/src/error/config.rs
src/dfx/src/commands/build.rs
src/dfx/src/commands/canister/install.rs
src/dfx/src/commands/deploy.rs
src/dfx/src/lib/builders/mod.rs

dfx.json can specify `output_env_file` (the default for new projects is `".env"`), and some commands accept `--output-env-file .env` on the command line.
If `dfx deploy`, `dfx build`, or `dfx canister install` were executed in a subdirectory of a project, they would create/read this file in that subdirectory, rather than the same directory as dfx.json (the project root).
With this change, the location of the env file is taken to be relative to the project root, and furthermore must be contained within the project directory.
Also fixed three places that could output "No such file or directory (OS error 2)" without telling which path wasn't found.
Fixes: https://dfinity.atlassian.net/browse/SDK-1028
Added e2e tests.

fix: output .env file is now relative to project root, not cwd

---

CHANGELOG.md
e2e/tests-dfx/extension.bash
src/dfx/src/commands/extension/install.rs

Running `dfx extension install <extension>` immediately after installing a new dfx version, or after `dfx cache delete`, would result in a cache directory that contained only an `extensions` subdirectory.
Later, dfx would see that the cache directory exists and therefore not install it.  Then, commands like `dfx start` or `dfx build` would fail due to missing files.
Fixes: https://dfinity.atlassian.net/browse/SDK-1240

fix: dfx extension install will no longer create a corrupt cache directory

---

.github/workflows/bitcoin-canister-update.yml

This PR introduces a new github workflow to update sources for bitcoin canister:
- runs periodically (daily, at midnight UTC)
- checks to see if the release tag associated with the latest tag no longer matches the release tag that dfx uses for the bitcoin canister
- If the latest tag has changed, opens a PR to update the release tag that dfx uses to match.
Closes https://dfinity.atlassian.net/browse/SDK-1039
https://github.com/smallstepman/sdk/pull/64

ci: add bitcoin workflow

---

CHANGELOG.md
e2e/tests-dfx/delete.bash
src/dfx-core/src/config/model/canister_id_store.rs
src/dfx/src/commands/canister/delete.rs

`dfx canister delete <by id>` would leave entries (canister name -> canister id) in the canister id store.  A subsequent `dfx deploy` would then fail because it would try to install to the deleted canister rather than creating a new one.
Fixes https://dfinity.atlassian.net/browse/SDK-1143

fix: deleting project canister by id will clean up canister id store.

---

.github/workflows/e2e.yml
Cargo.lock
Cargo.toml
e2e/tests-dfx/certificate.bash
src/canisters/frontend/ic-asset/src/lib.rs
src/canisters/frontend/icx-asset/src/main.rs
src/dfx-core/src/util/mod.rs
src/dfx/Cargo.toml
src/dfx/src/commands/canister/deposit_cycles.rs
src/dfx/src/commands/canister/send.rs
src/dfx/src/commands/cycles/balance.rs
src/dfx/src/commands/ledger/balance.rs
src/dfx/src/commands/ledger/mod.rs
src/dfx/src/lib/environment.rs
src/dfx/src/lib/replica/status.rs
src/dfx/src/lib/sign/sign_transport.rs
src/dfx/src/util/currency_conversion.rs

This updates to ic-agent 0.30.1, notably *not* including the large wasms feature.

chore: Update to new ic-agent version

---

.github/workflows/e2e.yml

We don't need to run any CI vs the ic-ref anymore.
See https://dfinity.atlassian.net/browse/SDK-1321 for followup to remove the --emulator mode itself

test: no longer run smoke matrix with --emulator

---

e2e/utils/cycles-ledger.bash

Now that the cycles ledger repo is open-sourced we can use it as the place to download the cycles ledger wasm
Covered by existing e2e

chore: change to permanent cycles ledger url

---

.github/workflows/publish-dfxvm-install-script.yml

Background: On any merge to master, the [publish-manifest workflow](https://github.com/dfinity/sdk/blob/master/.github/workflows/publish-manifest.yml) updates the install script and manifest.json on the [public-manifest branch](https://github.com/dfinity/sdk/tree/public-manifest).  That branch contains only those two files.  These are ultimately the files accessed by `sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)"`.
This PR introduces a new workflow and the following two branches:
- [dfxvm-install-script](https://github.com/dfinity/sdk/tree/dfxvm-install-script), which contains only install.sh
- [sdk-1278-dfxvm-install-script](https://github.com/dfinity/sdk/tree/sdk-1278-dfxvm-install-script), a feature branch to hold the changes to install.sh that will make it install …

feat: publish dfxvm install script from feature branch

---

CHANGELOG.md
public/install/200_downloader.sh

curl 7.73 (Released Oct 13 2020, see https://github.com/curl/curl/commit/aa8777f63febca6a13f6b86e141a832232560037) changed the output of `curl --help` to display categories, rather than all of the options, unless you pass `--help all`.  Our install script only called `curl --help`, so it stopped detecting that the `--proto` and `--tlsv1.2` options are available, and called curl in a less secure mode.
This PR calls `<cmd> --help all` instead of `<cmd> --help` when checking command help.  The install script calls this for `curl` and for `wget`.
`wget --help all` works in the latest wget that I tried, and I built wget 1.5.3 (circa 2015) which also worked.
Also checked "curl --help all" with curl 7.54.0.  It shows the same output as "curl --help" and returns exit code 0.
See above, and: …

fix: enable tlsv1.2 if curl supports it

---

public/install/200_downloader.sh
public/install/999_footer.sh

Alters the install script to install dfxvm, rather than dfx.
Note the base branch for the PR is not master.  A PR from the base branch will be submitted once we are ready to release dfxvm.
The script is a lot simpler, in part because it always downloads the latest version.  Even so, I restructured it a bit:
- make sure the temporary directory is always cleaned up
- handle errors in subshells properly
- never try to download an aarch64-unknown-linux-gnu build, which wouldn't exist
Also updates the downloader to pass `--progress-bar` to curl, which is much more streamlined.  The `--progress-bar` parameter was added in curl 5.10 in 1999.
Fixes https://dfinity.atlassian.net/browse/SDK-1278
`bash ./install.sh` , with or without DFX_VERSION, run from the public/ directory.

feat: installer downloads and executes dfxvm

---

public/install/999_footer.sh

Fixes shellcheck warnings seen here: https://github.com/dfinity/sdk/actions/runs/7108009431/job/19350497746
Ran the script and shellcheck locally.

fix: shellcheck warnings in install script

---

.github/workflows/publish-dfxvm-install-script.yml
.github/workflows/publish-manifest.yml

Runs the shellcheck workflow for the install script on PRs as well as merge to master, skipping the upload step for PRs.
For the publish-manifest workflow, sets the name to `install-script-shellcheck:required` for later inclusion as a required status.
Does not do this for the dfxvm-install-script-shellcheck, since we'd only remove it again soon, but it will still be reported as a status.
Here are the two workflow runs for this PR, which as expected, generated the script (running shellcheck in the process) but did not upload it:
- [install-script-shellcheck:required](https://github.com/dfinity/sdk/actions/runs/7108474788/job/19351821415?pr=3469)
- [dfxvm-install-script-shellcheck](https://github.com/dfinity/sdk/actions/runs/7108474790/job/19351821304?pr=3469)

fix: on PRs, run shellcheck for install scripts

---

CHANGELOG.md
docs/cli-reference/dfx-start.md
docs/dfx-json-schema.json
docs/networks-json-schema.json
e2e/tests-dfx/start.bash
src/dfx-core/src/config/model/dfinity.rs
src/dfx-core/src/config/model/local_server_descriptor.rs
src/dfx-core/src/json/structure.rs
src/dfx-core/src/network/provider.rs
src/dfx/src/actors/icx_proxy.rs
src/dfx/src/commands/start.rs

Add dfx.json, networks.json, and `dfx start` support for the icx-proxy `--domain` parameter.
Fixes https://dfinity.atlassian.net/browse/SDK-1327
Added e2e tests and ran locally.  The tests check that the parameter goes through, but don't check the functionality.

feat: domain configuration for icx-proxy

---

docs/process/release.adoc

This PR deletes the "MANUAL STEPS" release process description.  It's inaccurate and we have not used it in at least two years.
The only other change is to move the part about whitelisting the frontend canister with the Motoko playground.  There were actually two places that described this, both found in the "MANUAL STEPS" section.

docs: remove description of manual steps from release doc

---

CHANGELOG.md
src/dfx/assets/new_project_node_files/src/__project_name___frontend/assets/.ic-assets.json5
src/dfx/assets/new_project_node_files/src/__project_name___frontend/src/.ic-assets.json5

This MR adds `http://localhost:*` as `connect-src` into the asset canister's CSP. This will enable browsing the asset canister at `http://<canister-id>.localhost:<port>` in most browsers.

fix: add localhost to asset canister's CSP

---

src/dfx/src/commands/canister/delete.rs
src/dfx/src/commands/wallet/redeem_faucet_coupon.rs
src/dfx/src/lib/ledger_types/mod.rs

Changes `DEFAULT_FAUCET_PRINCIPAL` from `const &str` to `const Principal` for type safety and for consistency with other principal constants (see `MAINNET_BITCOIN_CANISTER_ID`, `MAINNET_LEDGER_CANISTER_ID`, among others).
Also removed the `allow_deprecated` flag since `Principal::from_slice` is no longer deprecated (to allow for this specific use case).
Added a test

refactor: use const Principal for default faucet principal

---

.github/workflows/e2e.yml

See https://github.com/dfinity/sdk/actions/runs/7265443777/job/19796376801 for an example where the UI test failed but the `e2e:required` status passed anyway and the PR was merged.
This PR will test it

test: require UI test to pass for CI

---

CHANGELOG.md

Includes everything up to #3485.

chore: Add the 0.15.3 header to the changelog

---

CHANGELOG.md
docs/cli-reference/dfx-cycles.md
e2e/tests-dfx/cycles-ledger.bash
src/dfx/src/commands/cycles/balance.rs
src/dfx/src/commands/cycles/top_up.rs
src/dfx/src/commands/cycles/transfer.rs
src/dfx/src/lib/operations/cycles_ledger.rs

[The canister ID for `cycles-ledger` became known](https://forum.dfinity.org/t/improving-the-cycle-management-experience/19895/10), therefore, it is no longer required to pass it as an CLI argument.  
covered by CI

feat!: update `dfx cycles` commands with maninet `cycles-ledger` canister ID

---

docs/cli-reference/dfx-ledger.md

Fix the sample for `dfx ledger fabricate-cycles`.

docs: Update dfx-ledger.md

---

CHANGELOG.md
src/dfx-core/src/config/model/canister_id_store.rs
src/dfx/src/lib/operations/canister/motoko_playground.rs

The playground backend returns acquisition timestamps with nanosecond precision, and uses nanosecond precision when looking up reserved canisters.
SystemDateTime has OS-specific precision.  On Linux and OSX this is nanosecond precision, but on Windows it's 100ns precision.  OffsetDateTime has nanosecond precision on all platforms.
The result was `dfx deploy --playground` on Windows would return a "Canister not found" error from the playground backend.
Part of https://dfinity.atlassian.net/browse/SDK-1343
Covered by CI, and tested locally on OSX and Windows.

fix: nanosecond precision for playground canister acquisition timestamps

---

Cargo.lock
src/canisters/frontend/ic-asset/src/sync.rs
src/dfx-core/Cargo.toml
src/dfx-core/src/fs/mod.rs
src/dfx/src/lib/builders/mod.rs
src/dfx/src/lib/canister_info/assets.rs
src/dfx/src/lib/operations/canister/install_canister.rs

Call `dunce::canonicalize` rather than `Path::canonicalize`.  On Linux/Macos, this just calls `std::fs::canonicalize()`, so no change there.
PathBuf::canonicalize on Windows generally returns Windows NT UNC paths like `\\?\C:\Users\you\`.  Lots of programs, including Microsoft's, don't work with these kinds of paths. For example, `npm` will print out a message something like `The current working directory is a UNC path.  I'm going to use C:\Windows instead.`. 
dunce:
> ... converts paths to legacy format whenever possible, but leaves UNC paths as-is when they can’t be unambiguously expressed in a simpler way. This allows legacy programs to access all paths they can possibly access, and UNC-aware programs to access all paths.
https://github.com/rust-lang/rust/issues/42869#issuecomment-17123 …

fix: Use dunce crate to get non-UNC paths when calling canonicalize

---

src/dfx/src/commands/new.rs
src/dfx/src/lib/builders/assets.rs
src/dfx/src/lib/mod.rs
src/dfx/src/lib/program.rs

On Windows, calls to `npm` and `node` fail.  They need to be `npm.cmd` and `node.exe` respectively.
Tested locally

fix: call npm.cmd and node.exe on Windows

---

.github/workflows/e2e.yml
e2e/tests-dfx/schema.bash
e2e/utils/_.bash

In e2e test suite, `set -o pipefail` in order to detect errors anywhere in a command pipeline.
This turned up one test with such an issue

test: detect errors in command pipelines

---

CHANGELOG.md
src/dfx/src/commands/canister/delete.rs

A HardwareIdentity holds a session open to the HSM.  This means an attempt to create a second HardwareIdentity to the same HSM will fail.  `dfx canister delete` tried to do this, though it didn't need to.
Fixes https://dfinity.atlassian.net/browse/SDK-1346
```
$ dfx canister delete del_backend
Error: Failed to delete canister 'del_backend'.
Caused by: Failed to delete canister 'del_backend'.
Failed to create AgentEnvironment.
Failed to create AgentEnvironment for network 'local'.
Failed to load identity: Failed to instantiate identity: Failed to instantiate hardware identity: Failed to instantiate hardware identity for identity 'hhssmm': PKCS#11: CKR_CRYPTOKI_ALREADY_INITIALIZED (0x191).
$ dfx-wip canister delete del_backend
Beginning withdrawal of cycles; on failure try --no-wallet …
```

fix: for canister delete with HSM trying to open two sessions

---

docs/cli-reference/dfx-identity.md

`dfx identity export` and `dfx identity import` exist, but export wasn't documented.
Fixes https://dfinity.atlassian.net/browse/SDK-601

docs: add documentation for dfx identity export

---

src/dfx/src/commands/new.rs
src/dfx/src/lib/info/mod.rs

We don't need to use `lazy_static` where const functions are available.
Fixes https://dfinity.atlassian.net/browse/SDK-761
Covered by CI

refactor: remove lazy_static where const functions are available

---

CHANGELOG.md
e2e/tests-dfx/start.bash
e2e/tests-dfx/wallet.bash
src/dfx/src/commands/canister/deposit_cycles.rs
src/dfx/src/commands/canister/start.rs
src/dfx/src/commands/canister/stop.rs
src/dfx/src/commands/canister/uninstall_code.rs

Make it so the following `dfx canister` commands work outside of a project, when specifying a single canister by id:
- `dfx canister stop <canister id>`
- `dfx canister stop <specific canister id>`
- `dfx canister deposit-cycles <amount> <specific canister id>`
- `dfx canister uninstall-code <specific canister id>`
Fixes https://dfinity.atlassian.net/browse/SDK-871
Added tests

fix: allow some canister commands outside of a project

---

.github/workflows/broadcast-frontend-hash.yml
.github/workflows/build-frontend-canister.yml
.github/workflows/consistent-sources.yml
.github/workflows/deny.yml
.github/workflows/e2e.yml
.github/workflows/fmt.yml
.github/workflows/lint.yml
.github/workflows/prepare-dfx-assets.yml
.github/workflows/publish-manifest.yml
.github/workflows/publish.yml
.github/workflows/shellcheck.yml
.github/workflows/unit.yml
.github/workflows/update-docs.yml
.github/workflows/update-motoko.yml
.github/workflows/update-replica-version.yml

GitHub is deprecating Node 16.
This PR upgrade all dependency actions to the version for Node 20.

chore: fix CI warnings

---

CHANGELOG.md

As Eric noticed this should be 0.17.0 instead of 0.16.1 since it contains a breaking change

chore: add changelog header 0.17.0

---

CHANGELOG.md
src/dfx/src/commands/canister/status.rs

Display query stats when doing a canister status call via `dfx`.
Ran against a `dfx start` deployed replica. All counters are reported as `0` as expected (since the query stats feature is currently disabled).
```
./dfx canister status canister_status_backend
Canister status call result for canister_status_backend.
Status: Running
Controllers: bnz7o-iuaaa-aaaaa-qaaaa-cai zp6ar-te3c2-c6t6s-5bhid-g4iax-2lsk5-7vuol-nk7qj-qbnie-znajy-iqe
Memory allocation: 0
Compute allocation: 0
Freezing threshold: 2_592_000
Memory Size: Nat(1936150)
Balance: 3_092_003_934_543 Cycles
Reserved: 0 Cycles
Reserved Cycles Limit: 5_000_000_000_000 Cycles
Module hash: 0x682631dae48a2628a6ed7ee01f022c33ddcfd75c1e1e1d8b218e4b877c7b11e4
Number of queries: 0
Instructions spent in queries: 0
Total query request paylod …
```

feat: Added query stats to canister status output

---

CHANGELOG.md
e2e/tests-dfx/assetscanister.bash
e2e/tests-dfx/build_granular.bash
e2e/tests-dfx/call.bash
e2e/tests-dfx/identity.bash
e2e/tests-dfx/wallet.bash
src/dfx/src/commands/canister/call.rs
src/dfx/src/commands/canister/sign.rs
src/dfx/src/commands/deps/init.rs
src/dfx/src/commands/remote/generate_binding.rs
src/dfx/src/lib/builders/mod.rs
src/dfx/src/lib/models/canister.rs
src/dfx/src/lib/operations/canister/install_canister.rs
src/dfx/src/util/mod.rs

This reverts https://github.com/dfinity/sdk/pull/2931
Covered by CI.  Reverted cleanly other than changelog.

chore: revert refactor: always fetch did file from canister when making canister calls

---

docs/cli-reference/dfx-wallet.md

https://github.com/dfinity/cycles-wallet/pull/130 made it possible to target any canister with `wallet_send`, not just cycles wallets anymore. The docs currently don't reflect that change.
Purely docs change

chore: update wallet send docs to match actual behavior

---

public/install-dfxvm.sh

- Copied the latest `check_help_for()` and `downloader()` from https://github.com/rust-lang/rustup/blob/master/rustup-init.sh (https://github.com/rust-lang/rustup/commit/5bf15e351ac11bfe08234dc5776bd386b61f209a)
- Modified to also recognize Darwin major versions 12, 13, and 14.
- This adds retry functionality and improves tls/ciphersuite detection and use.
- Reworked the tarball extraction slightly to avoid having to `rm -rf` the temp directory later.
- Removed two unused functions.
Fixes https://dfinity.atlassian.net/browse/SDK-758
Tested on:
- Macos Ventura, Sonoma, and Mojave (10.14) with curl
- `docker run -it ubuntu` with wget and curl

chore(dfxvm-installer): install script maintenance

---

.github/workflows/publish.yml

To simplify release handling going forward with dfxvm, with the potential to create our releases with [cargo-dist](https://github.com/axodotdev/cargo-dist), this PR makes the release publishing workflow create a second set of tarballs that match the structure generated by cargo-dist.  It also adds the LICENSE file to the archive.
Until now, dfx release tarballs contained the `dfx` binary in the root directory:
```
$ tar -tvf ~/Downloads/dfx-0.16.1-x86_64-darwin.tar.gz
-rwxr-xr-x  0 runner staff 124834024 Jan 31 09:14 dfx
```
The new format looks like this:
```
$ tar -tvf ~/Downloads/dfx-x86_64-apple-darwin.tar.gz 
drwxr-xr-x  0 runner staff       0 Feb  6 11:56 dfx-x86_64-apple-darwin/
-rw-r--r--  0 runner staff   11348 Feb  6 11:56 dfx-x86_64-apple-darwin/LICENSE
-rwxr-xr-x  0 runner …
```

build: release workflow generates tarballs with a top-level directory

---

src/dfx/src/commands/canister/install.rs
src/dfx/src/lib/operations/canister/deploy_canisters.rs
src/dfx/src/lib/operations/canister/install_canister.rs

Notable changes:
* `dfx canister install <CANISTER_ID>` will use `install_canister_wasm()` directly which reduce a lot of conditional logic inside `install_canister()`;
* `install_canister()` takes `argument_from_cli` and `argument_type`, then assembles the install_arg blob inside
* No need to pass argument using closure;
* This is a preparatory refactor for SDK-1348. I plan to add the logic of loading init_arg in `dfx.json` around this part of code;
Also some DRY change is included.
existing e2e

refactor: install canister

---

Cargo.lock
src/dfx/Cargo.toml
src/dfx/src/util/mod.rs

> RUSTSEC-2020-0016: net2 crate has been deprecated; use socket2 instead
Fixes https://github.com/dfinity/sdk/issues/3536
`dfx start` and `dfx start --host 127.0.0.1:0`

chore: replace deprecated net2 dependency with socket2

---

CHANGELOG.md
public/install-dfxvm.sh

pass --yes to dfxvm-init if DFXVM_INIT_YES is set
This will allow https://github.com/dfinity/setup-dfx to work with dfxvm.
Fixes https://dfinity.atlassian.net/browse/SDK-1363
Tested here: https://github.com/dfinity/setup-dfx/actions/runs/7833821371/job/21375693716
Also tested locally, for example
```
DFX_VERSION=0.0.1 DFXVM_INIT_YES= sh -ci "$(cat public/install-dfxvm.sh)"
```

feat: allow dfxvm install script to bypass confirmation

---

Cargo.lock
Cargo.toml

This includes the compatibility change to the chunked wasm API in dfinity/agent-rs#512

chore: Update agent-rs to 0.33.0

---

e2e/tests-dfx/import.bash

These tests have been moved to the `dfx-extensions` repo accidentally. Moving them back here

chore: move tests to correct repo

---

.github/workflows/e2e.yml
.github/workflows/fmt.yml
.github/workflows/lint.yml
.github/workflows/unit.yml

Use dorny/paths-filter to only run e2e tests and a few other workflows when related sources change.
This will allow us to update docs without having to wait for long test workflows.
Tested by the workflows on this PR, and by opening https://github.com/dfinity/sdk/pull/3590 to this branch.

test: filter some workflows based on paths

---

docs/process/release.md

We've missed updates to `compatibility.json` in the `dfx-extensions` repo a few times now when releasing. We should mention it in the release instructions

chore(docs): add dfx-extensions update to release process

---

CHANGELOG.md
docs/concepts/pull-dependencies.md
e2e/tests-dfx/deps.bash
src/dfx/src/commands/deps/deploy.rs
src/dfx/src/commands/deps/init.rs
src/dfx/src/commands/deps/pull.rs
src/dfx/src/lib/deps/mod.rs

`dfx deps pull` was recently changed to allow hash mismatch wasm. But `init` and `deploy` weren't change accordingly.
Also the warning of hash mismatch is removed since it scares users and users can't fix it locally.
Fixes SDK-1380
e2e/deps.bash

fix(deps): init/deploy still requires hash check

---

CHANGELOG.md
e2e/tests-dfx/build.bash
e2e/tests-dfx/dotenv.bash
src/dfx/src/commands/build.rs
src/dfx/src/lib/builders/mod.rs
src/dfx/src/lib/operations/canister/deploy_canisters.rs
src/dfx/src/lib/operations/canister/install_canister.rs
src/dfx/src/lib/operations/canister/mod.rs

Made it so `dfx deploy` and `dfx canister install` will always write canister ids for
all canisters in the project to the .env file, even if they aren't being deployed/installed or
a dependency of a canister being deployed/installed.
Fixes https://dfinity.atlassian.net/browse/SDK-1369
Updated an e2e test (dfx build) and added two more (dfx deploy, dfx canister install)

fix: no more disappearing canister ids from .env files

---

CHANGELOG.md
e2e/tests-dfx/generate.bash
src/dfx/src/lib/builders/assets.rs
src/dfx/src/lib/builders/custom.rs
src/dfx/src/lib/builders/mod.rs
src/dfx/src/lib/builders/motoko.rs
src/dfx/src/lib/builders/pull.rs
src/dfx/src/lib/builders/rust.rs

SDK-1380
Fixed a bug where `dfx generate` would delete a canister's source candid file if the `declarations.bindings` in `dfx.json` did not include "did".
Reported in https://github.com/nathanosdev/sdk_rust_candid_issue
`dfx generate`, in brief, gets the candid file of a canister and generate other bindings based on this .
The incorrect implementation required all impl of `CanisterBuilder` to have a `generate_idl()`  method. And the `generate_idl()` method should copy the source candid file into `declarations/` dir. After generating all bindings, `dfx generate` will remove the candid file (should be `declarations/<canister>.did`) if `declarations.bindings` doesn't contains "did".
The `RustCanisterBuilder` didn't follow the requirement of `generate_id()`. Instead, its `generate_id()` …

fix(generate): Rust canister source candid wrongly deleted

---

Cargo.lock
e2e/assets/fake_cmc/dfx.json
e2e/assets/fake_registry/dfx.json
e2e/assets/fake_registry/fake_registry.mo
e2e/tests-dfx/cycles-ledger.bash
e2e/utils/_.bash
src/dfx-core/src/config/model/canister_id_store.rs
src/dfx/src/commands/canister/create.rs
src/dfx/src/commands/deploy.rs
src/dfx/src/commands/ledger/create_canister.rs
src/dfx/src/commands/ledger/notify/create_canister.rs
src/dfx/src/commands/quickstart.rs
src/dfx/src/lib/named_canister.rs
src/dfx/src/lib/operations/canister/create_canister.rs
src/dfx/src/lib/operations/canister/deploy_canisters.rs
src/dfx/src/lib/operations/cmc.rs
src/dfx/src/lib/operations/cycles_ledger.rs
src/dfx/src/lib/subnet.rs
src/dfx/src/util/clap/subnet_selection_opt.rs

When the cycles ledger is used to create canisters it automatically should put canisters on the same subnet so cross-canister calls don't take forever.
Fixes [SDK-1372](https://dfinity.atlassian.net/browse/SDK-1372)
added e2e
[SDK-1372]: https://dfinity.atlassian.net/browse/SDK-1372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: make it easy to keep to keep a users canisters on the same subnet

---

CHANGELOG.md
e2e/tests-dfx/call.bash
src/dfx/src/commands/canister/call.rs
src/dfx/src/commands/canister/sign.rs
src/dfx/src/lib/operations/canister/mod.rs

SDK-1318
Fixed a bug where `dfx canister call` would fail when the deployed canister was removed from dfx.json.
A sample error:
```
$ dfx canister id ckbtc_kyt
aovwi-4maaa-aaaaa-qaagq-cai
$ dfx canister info ckbtc_kyt
Controllers: bkyz2-fmaaa-aaaaa-qaaaq-cai tb3st-xv2zz-fpfob-ku4oa-lmsvj-luynb-334fa-v42pq-m5avw-i4nch-bae
Module hash: 0xed21443ca58aad3e2b04502e3b5569c826eb7fa38c5df333920ae45cadafb874
$ dfx canister call ckbtc_kyt set_api_key '( record { api_key = "abc" } )' --candid kyt.did 
Error: Failed to get canister id and path to its candid definitions for 'ckbtc_kyt'.
Caused by: Failed to get canister id and path to its candid definitions for 'ckbtc_kyt'.
Failed to load canister info for 'ckbtc_kyt'.
Cannot find canister 'ckbtc_kyt',
```
`dfx canister id/info` can execute without …

fix: failed to call a canister removed from dfx.json

---

CHANGELOG.md
e2e/tests-dfx/install.bash
src/dfx/src/commands/canister/install.rs

Fixed a bug where `dfx canister install` would fail when specify a canister id and there is no dfx.json.
A sample error:
```
Error: Failed to get pull canisters defined in dfx.json.
Caused by: Failed to get pull canisters defined in dfx.json.
Cannot find dfx configuration file in the current working directory. Did you forget to create one?
```
Fixes SDK-1384
Add an e2e test in install.bash

fix: failed to install when specify id without dfx.json

---

e2e/tests-dfx/start.bash

Sample failures:
https://github.com/dfinity/sdk/actions/runs/8143004480/job/22254823042#step:10:67
https://github.com/dfinity/sdk/actions/runs/8120382844/job/22197858666#step:10:139
The test involved `--enable-bitcoin` which introduced out-of-control factors and made the test flacky.
Before the change, the test had a high failure probability.
With the change, my three consecutive runs succeed locally.
We should also monitor the CI in the next few days to see if the flacky errors show again.

test: improve a flacky start e2e test

---

CHANGELOG.md
e2e/tests-dfx/assetscanister.bash
src/canisters/frontend/ic-asset/src/asset/config.rs

Previously, any configuration element in .ic-assets.json functioned as if a setting of
`"allow_raw_access": true` were present in the json object.
For example, given the following configuration, all files would be configured
with `allow_raw_access` set to `true`, as if the second entry specified
`"allow_raw_access": true` (which is the default), even though it does not.
```json
[
{
"match": "**/*",
"allow_raw_access": false
},
{
"match": "**/*",
"headers": {
"X-Anything": "Something"
}
}
]
```
Now, given the same configuration, all files would be configured with `allow_raw_access` set to false, as expected.
Note that the default value of `allow_raw_access` is still `true`.
Fixes https://dfinity.atlassian.net/browse/SDK-1238
Notes to reviewers:
- the default of `true` comes from here: …

fix: .ic-assets.json configuration entries no longer overwrite the default for allow_raw_access

---

e2e/assets/playground_backend/mops.toml
e2e/tests-dfx/playground.bash

The local playground canister failed to compile with `moc` v0.11.0.
So I pinned the Motoko toolchain version to v0.10.4 in `mops.toml`. 
And in the `setup_playground`, I added `mops toolchain init` to use the pinned `moc`.
playground e2e tests

fix: playground e2e tests

---

.github/workflows/e2e.yml
.github/workflows/fmt.yml
.github/workflows/lint.yml
.github/workflows/unit.yml

The always() check provides a "status check"
https://docs.github.com/en/actions/learn-github-actions/expressions#status-check-functions
If a status check isn't present, a default status check of success() is automatically applied.
This meant that the e2e:required status could be skipped even on test failure, and when skipped, be marked as successful for purposes of required statuses.
Fixes https://dfinity.atlassian.net/browse/SDK-1474
Tested here: https://github.com/dfinity/sdk/actions/runs/8177422298/job/22359553279?pr=3644

fix: CI e2e:required status could skip even on failure

---

e2e/assets/deps/onchain/dfx.json
e2e/tests-dfx/deps.bash
src/dfx/src/util/mod.rs

In recent few CI run of the deps e2e test, it took abnormally longer time than usual (over 30mins v.s. around 5 mins).
A sample: https://github.com/dfinity/sdk/actions/runs/8256057849/job/22585991303
The test hanged when trying to download from "http://example.com/b.wasm.gz". That URL was believed to always return 404 which will terminate the download without retry. For some unknown reason, the URL may returns "500 internal server error" which makes the `download_file` retries indefinitely.
This PR not only fix the e2e test to use a "always 404" URL, but also limit the retry logic inside `download_file` to at most 60s.
A unit test was added to check if `download_file` retries at most 60s. This will make the "[Check cargo (unit) test](https://github.com/dfinity/sdk/actions/workflows/unit.ym …

fix: limit download_file max retry time to 60s

---

CHANGELOG.md
e2e/tests-dfx/logs.bash
src/dfx/src/commands/canister/logs.rs

`dfx canister logs` now outputs to stdout, rather than stderr, so that its output is `grep` and `tail` compatible.
Added corresponding tests to `e2e/tests-dfx/logs.bash`.

fix: [IC-272] make fetching canister logs grep- and tail- compatible

---

.gitignore
CHANGELOG.md
e2e/assets/bitcoin/bitcoin.did
e2e/tests-dfx/bitcoin.bash
nix/sources.json
src/dfx/assets/dfx-asset-sources.toml
src/dfx/src/commands/canister/call.rs

Reverts dfinity/sdk#3593
Bitcoin Canister release/2024-01-22 doesn't work with application subnet. (It drains all the cycles on purpose which is fine only on the system subnet).
The bitcoin canister will be fixed in a few weeks.
Before that, we need to downgrade it to the previous version.
To detect such break in the future, I added two bitcoin.bash e2e tests:
* check if the canister has enough cycles balance.
* check if the management canister Bitcoin API can be called.
* When testing the two query API, I found out that their effective_canister_id were set incorrectly. Fixed in this PR.
* A `bitcoin.did` is added for the test. It was refined from the `ic.did` in the spec and added the `regtest` network variant.
Also filled the missing changelog entry in v0.18.0.

chore: downgrade Bitcoin Canister back to 2023-10-13 (revert #3593)

---

CHANGELOG.md
src/dfx/src/commands/wallet/set_name.rs

As [reported on the forum](https://forum.dfinity.org/t/wallet-set-name/28460) `dfx wallet set-name` does not work. It calls the [wrong function](https://github.com/dfinity/cycles-wallet/blob/main/wallet/src/lib.rs#L145-L154) of the cycles wallet.
Manually tested against my existing cycles wallet

fix: dfx wallet set-name calls the wrong function

---

.github/workflows/lint.yml
src/dfx-core/src/fs/mod.rs

`clippy::all` is the lint group that clippy enables by default. `-Dclippy::all` does not error on lints from rustc, nor on explicitly `#[warn]`ed clippy lints. The flag to error on all warnings is `-Dwarnings`.

chore: Update CI to fail rustc lints

---

CHANGELOG.md
Cargo.lock
docs/cli-reference/dfx-canister.mdx
e2e/assets/method_signatures/dfx.json
e2e/assets/method_signatures/main.mo
e2e/tests-dfx/call.bash
src/dfx/Cargo.toml
src/dfx/src/commands/canister/call.rs
src/dfx/src/commands/canister/logs.rs
src/dfx/src/util/mod.rs

this is the same as dfx canister call ... | idl2json
See: https://github.com/dfinity/idl2json
Fixes: https://dfinity.atlassian.net/browse/SDK-1370
Added e2e tests

feat: canister call accepts --output json

---

CHANGELOG.md
src/dfx/src/commands/canister/call.rs
src/dfx/src/commands/canister/delete.rs
src/dfx/src/commands/canister/install.rs
src/dfx/src/commands/canister/sign.rs
src/dfx/src/commands/deploy.rs
src/dfx/src/lib/integrations/mod.rs
src/dfx/src/lib/operations/canister/deploy_canisters.rs
src/dfx/src/lib/operations/canister/install_canister.rs
src/dfx/src/util/mod.rs

https://forum.dfinity.org/t/dfx-0-18-0-is-promoted/28221/7

feat: add --always-assist flag for canister call/install/deploy/sign

---

.github/workflows/audit.yml

The audit action doesn't build `cargo-audit` with `--locked` which caused our recent audit jobs failure.
I created the [PR](https://github.com/actions-rust-lang/audit/pull/72) to fix the action.
This PR on our side prove that the fix works.
The Audit CI job should pass now.

fix(ci): audit

---

docs/cli-reference/dfx-deploy.mdx
docs/cli-reference/dfx-envars.mdx
docs/cli-reference/dfx-identity.mdx
docs/cli-reference/dfx-ping.mdx

In order to update [Docusaurus to v3](https://docusaurus.io/blog/preparing-your-site-for-docusaurus-v3#preparing-content-for-mdx-v3), we must ensure the mdx files read by the portal can be parsed by version 3 of the mdx parser engine.

chore: update markdown content for pass mdx v3 parser

---

src/dfx/src/commands/mod.rs
src/dfx/src/lib/diagnosis.rs
src/dfx/src/main.rs

DRY error handling and simplify dfx's main function.
This supports upcoming work for extension-defined canister types, which will need the ExtensionManager when constructing the Environment.
Covered by e2e, in particular the test that `dfx schema` works even without a valid dfx.json

refactor: simplify main and DRY error handling

---

src/dfx/src/commands/extension/install.rs
src/dfx/src/commands/extension/list.rs
src/dfx/src/commands/extension/run.rs
src/dfx/src/commands/extension/uninstall.rs
src/dfx/src/lib/environment.rs
src/dfx/src/main.rs

Since instantiating the ExtensionManager is literally the first thing to happen, keep it around.  We will also soon need it when loading the configuration.

refactor: instantiate extension manager once

---

Cargo.lock

See failed workflow run: https://github.com/dfinity/sdk/actions/runs/8546427855?pr=3694
https://rustsec.org/advisories/RUSTSEC-2024-0332.html

chore: update h2 dependency in order to pass cargo audit

---

CHANGELOG.md
e2e/tests-dfx/usage.bash
src/dfx-core/src/config/model/canister_id_store.rs
src/dfx-core/src/config/model/dfinity.rs
src/dfx-core/src/error/canister_id_store.rs
src/dfx-core/src/error/config.rs
src/dfx-core/src/error/network_config.rs
src/dfx-core/src/network/provider.rs
src/dfx/src/commands/identity/rename.rs
src/dfx/src/commands/start.rs
src/dfx/src/lib/builders/mod.rs
src/dfx/src/lib/canister_info.rs
src/dfx/src/lib/environment.rs

Make it so Environment::new doesn't create the .dfx directory; instead, create it when calling Config.get_temp_path().
The main motivation is to make it so Environment::new doesn't have to instantiate the Config at all, which is in turn in order to make it so dfx only loads dfx.json if it will use it.
Prep work for https://dfinity.atlassian.net/browse/SDK-1559

fix: dfx only creates .dfx directory if it's going to access it

---

CHANGELOG.md
e2e/tests-dfx/usage.bash
src/dfx-core/src/error/canister_id_store.rs
src/dfx/src/commands/canister/id.rs
src/dfx/src/commands/canister/update_settings.rs
src/dfx/src/commands/info/replica_port.rs
src/dfx/src/commands/info/webserver_port.rs
src/dfx/src/commands/language_service.rs
src/dfx/src/commands/ping.rs
src/dfx/src/commands/start.rs
src/dfx/src/commands/stop.rs
src/dfx/src/lib/agent.rs
src/dfx/src/lib/environment.rs
src/dfx/src/lib/models/canister.rs
src/dfx/src/lib/operations/canister/deploy_canisters.rs
src/dfx/src/lib/operations/canister/install_canister.rs

For example, this will work now:
```bash
echo garbage >dfx.json && dfx identity get-principal
```
This is meant to support reloading the config file in the future, which is why it uses RefCell and not OnceCell.
Fixes https://dfinity.atlassian.net/browse/SDK-1559

fix: dfx only loads dfx.json for commands that need it

---

Cargo.lock
Cargo.toml

SDK-1539
In agent-rs, we modified the types of the chunk store API to conform the specification.
Upgrading agent-rs dependencies changes the underlying call to the chunk store API when install large wasm.
There is no user visible changes in dfx.
The existing "can install >2MiB wasm" test in install.bash.
It also verifies the correctness of the [agent-rs PR](https://github.com/dfinity/agent-rs/pull/545).

chore: upgrade agent-rs

---

.github/workflows/update-docs.yml
CHANGELOG.md
docs/cli-reference/dfx-schema.mdx
docs/dfx-metadata-schema.json
e2e/tests-dfx/schema.bash
src/dfx/src/commands/schema.rs
src/dfx/src/lib/metadata/dfx.rs

`dfx schema --for dfx-metadata` to display JSON schema of the "dfx" metadata.
Added e2e tests in schema.bash.
The generated schema file is also included in source control.

feat: display schema for dfx metadata json

---

e2e/tests-dfx/metadata.bash
src/dfx-core/src/config/model/dfinity.rs

When a canister defines not all 5 tech_stack categories, the generated metadata JSON contained the undefined categories as null object. For example:
```json
{
"tech_stack": {
"cdk": {
"ic-cdk": {
"version": "0.13.2"
}
},
"language": null,
"lib": null,
"tool": null,
"other": null
}
}
```
This PR skip serializing such fields when they are None.
```json
{
"tech_stack": {
"cdk": {
"ic-cdk": {
"version": "0.13.2"
}
}
}
}
```
In the metadat.bash e2e test, added a check:
```bash
assert_command jq -r '.tech_stack | keys[]' b.json
assert_eq "cdk" # only cdk is defined
```

fix: skip serializing tech_stack null categories

---

e2e/tests-dfx/playground.bash

The playground test is failing.
Examples:
- https://github.com/dfinity/sdk/actions/runs/8803187859/job/24161266261
- https://github.com/dfinity/sdk/actions/runs/8803438757/job/24162434193?pr=3722
Hypothesis: introduced in [mops](https://cli.mops.one/) 0.44.0, released 2024-04-22
Tested by existing playground test

test: pin mops to 0.43.0

---

e2e/tests-dfx/call.bash

The Bitcoin testnet has some abnormal performance recently which caused the Bitcoin Canister for testnet keep returning 
an error of "Canister state is not fully synced.".
This PR disable the Bitcoin testnet tests.
The Bitcoin mainnet tests are kept.
A TODO comment was added to tracking with https://dfinity.atlassian.net/browse/SDKTG-323.

test: disable bitcoin testnet tests

---

docs/concepts/pull-dependencies.md
docs/concepts/tech-stack.md
src/dfx/assets/project_templates/azle/dfx.json-patch

It was not clear that `"tech_stack"` is part of the metadata under the key of `"dfx"`.
This PR clarifies it in both `pull-dependencies.md` and `tech-stack.md`. Reverse links to `canister-metadata.md` are added.
Also added `javascript` to the Azle template `dfx.json`, as suggested by @lastmjs, the author of Azle.

docs: tech_stack - clarify metadata key and add reverse links

---

CHANGELOG.md
e2e/tests-dfx/new.bash
src/dfx/src/commands/new.rs

`dfx new` would fail with "Failed to scaffold frontend code" if node was installed, but npm was not installed.
Also, now checks the status code when calling node and npm to see if they are installed. This means if there is a script that outputs something like the below, dfx will no longer assume the program is installed.
```
$ npm
Command 'npm' not found, but can be installed with: apt install npm
Please ask your administrator.
```

fix: for dfx new failure if node is installed but npm is not

---

CHANGELOG.md
docs/dfx-json-schema.json
e2e/tests-dfx/deploy.bash
e2e/tests-dfx/install.bash
src/dfx-core/src/config/model/dfinity.rs
src/dfx/src/lib/canister_info.rs
src/dfx/src/lib/operations/canister/install_canister.rs

In addition to setting `init_arg` in `dfx.json`, `init_arg_file` can be set in `dfx.json`.
- Please set a relative path to the directory where the the `dfx.json` is located.
- `init_arg` and `init_arg_file` cannot be set simultaneously.
- If `--argument` or `--argument-file` are provided, the argument from the command line takes precedence over the one in dfx.json.
Fixes [SDK-1455](https://dfinity.atlassian.net/browse/SDK-1455)
e2e: install.bash
[SDK-1455]: https://dfinity.atlassian.net/browse/SDK-1455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: init_arg_file in dfx.json

---

e2e/tests-dfx/playground.bash

The issue for which we pinned mops was fixed in 0.44.1
https://cli.mops.one/
> 0.44.1
2024-04-24
•
678 KiB
•
b10db8562b5cc2e4ab77bef7dae95912c34ba1dfe5bc96c43932e2dbcef5af8d
Fixed fallback to dfx moc if there is no mops.toml
Playground e2e

chore: unpin mops

---

src/dfx-core/src/identity/identity_manager.rs
src/dfx/src/lib/environment.rs

Changes the signature of `Environment::get_identity_override()` and `IdentityManager::new()` to be more idiomatic rust, using `Option<&str>` rather than `&Option<String>`.
The motivation is in consideration of another caller of `IdentityManager::new()`, which may pass `None` for the identity override.
Refactor covered by e2e

refactor: more idiomatic identity override

---

CHANGELOG.md
docs/cli-reference/dfx-identity.mdx
src/dfx/src/commands/identity/new.rs

The `dfx identity new` help text and documentation don't state what a valid identity name looks like.
Fixes [SDK-1481](https://dfinity.atlassian.net/browse/SDK-1481)
Not tested
[SDK-1481]: https://dfinity.atlassian.net/browse/SDK-1481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: document valid identity names

---

src/dfx-core/src/error/root_key.rs
src/dfx-core/src/network/root_key.rs
src/dfx/src/lib/root_key.rs

Renames (with deprecation0 two methods, since the criterion involved is whether the network is mainnet or not, rather than whether it is the local network or not, and the "local" setting also applies to testnets.
- fetch_root_key_when_local -> fetch_root_key_when_non_mainnet
- fetch_root_key_when_local_or_error -> fetch_root_key_when_non_mainnet_or_error
The motivation is an upcoming improvement to the interface used at https://github.com/dfinity/dfx-extensions/blob/main/extensions/nns/src/commands/install.rs#L70
Refactor covered by CI

refactor: fetch root key method names

---

Cargo.lock
src/dfx-core/Cargo.toml
src/dfx-core/src/error/builder.rs
src/dfx-core/src/error/identity/new_identity_manager.rs
src/dfx-core/src/error/mod.rs
src/dfx-core/src/identity/identity_manager.rs
src/dfx-core/src/interface/builder.rs
src/dfx-core/src/interface/dfx.rs
src/dfx-core/src/interface/mod.rs
src/dfx-core/src/lib.rs
src/dfx/src/lib/environment.rs

Adds `DfxInterface` and `DfxInterfaceBuilder` to dfx-core, meant to make it easier to load the dfx configuration and create an agent.
For an example use see: https://github.com/dfinity/dfx-extensions/pull/104/files#diff-f5cfacf098ff19a8547e1a28f532da8dd3edb0fa0c51c0a82d54b237760af60aR33
Companion PR: https://github.com/dfinity/dfx-extensions/pull/104
Added unit tests, and also tested in https://github.com/dfinity/dfx-extensions/pull/104.

feat: add DfxInterface and builder for easier setup

---

CHANGELOG.md
docs/cli-reference/dfx-canister.mdx
docs/cli-reference/dfx-identity.mdx
docs/dfx-json-schema.json
e2e/assets/wasm/identity/README.adoc
e2e/tests-dfx/build.bash
e2e/tests-dfx/create.bash
e2e/tests-dfx/deploy.bash
e2e/tests-dfx/rust.bash
e2e/tests-dfx/update_settings.bash
src/dfx-core/src/config/model/dfinity.rs
src/dfx-core/src/error/dfx_config.rs
src/dfx-core/src/extension/manifest/extension.rs
src/dfx/src/commands/canister/create.rs
src/dfx/src/commands/canister/info.rs
src/dfx/src/commands/canister/install.rs
src/dfx/src/commands/canister/status.rs
src/dfx/src/commands/canister/update_settings.rs
src/dfx/src/commands/identity/deploy_wallet.rs
src/dfx/src/lib/builders/custom.rs
src/dfx/src/lib/ic_attributes/mod.rs
src/dfx/src/lib/models/canister.rs
src/dfx/src/lib/operations/canister/deploy_canisters.rs

This replaces incorrect capitalization of "WASM" with "Wasm", which is the official abbreviation of WebAssembly.
See: https://webassembly.org/
The reason why not all letters are capitalized is because "Wasm" is not an acronym, but rather an abbreviation.
This change also fixes capitalization of the canister status output to be consistent wih other fields.

fix: Capitalization of "Wasm"

---

CHANGELOG.md
e2e/tests-dfx/assetscanister.bash
src/canisters/frontend/ic-asset/src/sync.rs

Well-founded complaint:
> May I ask what's the reasoning between not allowing .well-known folder per default and forcing each developers to whitelist this folder in ic-assets.json?
I had to answer and explain countless time, often per private message, how to set up such a file. It's becoming annoying, particularly when I'm pinged late in the evening, therefore I am curious to know if there is a valid reason.
This PR automatically adds `.well-known` to the list of synced directories
Fixes [SDK-1408](https://dfinity.atlassian.net/browse/SDK-1408)
Inspired quite a bit by #2948
Added unit tests
[SDK-1408]: https://dfinity.atlassian.net/browse/SDK-1408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix!: sync .well-known dir by default

---

CHANGELOG.md
docs/cli-reference/dfx-ledger.mdx
e2e/tests-dfx/ledger.bash
src/dfx/src/commands/ledger/account_id.rs

This PR makes it possible to derive the subaccount from a principal in the `dfx ledger account-id` command.
This is useful for NNS voters to validate NNS subnet rental request proposals by deriving the ledger account (controlled by the subnet rental canister's principal and using the proposer's principal as the subaccount) to which the proposer should have transfered the deposit.
A new e2e test has been added comparing the account ID returned by DFX against the account ID computed by the SRC for the caller.

feat: subaccount can be derived from principal in dfx ledger account-id

---

CHANGELOG.md
docs/cli-reference/dfx-canister.mdx
src/dfx/src/commands/canister/delete.rs

`dfx canister delete` occasionally fails because it attempts to withdraw too many cycles from the canister before it is deleted. Usually, `dfx` tries again with a larger margin of cycles, but sometimes this gets stuck. It is now possible to use `--initial-margin` to manually supply a margin in case the automatic margin does not work.
This is a temporary workaround until [a clean solution](https://dfinity.atlassian.net/browse/SDKTG-340) exists (requires spec change, runtime change, wallet change, agent support).
Fixes [SDK-1556](https://dfinity.atlassian.net/browse/SDK-1556)
Tested manually on mainnet
[SDK-1556]: https://dfinity.atlassian.net/browse/SDK-1556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: --initial-margin for dfx canister delete

---

docs/cli-reference/dfx-envars.mdx

Remove reference in docs to a warning removed in https://github.com/dfinity/sdk/pull/3624

docs: remove reference to obsolete warning

---

CHANGELOG.md
e2e/tests-dfx/describe_local_network.bash
src/dfx-core/src/network/provider.rs

Changed the message
```
Using the default definition for the 'local' shared network because ~/.config/dfx/networks.json does not define it.
```
to
```
Using the default configuration for the local shared network.
```

fix: reword confusing log message about default shared network config

---

CHANGELOG.md
Cargo.lock
Cargo.toml
e2e/tests-dfx/bitcoin.bash
e2e/tests-dfx/call.bash
src/dfx/src/commands/canister/call.rs

SDK-1720
The bitcoin query API are to be removed from replica and spec.
`agent-rs` has already [removed](https://github.com/dfinity/agent-rs/pull/567) the query API. Updated the agent dependencies to `be929fd7967249c879f48f2f494cbfc5805a7d98`.

feat!: remove support for bitcoin query API

---

docs/process/release.md

Given our new extended beta release schedule, we should be posting to the forum when the betas are available, not just when promoting the release.

docs: early forum post for betas

---

scripts/workflows/provision-darwin.sh
scripts/workflows/provision-linux.sh

CI is broken because binstall bumped the Rust required version in the latest version bump
CI

chore: pin binstall version so CI doent spontaneously break

---

CHANGELOG.md
e2e/tests-dfx/assetscanister.bash
src/canisters/frontend/ic-asset/src/asset/config.rs
src/canisters/frontend/ic-asset/src/asset/content.rs
src/canisters/frontend/ic-asset/src/asset/content_encoder.rs
src/canisters/frontend/ic-asset/src/batch_upload/plumbing.rs

Allows configuring which encodings are uploaded to the asset canister in `.ic-assets.json`
Fixes [SDK-1721](https://dfinity.atlassian.net/browse/SDK-1721)
added e2e
[SDK-1721]: https://dfinity.atlassian.net/browse/SDK-1721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: choose asset encodings that are synced to asset canister

---

CHANGELOG.md
Cargo.lock
e2e/tests-dfx/assetscanister.bash
src/canisters/frontend/ic-asset/Cargo.toml
src/canisters/frontend/ic-asset/src/asset/content.rs
src/canisters/frontend/ic-asset/src/asset/content_encoder.rs
src/canisters/frontend/ic-asset/src/batch_upload/plumbing.rs
src/canisters/frontend/ic-asset/src/evidence/mod.rs

Asset synchronization now not only uploads `identity` and `gzip` as encodings for MIME types `text`, `js`, and `html`, but also `br` encoding. 
Fixes [SDK-1604](https://dfinity.atlassian.net/browse/SDK-1604)
Added e2e
[SDK-1604]: https://dfinity.atlassian.net/browse/SDK-1604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: upload br encoding to asset canister

---

.github/workflows/update-docs.yml

The update-docs workflow doesn't work (skips itself) for external PRs.
Make it fail any PR if any of the schema command outputs changed and the changes are not included in the PR, rather than pushing a commit to update them.
This way it will work on external PRs too, and we can make it a required status.
The following PR makes a schema change: https://github.com/dfinity/sdk/pull/3805

feat: require all PRs to update JSON schema if changed

---

.github/workflows/update-docs.yml
CHANGELOG.md
docs/cli-reference/dfx-schema.mdx
docs/extension-manifest-schema.json
src/dfx-core/src/extension/manifest/extension.rs
src/dfx/src/commands/schema.rs

`dfx schema --for extension-manifest` now generates the JSON schema for extension.json files.
Updated CI workflow

feat: generate extension manifest schema

---

CHANGELOG.md
src/dfx/assets/project_templates/react/src/__frontend_name__/package.json
src/dfx/assets/project_templates/react/src/__frontend_name__/public/.ic-assets.json5
src/dfx/assets/project_templates/simple_assets/src/__frontend_name__/assets/.ic-assets.json5
src/dfx/assets/project_templates/svelte/src/__frontend_name__/package.json
src/dfx/assets/project_templates/svelte/src/__frontend_name__/static/.ic-assets.json5
src/dfx/assets/project_templates/vanilla_js/src/__frontend_name__/assets/.ic-assets.json5
src/dfx/assets/project_templates/vanilla_js/src/__frontend_name__/package.json
src/dfx/assets/project_templates/vue/src/__frontend_name__/package.json
src/dfx/assets/project_templates/vue/src/__frontend_name__/public/.ic-assets.json5

With an updated `@dfinity/agent` package the `unsafe-eval` CSP is no longer required
Fixes [FOLLOW-383](https://dfinity.atlassian.net/browse/FOLLOW-383)
Tested manually, and is partially covered by CI as well.
[FOLLOW-383]: https://dfinity.atlassian.net/browse/FOLLOW-383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore!: rm `unsafe-eval` from default project CSP

---

src/dfx/src/config/cache.rs

When dfx runs for the first time, it installs binaries, including itself, to the dfx cache. It also displays a message that it has done so. Without context, this message can be confusing.
Changed the final message to include context about what (dfx) it's installing and where (the cache)
before
```
$ dfx extension install nns --version 0.3.1
Version v0.21.0-beta.0+rev12.ecf712721 installed successfully.
Extension 'nns' installed successfully
```
after
```
$ dfx extension install nns --version 0.3.1
Installed dfx 0.21.0-beta.0+rev12.ecf712721 to cache.
Extension 'nns' installed successfully
```

fix: add context to dfx cache installation message

---

CHANGELOG.md
e2e/tests-dfx/build.bash
scripts/workflows/provision-linux.sh
src/dfx/src/commands/build.rs

`dfx build` should not require a password as it does not depend on anything on-chain
Reported on the [forum](https://forum.dfinity.org/t/dfx-build-requires-password/32546)
added e2e

fix: dfx build no longer requires a password

---

docs/extension-manifest-schema.json
src/dfx-core/src/extension/manifest/extension.rs
src/dfx-core/src/json/structure.rs

Currently, extension.json is always written by hand. Since the target type of extension.json is [ExtensionManifest](https://github.com/dfinity/sdk/blob/master/src/dfx-core/src/extension/manifest/extension.rs#L20), in theory it could be automatically generated from the information by clap. But libraries importing ExtensionManifest are not able to actually do this because some fields are not `pub` and because `ExtensionManifest` doesn't implement `Serialize`. This PR fixes both of those issues

refactor: Prepare for auto-generation of extension.json

---

Cargo.lock
src/dfx-core/Cargo.toml
src/dfx-core/src/error/extension.rs
src/dfx-core/src/error/mod.rs
src/dfx-core/src/error/reqwest.rs
src/dfx-core/src/extension/manager/install.rs
src/dfx-core/src/extension/manifest/compatibility_matrix.rs
src/dfx-core/src/http/get.rs
src/dfx-core/src/http/mod.rs
src/dfx-core/src/http/retryable.rs
src/dfx-core/src/lib.rs
src/dfx/src/commands/extension/install.rs

Upcoming changes to extension dependency management use retries and async.  This PR updates existing code to use async.  It makes minimal changes to compatibility_matrix.rs since it will soon be deleted.
Covered by CI, and also ran `cargo build && dfx cache delete && dfx cache install && dfx extension install nns` (fails as expected due to no entry in compatibility matrix) and then `dfx extension install --version 0.3.1`

refactor: convert extension install to async

---

CHANGELOG.md
src/dfx/src/commands/canister/call.rs

Internal [complaint](https://dfinity.slack.com/archives/CGA566TPV/p1719989491013429):
>If I pass arguments that won't work, such as --with-cycles without --wallet, it would be nice to get an error about that before walking though the entire interactive wizard.
With this change the user will see the error message instantly. The requirement is not new, just enforced at an earlier point in time.
Tested manually

chore!: --with-cycles requires --wallet is enforced earlier

---

CHANGELOG.md
e2e/tests-dfx/deploy.bash
src/dfx/src/lib/canister_info/motoko.rs
src/dfx/src/lib/models/canister.rs

Build the canister dependency graph only for the requested canisters, instead of building it for all canisters.
The motivation for this is that sometimes `canister.builder.get_dependencies` returns an error for some canisters, as those canisters are not properly formed (e.g. they are Motoko canisters with no `main` field). In this case, you could still theoretically call `dfx deploy <canister>` and you might expect dfx to not complain that some unrelated canisters in your dfx.json are not properly formed. By only calling `canister.builder.get_dependencies` on canisters that are actually needed for building the canister being deployed, we can avoid this from happening.
Of course, `dfx deploy` without specifying a canister will still not work. But it seems to be common for people to use …

fix: Build the canister dependency graph only for the requested canisters

---

CHANGELOG.md
src/canisters/frontend/ic-asset/src/batch_upload/retryable.rs

Fix for transient errors seen during asset upload as seen here: https://github.com/dfinity/portal/actions/runs/9838832207/job/27161262607
The status codes chosen correspond to the those checked for here: https://github.com/dfinity/sdk/pull/3815/files#diff-8d43d31fa855300ef66d8e25f19a7747fd49d36429a10f4fd2a9b077b568d832R12
Not tested specifically, but see above for a failed upload that may have succeeded with this change.

fix: retry certain http errors reported by replica during asset uploads

---

.github/workflows/e2e.yml
src/dfx/src/lib/builders/custom.rs
src/dfx/src/lib/builders/mod.rs
src/dfx/src/lib/builders/motoko.rs
src/dfx/src/lib/builders/pull.rs
src/dfx/src/lib/builders/rust.rs
src/dfx/src/lib/canister_info.rs
src/dfx/src/lib/canister_info/assets.rs
src/dfx/src/lib/canister_info/custom.rs
src/dfx/src/lib/canister_info/motoko.rs
src/dfx/src/lib/canister_info/pull.rs
src/dfx/src/lib/canister_info/rust.rs
src/dfx/src/lib/models/canister.rs
src/dfx/src/lib/operations/canister/mod.rs

Add `CanisterInfo.output_idl_path` and remove it from MotokoCanisterInfo, RustCanisterInfo, and so forth, and remove `CustomBuilderExtra.candid`.
Changed the return type of `CanisterInfo.get_output_idl_path()` from `Option<PathBuf>` to `&Path` since it is guaranteed to be set.
The motivation is to move in the direction of removing all of the *CanisterInfo types, instead having properties on CanisterInfo.
Covered by existing e2e tests

refactor: remove output_idl_path from <type>CanisterInfo types

---

CHANGELOG.md
src/dfx-core/src/error/extension.rs
src/dfx-core/src/error/reqwest.rs
src/dfx-core/src/extension/manager/install.rs
src/dfx-core/src/extension/manifest/dependencies.rs
src/dfx-core/src/http/get.rs
src/dfx-core/src/http/mod.rs
src/dfx-core/src/http/retryable.rs

Since reqwest 0.12.1 (https://github.com/seanmonstar/reqwest/pull/2199), fmt::Display for reqwest::Error no longer includes the source.
The whole reason for WrappedReqwestError was to avoid displaying the source twice. But since the above change, the source isn't displayed at all.
After this change, dfx will once again display the error source(s) for request::Error, but on separate lines ("Caused by:") like other error sources.
Tested locally with `dfx extension install` with an extension.json with missing fields
Before
```
Error: error decoding response body
```
After
```
Error: error decoding response body
Caused by: missing field `homepage` at line 4 column 4
```

fix: display reqwest::Error source

---

CHANGELOG.md
docs/cli-reference/dfx-start.mdx
src/dfx-core/src/config/model/replica_config.rs
src/dfx-core/src/config/model/settings_digest.rs
src/dfx/src/actors/replica.rs
src/dfx/src/commands/start.rs

Replica no longer support this flag

chore: remove the deprecated --use-old-metering flag

---

CHANGELOG.md
docs/dfx-json-schema.json
e2e/assets/rust_complex/Cargo.toml
e2e/assets/rust_complex/can1/Cargo.toml
e2e/assets/rust_complex/can1/src/main.rs
e2e/assets/rust_complex/can2/Cargo.toml
e2e/assets/rust_complex/can2/src/bin/can3.rs
e2e/assets/rust_complex/can2/src/lib.rs
e2e/assets/rust_complex/dfx.json
e2e/assets/rust_complex/interface.did
e2e/tests-dfx/rust.bash
src/dfx-core/src/config/model/dfinity.rs
src/dfx/src/lib/canister_info.rs
src/dfx/src/lib/canister_info/rust.rs

Currently, dfx asks you to specify a package, and selects what it thinks is the default crate from that package. This misfires when a package contains multiple possible crates, as @sesi200 reported with the cycles ledger. This PR changes it to only assume that the default crate is the one with the same name as the package, and use a new `crate` field in dfx.json to explicitly specify non-default crates.

feat!: Change crate selection logic to use an explicit crate field

---

CHANGELOG.md
docs/extension-manifest-schema.json
e2e/tests-dfx/extension.bash
src/dfx-core/src/error/extension.rs
src/dfx-core/src/extension/manager/install.rs
src/dfx-core/src/extension/manifest/extension.rs
src/dfx-core/src/extension/url.rs
src/dfx/src/commands/extension/install.rs

dfx extension install <URL to extension.json>
Also adds download_url_template to extension.json
Fixes https://dfinity.atlassian.net/browse/SDK-1770
There is no document for `dfx extension` in https://github.com/dfinity/sdk/tree/master/docs/cli-reference, and this PR doesn't add one.
Added e2e tests

feat: install extension by url

---

CHANGELOG.md
e2e/tests-dfx/cycles-ledger.bash
e2e/tests-dfx/extension.bash
e2e/tests-dfx/ledger.bash
src/dfx-core/src/error/extension.rs
src/dfx-core/src/extension/manager/install.rs
src/dfx-core/src/extension/manager/mod.rs
src/dfx-core/src/extension/manifest/extension.rs
src/dfx-core/src/json/structure.rs
src/dfx/src/commands/extension/install.rs
src/dfx/src/lib/progress_bar.rs

`dfx extension install` (without the `--version` parameter) reports success, with a warning log, if any version of the extension is already installed.
if `--version` is passed, and the version does not match, dfx still reports an error.
Fixes https://dfinity.atlassian.net/browse/SDK-1651
Added e2e tests

fix: dfx extension install no longer reports an error if extension already installed

---

src/dfx-core/src/identity/mod.rs
src/dfx-core/src/identity/wallet.rs
src/dfx/src/commands/canister/delete.rs
src/dfx/src/commands/quickstart.rs
src/dfx/src/commands/wallet/upgrade.rs
src/dfx/src/lib/identity/wallet.rs
src/dfx/src/lib/migrate.rs

Moves two methods from dfx/src/lib to dfx-core
Preparatory work for https://dfinity.atlassian.net/browse/SDK-1483
Covered by existing tests

refactor: move wallet_canister_id to dfx-core

---

CHANGELOG.md
docs/cli-reference/dfx-canister.mdx
e2e/tests-dfx/basic-project.bash
e2e/tests-dfx/bitcoin.bash
e2e/tests-dfx/call.bash
e2e/tests-dfx/create.bash
e2e/tests-dfx/update_settings.bash
e2e/tests-dfx/wallet.bash
src/dfx-core/src/error/identity/call_sender_from_wallet.rs
src/dfx-core/src/identity/mod.rs
src/dfx/src/commands/canister/mod.rs
src/dfx/src/commands/deploy.rs

The `--wallet` parameter can now be either the principal of a wallet or the name of an identity.
If the name of an identity, dfx looks up the associated wallet's principal.
This means `--wallet <name>` is the equivalent of `--wallet $(dfx identity get-wallet --identity <name>)`.
Fixes https://dfinity.atlassian.net/browse/SDK-1483
Added e2e tests and updated existing e2e tests to use the new (shorter) form.

feat: accept --wallet <identity name> in addition to --wallet <principal>

---

src/canisters/frontend/ic-asset/src/asset/config.rs
src/canisters/frontend/ic-asset/src/error/gather_asset_descriptors.rs
src/canisters/frontend/ic-asset/src/error/get_asset_config.rs
src/dfx-core/src/config/model/canister_id_store.rs
src/dfx-core/src/config/model/dfinity.rs
src/dfx-core/src/error/cache.rs
src/dfx-core/src/error/canister_id_store.rs
src/dfx-core/src/error/config.rs
src/dfx-core/src/error/extension.rs
src/dfx-core/src/error/fs.rs
src/dfx-core/src/error/identity.rs
src/dfx-core/src/error/load_dfx_config.rs
src/dfx-core/src/error/wallet_config.rs
src/dfx-core/src/fs/composite.rs
src/dfx-core/src/fs/mod.rs
src/dfx-core/src/identity/mod.rs
src/dfx-core/src/identity/pem_safekeeping.rs
src/dfx-core/src/network/directory.rs
src/dfx/src/config/cache.rs
src/dfx/src/lib/error/project.rs
src/dfx/src/lib/identity/wallet.rs

Move some of the error types out of FsError into method-specific error types. The goal is to remove FsError altogether. 
Refactor covered by existing tests

refactor: Split up FsError into method-specific error types (partial)

---

src/dfx-core/src/config/cache.rs
src/dfx-core/src/error/cache.rs
src/dfx-core/src/error/extension.rs
src/dfx-core/src/extension/manager/execute.rs
src/dfx-core/src/extension/manager/mod.rs
src/dfx/src/commands/cache/show.rs
src/dfx/src/commands/killall.rs
src/dfx/src/config/cache.rs

Split up CacheError into method-specific error types.
Also uses `ensure_dir_exists` and renames `get_bin_cache_root` to `ensure_cache_versions_dir` because that is what it does.  I may follow up with another PR that renames some other methods that currently have similar names but subtle differences.
Covered by existing tests.

refactor: Split up CacheError into method-specific error types

---

.github/workflows/e2e.yml
.github/workflows/update-docs.yml
CHANGELOG.md
Cargo.lock
Cargo.toml
docs/extension-catalog-schema.json
e2e/tests-dfx/extension.bash
src/dfx-core/src/error/extension.rs
src/dfx-core/src/extension/catalog.rs
src/dfx-core/src/extension/manager/install.rs
src/dfx-core/src/extension/mod.rs
src/dfx-core/src/json/structure.rs
src/dfx/src/commands/extension/install.rs
src/dfx/src/commands/schema.rs

Look up location of extension.json url from /catalog.json in https://github.com/dfinity/dfx-extensions
Fixes https://dfinity.atlassian.net/browse/SDK-1796
Added an e2e test, and the `dfx extension install <extension name>` test also covers this.

feat: install extensions using the catalog

---

e2e/tests-dfx/extension.bash
src/dfx-core/src/error/extension.rs
src/dfx-core/src/extension/manager/install.rs

`dfx extension install` no longer reports `file not found` if installing an extension that does not have any subcommands.
No extensions exist like this yet, so there is nothing to note in the changelog
Added e2e tests

fix: file not found when installing an extension with no commands

---

src/dfx-core/Cargo.toml
src/dfx-core/src/config/model/local_server_descriptor.rs
src/dfx/src/lib/network/id.rs

This PR adds a new function `load_settings_digest` to fetch the settings digest from the `network-id` file in the data directory if no settings digest is set in `LocalServerDescriptor`.
The fix has been tested manually against a development version of the NNS extension.

feat: add fn load_settings_digest to load_settings_digest

---

docs/dfx-json-schema.json
docs/networks-json-schema.json
e2e/tests-dfx/frontend.bash
src/dfx-core/src/config/model/dfinity.rs
src/dfx-core/src/config/model/local_server_descriptor.rs
src/dfx/src/actors/pocketic_proxy.rs
src/dfx/src/commands/start.rs

This sets the default domain to `localhost`, so `<canister>.localhost` resumes working.

fix: Fix PocketIC domain config

---

e2e/tests-dfx/bitcoin.bash
e2e/tests-dfx/canister_http.bash

The new http gateway has some unwrap() calls instead of error checking, and panics on connect failure.  This surfaces in the two tests that this PR updates.
The result is that dfx has to restart the http gateway more than once, until it finally comes up after the replica is healthy.  Sometimes this exceeds the 15 second timeout in these tests.
The panics are fixed in https://github.com/dfinity/ic/pull/1029 but that fix will take a while to land here.
See test failures and later successes in the commits on branch https://github.com/dfinity/sdk/commits/ens/check-flaky-test/

fix: flaky test due to panic in http gateway

---

e2e/assets/rust_complex/Cargo.toml
e2e/assets/rust_deps/src/rust_deps/Cargo.toml
src/dfx/assets/project_templates/rust/src/__backend_name__/Cargo.toml

Note that the `ic-cdk` dependency of the assets canister is not updated in this PR.

chore: update rust template with ic-cdk v0.16.0

---

Cargo.lock
e2e/tests-dfx/new.bash
src/dfx-core/Cargo.toml
src/dfx-core/src/config/mod.rs
src/dfx-core/src/config/project_templates.rs
src/dfx/src/commands/new.rs
src/dfx/src/lib/project/mod.rs
src/dfx/src/lib/project/templates.rs
src/dfx/src/main.rs

Refactors the code that hands backend project templates to be data-driven rather than hardcoded as an enum.
Part of https://dfinity.atlassian.net/browse/SDK-1805
Most is covered by existing e2e.
I added two tests that show that the help and command error output still include the list of possible values. It might seem like these are just making sure that clap works, but an experiment in which I tried to make the `type` variable an `Option<ProjectTemplateName>` turned out to not show the possible values.

refactor: data-driven backend project templates

---

docs/process/release.md

It's no longer necessary to update compatibility.json in the dfx-extensions repo.  New dfx versions don't read that file.

docs: remove extension compatibility.json update from release process

---

e2e/tests-dfx/completion.bash
src/dfx-core/src/config/project_templates.rs
src/dfx/src/commands/new.rs
src/dfx/src/lib/project/templates.rs

Refactors the "frontend" and "extras" project templates to be data-driven rather than hardcoded.  This is in preparation for extensions to be able to provide project templates.
Part of https://dfinity.atlassian.net/browse/SDK-1805
Existing tests cover `dfx new` (cli and interactive).  I also tested the interactive flow manually.
Added an e2e test that verifies that the project template options show up in the completion scripts.

refactor: data-driven frontend, frontend test, and extra project templates

---

CHANGELOG.md
src/dfx/assets/project_templates/react_tests/src/__frontend_name__/package.json-patch
src/dfx/assets/project_templates/react_tests/src/__frontend_name__/src/tests/App.test.jsx
src/dfx/assets/project_templates/svelte/src/__frontend_name__/package.json
src/dfx/assets/project_templates/svelte_tests/src/__frontend_name__/package.json-patch
src/dfx/assets/project_templates/svelte_tests/src/__frontend_name__/src/tests/App.test.js
src/dfx/assets/project_templates/vanilla_js/src/__frontend_name__/package.json
src/dfx/assets/project_templates/vanilla_js_tests/src/__frontend_name__/package.json-patch
src/dfx/assets/project_templates/vue_tests/src/__frontend_name__/package.json-patch

to prevent typescript config error

fix: bumps sveltekit starter dependency versions

---

scripts/workflows/provision-darwin.sh

add `--cask` to avoid CI warnings

chore: add `--cask` in `provision-darwin.sh` when installing `mitmproxy`

---

Cargo.lock
Cargo.toml
e2e/tests-dfx/basic-project.bash
e2e/tests-dfx/request_status.bash
src/canisters/frontend/ic-asset/Cargo.toml
src/canisters/frontend/icx-asset/Cargo.toml
src/dfx-core/Cargo.toml
src/dfx/Cargo.toml
src/dfx/src/commands/canister/create.rs
src/dfx/src/commands/canister/status.rs
src/dfx/src/commands/canister/update_settings.rs

Release `ic-asset` and `icx-asset` v0.21.0.
`dfx-core` is versioned and released. And `agent-rs` dependencies are specified with versions instead of git revs.

chore: release ic(x)-asset v0.21.0

---

src/dfx/src/lib/builders/mod.rs
src/dfx/src/util/command.rs
src/dfx/src/util/mod.rs

Moves into a method functionality that either executes a command in the local directory, or wraps it in `sh -c`

refactor: direct_or_shell_command

---

src/dfx/src/lib/canister_info/rust.rs

The current crate selection logic assumes crate name == package name. This is only true for bins, not libs.
Fixes #3919

fix: Fix cdylib crate name logic

---

src/dfx-core/src/config/project_templates.rs
src/dfx/src/commands/new.rs
src/dfx/src/lib/builders/mod.rs
src/dfx/src/lib/project/templates.rs

Reworks the project template properties in preparation for extensions to be able to define them.
New properties:
- `requirements`: Other project templates that this project requires to be patched in also.   Used to patch in the base JS files.
- `post_create`: commands to execute after adding a new canister to the project, like `npm install` or `cargo update`
- `post_create_spinner_message`: some post-create commands hide their output
- `post_create_failurea_warning`: log a warning instead of aborting on error
These replace `has_js`, `update_cargo_lockfile`, and `install_node_dependencies`, which reflected the previous hard-coded behavior.
Fixes https://dfinity.atlassian.net/browse/SDK-1833
Covered by existing CI, and run manually to witness the spinners.'

refactor: project template properties

---

src/dfx/src/actors/pocketic.rs

Unlike fiduciary and bitcoin subnet (or a regular application subnet), PocketIC cannot create the II subnet dynamically (when needed) because the II subnet has been split out of the NNS subnet and PocketIC does not support dynamic subnet creation of subnets that have been split.

fix: create II subnet when using PocketIC

---

.github/workflows/publish.yml
e2e/tests-dfx/create.bash
src/dfx-core/src/config/model/replica_config.rs
src/dfx/src/actors/mod.rs
src/dfx/src/actors/pocketic.rs
src/dfx/src/commands/start.rs
src/dfx/src/lib/environment.rs

This PR fetches the effective canister id from the PocketIC topology instead of using a hard-coded canister id. The motivation for this fix is that changes to the PocketIC topology (e.g., adding a new subnet) might render the hard-coded canister id not belong to the expected subnet.
A new bash test has been added.

fix: fetch effective canister id from PocketIC topology

---

src/dfx/src/commands/canister/status.rs

The field was missed in the canister status output.

fix: Add `idle_cycles_burned_per_day` field

---

docs/cli-reference/dfx-identity.mdx
src/dfx/src/commands/identity/import.rs

`dfx identity --help` only shows PEM file imports for `dfx identity import` but is actually also capable of handling seed phrase files as well

chore: update command comment

---

CHANGELOG.md
e2e/tests-dfx/error_context.bash
src/dfx/src/lib/diagnosis.rs

The current error message for a non-running local replica is not great:
```
Error: Failed while waiting for agent status.
Caused by: An error happened during communication with the replica: error sending request for url (http://127.0.0.1:4943/api/v2/status)
Caused by: error sending request for url (http://127.0.0.1:4943/api/v2/status)
Caused by: client error (Connect)
Caused by: tcp connect error: Connection refused (os error 61)
Caused by: Connection refused (os error 61)
```
This PR adds a nice message explaining in understandable words what the problem is and what to do.
added e2e, some manual testing

chore: improve error message when local replica not running

---

src/dfx-core/src/config/cache.rs
src/dfx-core/src/error/cache.rs
src/dfx-core/src/error/interface.rs
src/dfx-core/src/error/mod.rs
src/dfx-core/src/interface/builder.rs

`DfxInterfaceBuilder::build` loads dfx.json. If dfx.json has a canister with a type defined by an extension, then it's necessary to provide an ExtensionManager, otherwise the loader won't recognize the canister's `type`.
This adds methods to DfxInterfaceBuilder, as well as a standalone method for extracting the dfx version from the dfx cache path.
Required for https://dfinity.atlassian.net/browse/SDK-1832
Tested in https://github.com/dfinity/dfx-extensions/pull/153

feat: DfxInterfaceBuilder can provide extension manager

---

Cargo.lock
src/dfx-core/CHANGELOG.md
src/dfx-core/Cargo.toml

Adds methods needed to load dfx.json when an extension defines a canister type referenced by the project.

chore: release dfx-core 0.1.1

---

CHANGELOG.md
docs/cli-reference/dfx-envars.mdx
e2e/tests-dfx/generate.bash
e2e/tests-dfx/playground.bash
src/dfx/src/commands/generate.rs
src/dfx/src/lib/network/network_opt.rs

The `prebuild` step in all of the default projects is `dfx generate`. Since no `--network` parameter was provided, the generate step happens for the `local` network. When deploying with `dfx deploy --playground`, this would only work if at least `dfx build` (to the local network) had been run previously.
This PR makes all commands look for the `DFX_NETWORK` parameter if no `--network` parameter was passed.
Fixes:
- https://dfinity.atlassian.net/browse/SDK-1882
- https://dfinity.atlassian.net/browse/SDK-1860
- https://dfinity.atlassian.net/browse/SDK-1605
Added an e2e test and tested manually.

fix: dfx deploy to the playground fails for a fresh project; CLI reads DFX_NETWORK

---

e2e/tests-dfx/cycles-ledger.bash
e2e/tests-dfx/extension.bash

Adds a test that `dfx nns install` works if dfx.json has a canister with a type defined in an extension. Related: https://github.com/dfinity/dfx-extensions/pull/153
Also use a newer nns extension version.
Part of https://dfinity.atlassian.net/browse/SDK-1832

test: extension commands with extension defined canister type

---

Cargo.lock
src/dfx/Cargo.toml
src/dfx/src/util/mod.rs

This PR fixes errors of the form
```
$ dfx start --clean
Running dfx start for version 0.24.2+rev23.dirty-3b68fe37
Using project-specific network 'local' defined in /home/martin/orbit/dfx.json
Error: Failed to get frontend address.
Caused by: Failed to find available socket address
Caused by: Failed to bind socket to 127.0.0.1:4943.
Caused by: Address already in use (os error 98)
```
observed when restarting dfx shortly after browsing a frontend canister making periodic background requests and stopping dfx.
It has been manually confirmed to fix the issue on Ubuntu 24.04.1 LTS.

fix: address already in use error in dfx start

---

CHANGELOG.md
e2e/tests-dfx/canister_url.bash
e2e/tests-dfx/fabricate_cycles.bash
e2e/tests-dfx/identity.bash
e2e/tests-dfx/network.bash
e2e/tests-dfx/sign_send.bash
src/dfx/src/lib/environment.rs

SDK-1904
This used to be a warning. A hard error can abort the command so that no insecure state will be on the mainnet.
Users can surpress this error by setting `export DFX_WARNING=-mainnet_plaintext_identity`.
The warning won't display when executing commands like `dfx deploy --playground`.
```
$ dfx deploy --ic
Error: Failed to create AgentEnvironment.
Caused by: Failed to create AgentEnvironment for network 'ic'.
Caused by: The default identity is not stored securely. Do not use it to control a lot of cycles/ICP.
- For enhanced security, create a new identity using the command:
dfx identity new
Then, specify the new identity in mainnet-facing commands with the --identity flag.
- If you understand the risks and still wish to use the insecure plaintext identity, you can suppress this …
```

feat: error when using insecure identity on mainnet

---

src/dfx/src/actors/pocketic_proxy.rs

This PR stops the HTTP gateway gracefully by sending a shutdown request to the PocketIC server before killing the server process.

chore: stop HTTP gateway gracefully

---

docs/cli-reference/dfx-cycles.mdx

Copy/paste fail when creating docs for `dfx cycles convert --deposit-memo`. Also adding some missing links

chore: fix dfx cycles convert docs

---

src/dfx-core/src/config/model/mod.rs
src/dfx-core/src/config/model/project_template.rs
src/dfx-core/src/config/project_templates.rs
src/dfx/src/commands/new.rs
src/dfx/src/lib/project/templates.rs

Moves the `Category` type into the config/model package, next to other types serialized from JSON. This will reduce the changes in https://github.com/dfinity/sdk/pull/4012.

refactor: Category to ProjectTemplateCategory

---

src/dfx-core/src/config/model/local_server_descriptor.rs
src/dfx/src/commands/start.rs

Removes a parameter that is always passes as `None`. The now-deleted `dfx replica` command used to pass Some(port).
Then removes the resulting dead code.
Refactor covered by CI

refactor: remove dead code

---

CHANGELOG.md
e2e/tests-dfx/cycles-ledger.bash
src/dfx/src/lib/diagnosis.rs

If users run `dfx deploy` without enough cycles, show additional messages to indicate what to do next.
```
Error explanation:
Insufficient cycles balance to create the canister.
How to resolve the error:
Please top up your cycles balance by converting ICP to cycles like below:
'dfx cycles convert --amount=0.123 --ic'.
```
[SDK-1867](https://dfinity.atlassian.net/browse/SDK-1867)
Tested manually.
[SDK-1867]: https://dfinity.atlassian.net/browse/SDK-1867?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: improve error message for 'dfx deploy'.

---

Cargo.lock
deny.toml
docs/dfx-json-schema.json
docs/networks-json-schema.json
docs/process/release.md
e2e/tests-dfx/assetscanister.bash
e2e/tests-icx-asset/icx-asset.bash
rust-toolchain.toml
src/canisters/frontend/ic-asset/src/asset/config.rs
src/dfx/src/lib/deps/mod.rs
src/dfx/src/lib/deps/pull/mod.rs
src/dfx/src/lib/environment.rs
src/dfx/src/lib/manifest.rs

We had it happen multiple times that we promoted a dfx version where `dfx deploy --playground` does not work because the updated allowlist was not deployed in time. With this new check we can make sure this doesn't happen again.

chore(docs): add manual allowlist check to promote runbook

---

CHANGELOG.md
src/dfx/src/lib/operations/canister/motoko_playground.rs

When we forget to allowlist the latest frontend canister wasm to the playground backend the error message is incomprehensible to users:
```
Error: Failed while trying to deploy canisters.
Caused by: Failed while trying to install all canisters.
Caused by: Failed to install wasm module to canister 'ii_integration_frontend'.
Caused by: install failed
Caused by: The replica returned a rejection error: reject code CanisterReject, reject message IC0503: Error from Canister ozk6r-tyaaa-aaaab-qab4a-cai: Canister called `ic0.trap` with message: Wasm is not whitelisted.
Consider gracefully handling failures from this canister or altering the canister to handle exceptions. See documentation: http://internetcomputer.org/docs/current/references/execution-errors#trapped-explicitly, error code None
``` …

chore: improve error message when asset wasm is not allowlisted in playground

---

CHANGELOG.md
e2e/tests-dfx/assetscanister.bash
src/canisters/frontend/ic-asset/src/batch_upload/plumbing.rs
src/canisters/frontend/ic-asset/src/evidence/mod.rs
src/canisters/frontend/ic-asset/src/sync.rs
src/canisters/frontend/ic-asset/src/upload.rs

`dfx deploy` now tries to pack content encoding data into the CommitBatch arguments, in order to streamline deploys for smaller projects.  Larger deploys split up synchronization operations into multiple batches, in order to avoid exceeding message size or computation limits.
However, the above also applied to `dfx deploy --by-proposal`, which has to submit all synchronization operations in the same ProposeCommitBatchArguments.  Including asset contents increases the changes of exceeding message size limits.
This PR makes `dfx deploy --by-proposal` never include asset content in the ProposeCommitBatchArguments, instead uploading all contents with create_chunk or create_chunks.
Fixes https://dfinity.atlassian.net/browse/SDK-1914

fix: fix: dfx deploy --by-proposal no longer sends chunk data in ProposeCommitBatch

---

scripts/update-replica.sh

This PR fixes the update-replica.sh script to also support commits starting with a digit. Previously, the expression `\1$SHA\2` where `$SHA` gets substituted for `3e24396441e4c7380928d4e8b4ccff7de77d0e7e` (for instance) would be [interpreted](https://github.com/dfinity/sdk/actions/runs/12389699213/job/34583240855) as `\13` followed by `e24396441e4c7380928d4e8b4ccff7de77d0e7e` and `\2` instead of `\1` followed by `e24396441e4c7380928d4e8b4ccff7de77d0e7e` and `\2`.
The new perl command has been tested manually on Ubuntu 24.04.1 LTS and perl5 (revision 5 version 38 subversion 2).

fix: update-replica.sh for commit starting with digit

---

e2e/tests-dfx/request_status.bash

We have a test for `dfx canister request-status`, but not one that shows the identity must match the one used with `dfx canister call`.

test: add e2e test for canister request-status with different identity

---

Cargo.lock
Cargo.toml
src/dfx-core/src/error/keyring.rs
src/dfx-core/src/identity/keyring_mock.rs

This PR updates the dependency `keyring` to version 3, from version 1.2 before.
Having such an old version of keyring was causing the SDK to have duplicate versions of many dependencies, because the old version of keyring was pulling in old versions of lots of other libraries. 
For example, previously the SDK was depending on rustix 0.37 as well as rustix 0.38. It was also depending on two versions of cipher, two versions of aes, two versions of hmac, two versions of proc-macro-crate, two versions of toml, two versions of socket2, two versions of async-lock, two versions of fastrand, and two versions of nix. 
After this PR, the SDK will only depend on one version of each of these libraries. This will speed up build times and probably make the binary slightly smaller. At least, I think it …

chore: update `keyring` to version 3

---

src/dfx-core/src/extension/manifest/extension.rs

There was recently an [addition](https://github.com/dfinity/sdk/commit/e05c888d5652832c8c4bb9fbd7b736d21144443d#diff-f9f700123e62eca450ee9933de6c11203dd9ba7a0adabc28f2cee52e0434a38dR40) of `pub project_templates: Option<HashMap<String, ExtensionProjectTemplate>>`  to the struct `ExtensionManifest`.
This is somewhat problematic on its own because `ExtensionManifest` has `#[serde(deny_unknown_fields)]`. So any extension that has this field in its manifest won’t be compatible with any version of DFX that was released prior to this field being added. 
This lack of backwards-compatibility might be desirable for extensions that declare project templates (since old versions of DFX wouldn't support the extension's whole feature set). But extensions that don't declare project templates should …

fix: make extensions that don't use project templates backwards-compatible

---

e2e/tests-dfx/bitcoin.bash
e2e/tests-dfx/canister_http_adapter.bash
e2e/tests-dfx/create.bash
e2e/tests-dfx/cycles-ledger.bash
e2e/tests-dfx/deps.bash
e2e/tests-dfx/start.bash
src/dfx-core/src/config/model/dfinity.rs
src/dfx/src/actors/pocketic.rs

Tests specifically about the behavior of the bitcoin and outcalls HTTP adapter remain replica-only since those are implementation details. create.bash#4 remains replica-only since it relies on subnets not existing and canister IDs being freeform. Everything else now works with PocketIC after adding a fiduciary subnet.

chore: remove remaining pocketic test exclusions

---

CHANGELOG.md
src/dfx/src/commands/canister/status.rs

Provides units for all fields of canister status.
Before
```bash
$ dfx canister status  pxmfj-jaaaa-aaaan-qmmbq-cai --ic
Canister status call result for pxmfj-jaaaa-aaaan-qmmbq-cai.
Status: Running
Controllers: uom2z-lqsqq-qbn4p-nts4l-2xjfl-oeivu-oso42-4t4jh-54ikd-ewnvi-tqe yjac5-2yaaa-aaaan-qaqka-cai
Memory allocation: 0
Compute allocation: 0
Freezing threshold: 2_592_000
Idle cycles burned per day: 20_548_135
Memory Size: Nat(2010735)
Balance: 2_985_413_617_008 Cycles
Reserved: 0 Cycles
Reserved cycles limit: 5_000_000_000_000 Cycles
Wasm memory limit: 3_221_225_472 Bytes
Wasm memory threshold: 0 Bytes
Module hash: 0x4f13cceb571483ac99a9f89afc05718c0a4ab72e9fac7d49054c0a3e05c4899b
Number of queries: 0
Instructions spent in queries: 0
Total query request payload size (bytes): 0
Total …
```

chore: provides units for all fields of canister status.

---

.github/workflows/e2e.yml
CHANGELOG.md
e2e/playwright/tests/react.spec.ts
e2e/playwright/tests/vanilla.spec.ts
e2e/playwright/tests/vue.spec.ts

Extends playwright coverage to the remaining frontend projects
Fixes SDK-1931
It's all tests!

test: adds playwright tests for `dfx new` project frontends

---

CHANGELOG.md
src/dfx/assets/project_templates/svelte/src/__frontend_name__/package.json

We were encountering build failures on the sveltekit starter, and this will both improve the build process and and unblock CI

fix: removes unnecessary tsc step in sveltekit build script

---

e2e/tests-dfx/wallet.bash

Add an e2e test for canister_info.
Added a test only.

chore: add an e2e test for canister_info.

---

src/dfx/src/lib/diagnosis.rs

The compatibility code for old replicas produced a misleading message on unrelated 403s. Fortunately old replicas probably do not exist.

fix: Change 'controller of canister' error explanation to only use error code

---

CHANGELOG.md
e2e/tests-dfx/install.bash
src/dfx/src/lib/operations/canister/install_canister.rs

When running `dfx deploy --no-asset-upgrade` or `dfx canister install --no-asset-upgrade` on an asset canister that is not up to date then dfx hangs forever with `Waiting for module change to be reflected in system state tree...`
Example:
```
% dfx deploy --ic --no-asset-upgrade
Deploying all canisters.
All canisters have already been created.
Building canisters...
[...]
Installing canisters...
Upgrading code for canister fe-app, with canister ID <id>
Waiting for module change to be reflected in system state tree...
Waiting for module change to be reflected in system state tree...
Waiting for module change to be reflected in system state tree...
[keeps waiting forever]
```
The problem was that dfx waited for the new wasm hash to show up in the state tree even if the new wasm was not …

fix: --no-asset-upgrade hangs forever

---

src/dfx/src/lib/logger.rs

Even with `self.spinners.suspend(|| self.inner.log(record, values))`, spinner and log outputs would sometimes intermix. dfx doesn't have high-volume logging, so this PR changes stderr logging to use sync logging.
Tested on another branch that makes more use of progress bars + logging

fix: spinners and log output no longer intermix

---

CHANGELOG.md
e2e/tests-dfx/assetscanister.bash
src/canisters/frontend/ic-asset/src/batch_upload/plumbing.rs
src/canisters/frontend/ic-asset/src/canister_api/methods/asset_properties.rs
src/canisters/frontend/ic-asset/src/canister_api/methods/chunk.rs
src/canisters/frontend/ic-asset/src/evidence/mod.rs
src/canisters/frontend/ic-asset/src/lib.rs
src/canisters/frontend/ic-asset/src/progress.rs
src/canisters/frontend/ic-asset/src/sync.rs
src/canisters/frontend/ic-asset/src/upload.rs
src/canisters/frontend/icx-asset/src/commands/sync.rs
src/canisters/frontend/icx-asset/src/commands/upload.rs
src/dfx-core/src/progress/mod.rs
src/dfx/src/actors/mod.rs
src/dfx/src/lib/installers/assets/mod.rs
src/dfx/src/lib/mod.rs
src/dfx/src/lib/operations/canister/deploy_canisters.rs
src/dfx/src/lib/operations/canister/install_canister.rs
src/dfx/src/lib/progress/asset_sync_progress_renderer.rs
src/dfx/src/lib/progress/mod.rs

Added spinners to reflect asset synchronization progress. Changed logging from info to debug.
Fixes: https://dfinity.atlassian.net/browse/SDK-1944
Now the output looks like this (while assets are being uploaded)
```
dfx deploy
Deploying all canisters.
Creating canisters...
Created a wallet canister on the "local" network for user "default" with ID "bnz7o-iuaaa-aaaaa-qaaaa-cai"
scraped-portal-backend canister created with canister id: bkyz2-fmaaa-aaaaa-qaaaq-cai
scraped-portal-frontend canister created with canister id: bd3sg-teaaa-aaaaa-qaaba-cai
Building canisters...
Installing canisters...
Creating UI canister on the local network.
The UI canister on the "local" network is "be2us-64aaa-aaaaa-qaabq-cai"
Installing code for canister scraped-portal-backend, with canister ID …
```

feat: progress bars for asset upload

---

CHANGELOG.md
e2e/assets/remote/download_did/canister_ids.json
e2e/assets/remote/download_did/dfx.json
e2e/assets/remote/download_did/main.mo
e2e/tests-dfx/remote.bash
src/dfx/src/lib/models/canister.rs

If `canisters.<dependency canister>.candid` is a URL and `canisters.<dependency canister>.remote.candid` is `null`, then `dfx build` failed when the project was not first built for a non-remote network because the candid file was not properly downloaded.
Fixes [SDK-1793](https://dfinity.atlassian.net/browse/SDK-1793)
added e2e
[SDK-1793]: https://dfinity.atlassian.net/browse/SDK-1793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: download remote did files

---

CHANGELOG.md
docs/dfx-json-schema.json
e2e/tests-dfx/build_rust.bash
src/dfx-core/src/config/model/dfinity.rs
src/dfx/src/lib/canister_info.rs
src/dfx/src/lib/canister_info/rust.rs
src/dfx/src/lib/models/canister.rs

Adds a dfx.json field `skip_cargo_audit`. Resolves SDK-1450

feat: Allow disabling cargo-audit

---

src/dfx/src/lib/named_canister.rs

Display a spinner when creating/installing the Candid UI canister, and log about it to debug, not info.
Part of https://dfinity.atlassian.net/browse/SDK-1944
Tested locally

feat: add spinner for Candid UI canister creation

---

src/dfx/src/lib/operations/canister/install_canister.rs

When deploying to the playground we cannot verify the wasm hash because the playground may change the wasm before deploying. Clarify the message and show it only in verbose mode.
Fixes # SDK-1898
```
❯ ddfx deploy --playground
WARN: Canister 'hello_backend' has timed out.
Deploying all canisters.
Reserving canisters in playground...
Reserved canister 'hello_backend' with id 7gngh-jqaaa-aaaab-qacvq-cai with the playground.
Building canisters...
Installing canisters...
Installing code for canister hello_backend, with canister ID 7gngh-jqaaa-aaaab-qacvq-cai
Deployed canisters.
URLs:
Backend canister via Candid interface:
hello_backend: https://a4gq6-oaaaa-aaaab-qaa4q-cai.raw.icp0.io/?id=7gngh-jqaaa-aaaab-qacvq-cai
❯ ddfx deploy --playground --verbose
Deploying all canisters.
All canisters …
```

chore: clarify log message when deploying to playground

---

e2e/tests-dfx/assetscanister.bash

A while back the asset canister did not handle special characters in file names correctly. This was recorded in e2e tests and recorder for follow-up in SDK-1247/1420. The behavior was fixed in #3767. This PR now updates the tests to demonstrate more clearly that special characters are handled properly.
Fixes [SDK-1420](https://dfinity.atlassian.net/browse/SDK-1420)
Updated e2e tests to demonstrate correct behavior
[SDK-1420]: https://dfinity.atlassian.net/browse/SDK-1420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update tests to show asset canister properly handles special chars

---

e2e/tests-dfx/assetscanister.bash
e2e/tests-dfx/error_context.bash
src/canisters/frontend/ic-asset/src/sync.rs
src/dfx/src/commands/deploy.rs
src/dfx/src/lib/builders/assets.rs

- Removes the 'Unhardened assets: all' line
- Reorders the URLs to clarify importance
- Prints a better error message when NPM is missing
SDK-1890, SDK-1893, SDK-1899

chore: Misc output changes

---

CHANGELOG.md
src/dfx/src/commands/cycles/balance.rs

docs: fix dfx cycles balance description

---

.github/workflows/deny.yml

The license check in CI started failing today. Example: https://github.com/dfinity/sdk/actions/runs/13636726972/job/38121248105?pr=4126
I tried running the command that it asked for, but it didn't help, probably because it's running in a docker container. I tried the v2 action and configuring it to use the rust version that it's used to, but rust-toolchain.toml still overrode it.
This PR removes rust-toolchain.toml when the deny workflow runs so that the workflow can run with what it needs.

fix: cargo-deny failure due to toolchain not installed

---

.github/workflows/e2e.yml
.github/workflows/publish.yml
scripts/test-uis.py
scripts/workflows/e2e-matrix.py

`ubuntu-20.04` runners are getting deprecated: https://github.com/actions/runner-images/issues/11101

chore: bump ubuntu

---

.github/workflows/e2e.yml
CHANGELOG.md
CONTRIBUTING.md
e2e/assets/expect_scripts/ctrl_c_right_after_dfx_start.exp
e2e/tests-dfx/bitcoin.bash
e2e/tests-dfx/call.bash
e2e/tests-dfx/create.bash
e2e/tests-dfx/info.bash
e2e/tests-dfx/ledger.bash
e2e/tests-dfx/playground.bash
e2e/tests-dfx/start.bash
e2e/utils/_.bash
src/dfx-core/src/config/model/settings_digest.rs
src/dfx/src/commands/start.rs

As [announced](https://forum.dfinity.org/t/dfx-replacing-the-local-replica-with-pocketic/40167) `dfx start` now runs PocketIC by default.
Running a local replica is still possible with `--replica`, but this option will be removed in the near future.
Fixes [SDK-1989](https://dfinity.atlassian.net/browse/SDK-1989)
Covered by e2e
[SDK-1989]: https://dfinity.atlassian.net/browse/SDK-1989?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat!: default to PocketIC

---

CHANGELOG.md
src/canisters/frontend/ic-asset/src/error/gather_asset_descriptors.rs
src/canisters/frontend/ic-asset/src/sync.rs

When using unhardened security policies dfx incorrectly prints
```
WARN: This project uses the default security policy for all assets. While it is set up to work with many applications, it is recommended to further harden the policy to increase security against attacks like XSS.
WARN: To get started, have a look at 'dfx info canister-security-policy'. It shows the default security policy along with suggestions on how to improve it.
```
It should recommend `dfx info security-policy` instead.
tested manually

fix: properly suggest `dfx info security-policy`

---

src/dfx-core/src/config/project_templates.rs
src/dfx/src/lib/mod.rs
src/dfx/src/lib/telemetry.rs
src/dfx/src/main.rs

Uses the clap CliOpts to get the subcommand and sanitized arguments and save them for later reporting.
While some methods in the Telemetry impl may return a Result, my intent is that the caller will ignore them, as seen in the call from main. The idea is that telemetry shouldn't interfere with what the user is doing.
Fixes https://dfinity.atlassian.net/browse/SDK-1961
Added unit tests

feat: store sanitized command-line for telemetry

---

CHANGELOG.md
docs/cli-reference/dfx-info.mdx
e2e/tests-dfx/info.bash
src/dfx/src/commands/info/mod.rs
src/dfx/src/lib/telemetry.rs

`dfx info telemetry-log-path` reports the path to the telemetry log file.
Fixes https://dfinity.atlassian.net/browse/SDK-1979

feat: add dfx info telemetry-log-path

---

CHANGELOG.md
e2e/tests-dfx/cycles-ledger.bash
src/dfx/src/lib/operations/canister/create_canister.rs

Updated the canister creation fee to `500B` cycles as [documented](https://internetcomputer.org/docs/building-apps/essentials/gas-cost#cycles-price-breakdown).
Please check the [forum post](https://forum.dfinity.org/t/evaluating-compute-pricing-in-response-to-increased-demand-on-the-internet-computer-protocol/36565) for more info.

chore: updated the canister creation fee to 500B cycles.

---

CHANGELOG.md
docs/cli-reference/dfx-ledger.mdx
e2e/tests-dfx/ledger.bash
src/dfx/src/commands/ledger/allowance.rs
src/dfx/src/commands/ledger/mod.rs
src/dfx/src/lib/operations/ledger.rs

Implement `dfx ledger allowance` that complies with the [ICRC2 standard](https://github.com/dfinity/ICRC-1/blob/main/standards/ICRC-2/ICRC-2.did).
[SDK-2026](https://dfinity.atlassian.net/browse/SDK-2026)
E2E tests.
[SDK-2026]: https://dfinity.atlassian.net/browse/SDK-2026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Implement `dfx ledger allowance`.

---

docs/cli-reference/dfx-generate.mdx

Update the description of the output folder of `dfx generate` to notify users not to put their own files under the output folder. We [delete the output folder](https://github.com/dfinity/sdk/blob/master/src/dfx/src/lib/builders/mod.rs#L128) before generating the binding files.
[SDK-1435](https://dfinity.atlassian.net/browse/SDK-1435)
Only document change.
[SDK-1435]: https://dfinity.atlassian.net/browse/SDK-1435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update description of the output folder of 'dfx generate'.

---

Cargo.lock
src/dfx-core/src/config/model/canister_id_store.rs
src/dfx/Cargo.toml
src/dfx/src/commands/canister/delete.rs
src/dfx/src/commands/canister/install.rs
src/dfx/src/commands/canister/update_settings.rs
src/dfx/src/commands/canister/url.rs
src/dfx/src/lib/environment.rs
src/dfx/src/lib/models/canister.rs
src/dfx/src/lib/named_canister.rs
src/dfx/src/lib/operations/canister/create_canister.rs
src/dfx/src/lib/operations/canister/deploy_canisters.rs
src/dfx/src/lib/operations/canister/install_canister.rs
src/dfx/src/lib/operations/canister/motoko_playground.rs

CanisterIdStore is a handle to global state via every mutating method saving to the file system, but still presents as a data structure it's meaningful to create a new instance of. This PR changes it to a property of Environment instead of something you create.

chore: convert CanisterIdStore to a global

---

Cargo.toml
src/canisters/frontend/ic-asset/src/asset/config.rs
src/canisters/frontend/ic-asset/src/error/assemble_commit_batch_argument.rs
src/canisters/frontend/ic-asset/src/error/compute_evidence.rs
src/canisters/frontend/ic-asset/src/error/create_chunk.rs
src/canisters/frontend/ic-asset/src/error/create_encoding.rs
src/canisters/frontend/ic-asset/src/error/create_project_asset.rs
src/canisters/frontend/ic-asset/src/error/gather_asset_descriptors.rs
src/canisters/frontend/ic-asset/src/error/get_asset_properties.rs
src/canisters/frontend/ic-asset/src/error/hash_content.rs
src/canisters/frontend/ic-asset/src/error/load_config.rs
src/canisters/frontend/ic-asset/src/error/load_rule.rs
src/canisters/frontend/ic-asset/src/error/prepare_sync_for_proposal.rs
src/canisters/frontend/ic-asset/src/error/sync.rs
src/canisters/frontend/ic-asset/src/error/upload.rs
src/canisters/frontend/ic-asset/src/error/upload_content.rs
src/dfx-core/Cargo.toml
src/dfx-core/src/error/encryption.rs

ic-asset was missing agent errors, and dfx-core was missing crypto errors. Also removed `{}` formatting of source errors per [this comment](<https://github.com/dfinity/sdk/pull/4149#discussion_r2004352895>).

chore: Add source information to all errors

---

Cargo.lock
Cargo.toml

See failures here: https://github.com/dfinity/sdk/actions/runs/13980704355?pr=4162

fix: Update to ring 0.17.14 for cargo audit

---

CHANGELOG.md
src/dfx/src/lib/telemetry.rs

Send telemetry every 2-4 days.
For betas, send telemetry every day +/- 6 hours.
Also added a changelog entry for the whole thing.
```
$ rm send-time.txt ; dfx --version ; dfx cache show ; cat send-time.txt
dfx 0.87.1
/Users/ericswanson/.cache/dfinity/versions/0.87.1
2025-03-23 18:23:25
$ rm send-time.txt ; dfx --version ; dfx cache show ; cat send-time.txt
dfx 0.87.1
/Users/ericswanson/.cache/dfinity/versions/0.87.1
2025-03-23 22:35:32
$ rm send-time.txt ; dfx --version ; dfx cache show ; cat send-time.txt
dfx 0.87.1
/Users/ericswanson/.cache/dfinity/versions/0.87.1
2025-03-22 15:28:15
$ rm send-time.txt ; dfx --version ; dfx cache show ; cat send-time.txt
dfx 0.87.1-beta.1
/Users/ericswanson/.cache/dfinity/versions/0.87.1-beta.1
2025-03-21 10:49:11
$ rm send-time.txt ; dfx --version ; …
```

feat: shorten time to report telemetry, esp for betas

---

CHANGELOG.md

Includes everything up to (#4164)

chore: Add the 0.26.0 header to the changelog

---

CHANGELOG.md
docs/cli-reference/dfx-ledger.mdx
e2e/tests-dfx/ledger.bash
src/dfx/src/commands/ledger/allowance.rs
src/dfx/src/commands/ledger/approve.rs
src/dfx/src/commands/ledger/balance.rs
src/dfx/src/commands/ledger/show_subnet_types.rs
src/dfx/src/commands/ledger/transfer.rs
src/dfx/src/commands/ledger/transfer_from.rs
src/dfx/src/lib/operations/cycles_ledger.rs
src/dfx/src/lib/operations/ledger.rs
src/dfx/src/lib/operations/mod.rs

Extend `dfx ledger transfer` and `dfx ledger balance` to support [ICRC1 standard](https://github.com/dfinity/ICRC-1/tree/main/standards/ICRC-1).
[SDK-2014](https://dfinity.atlassian.net/browse/SDK-2014)
[SDK-2016](https://dfinity.atlassian.net/browse/SDK-2016)
Covered by e2e tests.
[SDK-2014]: https://dfinity.atlassian.net/browse/SDK-2014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SDK-2016]: https://dfinity.atlassian.net/browse/SDK-2016?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Extend `dfx ledger transfer` and `dfx ledger balance` to support ICRC1 standard

---

CHANGELOG.md
src/dfx/src/lib/ledger_types/mod.rs
src/dfx/src/lib/operations/ledger.rs

Use the [account_balance](https://github.com/dfinity/ic/blob/master/rs/ledger_suite/icp/ledger.did#L489) rather than the legacy [account_balance_dfx](https://github.com/dfinity/ic/blob/master/rs/ledger_suite/icp/ledger.did#L516) on the ICP ledger.
[SDK-2053](https://dfinity.atlassian.net/browse/SDK-2053)
Covered by the current e2e tests.
[SDK-2053]: https://dfinity.atlassian.net/browse/SDK-2053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: use 'account_balance' instead of the legacy 'account_balance_dfx'.

---

src/dfx-core/src/config/directories.rs
src/dfx-core/src/error/config.rs
src/dfx-core/src/error/identity.rs
src/dfx-core/src/error/network_config.rs
src/dfx-core/src/network/provider.rs

This PR refactors one method to return a method-specific error type, for the only error that can occur, rather than `ConfigError`, which could indicate many things.
Made here in order to make an upcoming PR slightly smaller.
refactor covered by CI

refactor: error return for get_shared_network_data_directory

---

CHANGELOG.md
e2e/tests-dfx/error_context.bash
e2e/tests-dfx/network.bash
e2e/tests-dfx/project_local_network.bash
e2e/tests-dfx/wallet.bash
e2e/utils/_.bash
src/dfx-core/src/config/directories.rs
src/dfx-core/src/config/model/network_descriptor.rs
src/dfx-core/src/error/config.rs
src/dfx-core/src/error/identity.rs
src/dfx-core/src/error/network_config.rs
src/dfx-core/src/error/wallet_config.rs
src/dfx-core/src/identity/mod.rs
src/dfx-core/src/identity/wallet.rs
src/dfx-core/src/network/provider.rs

For the local shared network, `dfx start` stores replica state in a subdirectory based on the configuration of that backend. dfx wasn't storing `wallets.json` in this subdirectory, which meant that when changing settings, dfx would try to use a wallet canister that didn't exist.
This change puts wallets.json in the same subdirectory as the rest of the backend state. 
Fixes https://dfinity.atlassian.net/browse/SDK-1918
I put the changelog entry in the 0.26.0 section because I will port this to the release branch after CR approval here.

fix: store wallets.json with backend data files

---

CHANGELOG.md
docs/cli-reference/dfx-canister.mdx
e2e/tests-dfx/id.bash
src/dfx/src/commands/canister/mod.rs
src/dfx/src/commands/canister/set_id.rs

Added the counterpart to `dfx canister id <canister name>`. Networks can be targeted as usual using `--network <network name>` or the `--ic` shorthand for mainnet.
Requested through DMs, and answers the occasional forum question where people ask how to set a specific canister id after creating a canister through NNS dapp.
Added e2e

feat: dfx canister set-id

---

CHANGELOG.md
e2e/tests-dfx/project_local_network.bash
src/dfx-core/src/network/directory.rs

After editing dfx.json to define a local network, dfx would try to continue to reuse canister ids defined for the shared network. This would cause errors since those canisters most likely did not exist.
This PR deletes the .dfx directory if the configuration changes from using the shared local network to the project network.
Fixes https://dfinity.atlassian.net/browse/SDK-2062

fix: clear state when switching from shared to project network

---

.github/workflows/e2e.yml
scripts/workflows/e2e-matrix.py

Only run selected tests on macos, and also use the `macos-13` runners.
Fixes https://dfinity.atlassian.net/browse/SDK-2067

test: run fewer tests on macos

---

CHANGELOG.md

Fixed the wrong place for the changelog introduced by merging.

chore: fix the wrong place for the changelog.

---

CHANGELOG.md
docs/cli-reference/dfx-canister.mdx
src/dfx/src/commands/canister/logs.rs

Support `follow` mode for 'dfx canister logs':
- `--follow` to enable the follow mode, which keeps fetching the logs continuously.
- `--interval` to set the interval.
[SDK-2069](https://dfinity.atlassian.net/browse/SDK-2069)
- Unit test added.
- Manually tested locally.
- Cannot find an elegant way to test in the e2e test framework.
[SDK-2069]: https://dfinity.atlassian.net/browse/SDK-2069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Support `follow` mode for 'dfx canister logs'.

---

src/dfx/src/actors/mod.rs
src/dfx/src/actors/pocketic.rs
src/dfx/src/actors/pocketic_proxy.rs

This PR uses the CLI argument `--log-levels` instead of the environment variable `RUST_LOG` when starting the PocketIC server. The motivation for this change is that `RUST_LOG` also affects the log level for the replica (specified [separately](https://github.com/dfinity/sdk/blob/a026b45e227c0622717e0e1060d97a16cf5e3b4c/src/dfx/src/actors/pocketic.rs#L377)) and that `RUST_LOG` might be ignored in a future PocketIC release (see this [PR](https://github.com/dfinity/ic/pull/4897)).

fix: do not use RUST_LOG to configure PocketIC

---

.github/workflows/bitcoin-canister-update.yml
.github/workflows/broadcast-frontend-hash.yml
.github/workflows/update-motoko.yml
.github/workflows/update-replica-version.yml

The `dfinity-bot` got removed form GitHub. The GitHub actions in the sdk repo authenticated as this bot using the `NIV_UPDATER_TOKEN` secret which means that these actions will break.
We're switching all repos to use [actions/create-github-app-token](https://github.com/actions/create-github-app-token) because it's more secure.

chore: replace secrets.NIV_UPDATER_TOKEN with actions/create-github-app-token

---

docs/cli-reference/dfx-canister.mdx

Fixed the document for canister snapshot with `--replace` option as it will return a new snapshot ID.

docs: fixed the document for canister snapshot with '--replace' option.

---

Cargo.lock

Fix the new cargo audit alert: https://github.com/dfinity/sdk/actions/runs/16911283256

fix: upgrade slab to 0.4.11 to fix vulnerability

---

Cargo.lock

chore: include #4343 in 0.29.0

---

.github/workflows/bitcoin-canister-update.yml

This daily job has been consistently [failing](https://github.com/dfinity/sdk/actions/workflows/bitcoin-canister-update.yml).
- Fixed a typo from `commmon` to `common`.
- Changed the cron schedule to run every Wednesday at 4:00 AM UTC. The bitcoin-canister doesn't update frequently, so a weekly check is sufficient.

fix(ci): bitcoin-canister-update.yml typo, run weekly

---

docs/design/asset-canister-interface.md

This requirement does not hold and is not checked anywhere

fix: extra requirement in asset canister docs

---

e2e/tests-dfx/assetscanister.bash
e2e/utils/_.bash

Follow-up of https://github.com/dfinity/sdk/pull/4387 and https://github.com/dfinity/sdk/pull/4393.
New integration tests.

test: integration tests for ic_env cookie

---

CHANGELOG.md

Added a new feature for bootstrapping system canisters using a flag.

chore: Add changelog entry for version 0.30.0
