dfinity/sdk

CHANGELOG.adoc
Also set doctype to book since we have multiple top-level header sections
=> chore: Update changelog: add section for dfx 0.9.3

README.adoc
Release ink in the README is broken.
=> chore: Fix broken link

.github/workflows/publish-manifest.yml, .github/workflows/publish.yml
You can check the contents of the manifest here https://github.com/dfinity/sdk/suites/6485129500/artifacts/240458728
Once this is approved I'll switch the artifact upload step to a "push to new branch" step using GHPagesUploadAction.
=> feat: publish manifest and install script to github

src/dfx/src/commands/canister/deposit_cycles.rs
Misleading error message.
Fixes [this user's confusion](https://forum.dfinity.org/t/depositing-cycles-from-terminal/9438/13)
Not at all. Error message change only.
=> chore: improve deposit-cycles error message when no wallet is specified

.github/CONTRIBUTING.md, CHANGELOG.md, README.md
Since we’re now copying these change notes to the new portal website, which uses markdown, let’s make our lives easier.
Fixes [SDK-619](https://dfinity.atlassian.net/browse/SDK-619)
Visual scan of VSCode preview
=> chore: change README format to md

.github/workflows/update-replica-version.yml
continuation of https://github.com/dfinity/sdk/pull/2403
--
=> fix(ci): use markdown format in `update-replica` workflow

CHANGELOG.md
update CHANGELOG covering MR #2518
=> fix: update CHANGELOG

CHANGELOG.md, docs/cli-reference/dfx-sns.md, e2e/assets/sns/logo.svg, e2e/assets/sns/valid_sns_init_config.yaml, e2e/tests-dfx/sns.bash, src/dfx/src/commands/sns/config/validate.rs, src/dfx/src/lib/sns/mod.rs, src/dfx/src/lib/sns/sns_cli.rs, src/dfx/src/lib/sns/validate_config.rs
This implements the previously agreed upon command:
```
dfx sns config validate
```
- There is a CI test that verifies that the command succeeds on a known good file.
- There is another that verifies that if a line is omitted from the file, validation fails.
=> feat: sns config validate

CHANGELOG.md, src/dfx/src/lib/nns/install_nns.rs
I tried to use `dfx nns install` and ran into trouble. Some nicer error messages and some better changelog entries would have been nice.
No behavior change.
=> chore: clarify constraints and error messages of dfx nns install

e2e/assets/sns/valid/sns.yml, e2e/tests-dfx/nns.bash, src/dfx/src/commands/nns/import.rs, src/dfx/src/lib/nns/install_nns/canisters.rs, src/dfx/src/lib/project/import.rs
=> Replica 9173c5f1b fix nns sns tests

public/install/200_downloader.sh
Fixes #2723 
Not tested, but is exactly the same as #2006 which went through without a problem.
=> chore: Add macOS Ventura to versions that are supported by the installer

docs/cli-reference/dfx-wallet.md
Fixes https://github.com/dfinity/portal/issues/746
=> chore: fix typo

docs/cli-reference/dfx-identity.md
=> docs: add missing hyphens to force flag

CHANGELOG.md, src/dfx/src/lib/nns/install_nns.rs
=> fix: fixed error text

Cargo.lock, src/dfx-core/Cargo.toml, src/dfx-core/src/error/identity.rs, src/dfx-core/src/error/io.rs, src/dfx-core/src/error/mod.rs, src/dfx-core/src/error/structured_file.rs, src/dfx-core/src/fs/mod.rs, src/dfx-core/src/json/mod.rs, src/dfx-core/src/lib.rs, src/dfx/src/lib/identity/identity_manager.rs
Replacing more `anyhow` usage with concrete error types.
Part of https://dfinity.atlassian.net/browse/SDK-892
Covered by CI
=> refactor: get_identity_config_or_default, StructuredFileError, load_json_file

e2e/tests-dfx/identity.bash, e2e/tests-dfx/identity_command.bash, src/dfx/src/commands/canister/delete.rs, src/dfx/src/commands/canister/info.rs
=> chore: fix typos

src/dfx/src/lib/identity/mod.rs
Remove an unused field from the `Identity` struct.  This also makes it so it isn't necessary to pass the `IdentityManager` as a parameter when creating instances of the the individual identity types.
Covered by CI
=> refactor: remove unused variable Identity.dir

src/dfx/src/lib/identity/mod.rs
There was a time when some of these "load"ed something (see dfx/src/lib/identity/mod.rs line 96 in [SDK #1289](https://github.com/dfinity/sdk/pull/1289)), but they do not anymore. 
Covered by CI
=> refactor: Identity constructors: rename to basic, hardware, secp256k1

Cargo.lock, src/dfx-core/Cargo.toml, src/dfx-core/src/error/foundation.rs, src/dfx-core/src/error/identity.rs, src/dfx-core/src/error/io.rs, src/dfx-core/src/error/mod.rs, src/dfx-core/src/foundation/mod.rs, src/dfx-core/src/fs/mod.rs, src/dfx-core/src/lib.rs, src/dfx/src/lib/identity/identity_manager.rs
Removing dependencies on anyhow/DfxResult in preparation to move code to the dfx-core crate.
Covered by CI
=> refactor: concrete error types for IdentityManager::initialize

e2e/tests-dfx/error_context.bash, src/dfx-core/src/error/mod.rs, src/dfx-core/src/error/structured_file.rs, src/dfx-core/src/error/wallet_config.rs, src/dfx/src/lib/identity/mod.rs
Removing dependencies on anyhow/DfxResult in preparation for moving code to the dfx-core crate.
Covered by CI
=> refactor: concrete error types for load_wallet_config

Cargo.lock, src/dfx-core/Cargo.toml, src/dfx-core/src/error/keyring.rs, src/dfx-core/src/error/mod.rs, src/dfx/src/lib/identity/keyring_mock.rs
Preparation to move code to dfx-core crate
Covered by CI
=> refactor: concrete error types for delete_pem_from_keyring

Cargo.lock, e2e/assets/expect_scripts/wrong_password_rejected.exp, src/dfx-core/Cargo.toml, src/dfx-core/src/error/encryption.rs, src/dfx-core/src/error/identity.rs, src/dfx-core/src/error/keyring.rs, src/dfx/src/lib/identity/keyring_mock.rs, src/dfx/src/lib/identity/pem_safekeeping.rs
Preparation to move code to dfx-core crate
Covered by CI
=> refactor: concrete error types for load_pem()

src/dfx/src/lib/identity/identity_file_locations.rs, src/dfx/src/lib/identity/identity_manager.rs, src/dfx/src/lib/identity/mod.rs, src/dfx/src/lib/identity/pem_safekeeping.rs
Remove some dependencies on Identity -> IdentityManager by introducing a new type to provide file locations
Covered by CI
=> refactor: IdentityFileLocations

Cargo.lock, src/dfx-core/Cargo.toml, src/dfx-core/src/error/identity.rs, src/dfx-core/src/fs/mod.rs, src/dfx/src/lib/identity/mod.rs
Preparation to move code to the dfx-core crate
Covered by CI
=> refactor: concrete result types for Identity constructors

Cargo.lock, src/dfx-core/Cargo.toml, src/dfx-core/src/error/encryption.rs, src/dfx-core/src/error/identity.rs, src/dfx/src/lib/identity/identity_manager.rs, src/dfx/src/lib/identity/mod.rs
Preparation for moving to dfx-core crate
Covered by CI
=> refactor: EncryptionConfiguration::new concrete error types

src/dfx-core/src/error/config.rs, src/dfx-core/src/error/io.rs, src/dfx-core/src/error/mod.rs, src/dfx-core/src/foundation/mod.rs, src/dfx-core/src/fs/composite.rs, src/dfx-core/src/fs/mod.rs, src/dfx/src/lib/config.rs, src/dfx/src/lib/identity/identity_manager.rs, src/dfx/src/util/mod.rs
=> refactor: concrete error types for get_config_dfx_dir_path

src/dfx-core/src/error/identity.rs, src/dfx/src/lib/identity/identity_manager.rs
=> refactor: concrete error type for IdentityManager::new

src/dfx-core/src/error/identity.rs, src/dfx/src/commands/canister/create.rs, src/dfx/src/commands/canister/update_settings.rs, src/dfx/src/lib/identity/identity_manager.rs
=> refactor: concrete error types for instantiate_selected_identity

src/dfx-core/src/error/io.rs, src/dfx-core/src/fs/mod.rs, src/dfx/src/lib/identity/identity_manager.rs
=> refactor: concrete error types for get_identity_names

src/dfx-core/src/error/identity.rs, src/dfx/src/lib/identity/mod.rs
=> refactor: concrete error types for map_wallets_to_renamed_identity

src/dfx-core/src/error/wallet_config.rs, src/dfx/src/lib/identity/mod.rs
=> refactor: concrete error types for wallet config methods

src/dfx-core/src/error/dfx_config.rs, src/dfx/src/config/dfinity.rs
=> refactor: concrete error types for get_canister_config

src/dfx-core/src/error/io.rs, src/dfx-core/src/error/load_dfx_config.rs, src/dfx-core/src/error/mod.rs, src/dfx-core/src/fs/mod.rs, src/dfx/src/config/dfinity.rs
Preparation to move to dfx-core crate.
=> refactor: dfx.json load/save concrete error types

src/dfx-core/src/error/load_networks_config.rs, src/dfx-core/src/error/mod.rs, src/dfx/src/config/dfinity.rs
=> refactor: concrete error types for loading networks.json

e2e/tests-dfx/assetscanister.bash
We don't have adequate test coverage for access control of the asset canister.  This PR adds tests for current behavior, which is:
- an authorized principal, which is not a controller, may:
- authorize other principals
- deauthorize any authorized principal
Upcoming changes will alter this behavior.
This is preparatory work for https://dfinity.atlassian.net/browse/SDK-931.
=> test: for current behavior wrt ACL management by authorized (non-controller) principals

Cargo.lock, src/dfx-core/Cargo.toml, src/dfx-core/src/json/mod.rs, src/dfx-core/src/json/structure.rs, src/dfx/src/config/dfinity.rs, src/dfx/src/util/mod.rs
In preparation for moving configuration to the dfx-core crate.
=> refactor: Move SerdeVec, PossiblyStr to dfx-core crate

Cargo.lock, e2e/tests-dfx/create.bash, src/dfx-core/Cargo.toml, src/dfx-core/src/error/mod.rs, src/dfx-core/src/error/network_config.rs, src/dfx/src/lib/provider.rs
=> refactor: concrete types for parse_provider_url

e2e/tests-dfx/create.bash, e2e/tests-dfx/install.bash, src/dfx-core/src/error/network_config.rs, src/dfx/src/lib/provider.rs
=> refactor: concrete types for network descriptor creation

CHANGELOG.md, src/dfx/assets/new_project_rust_files/src/__project_name___backend/Cargo.toml, src/dfx/assets/new_project_rust_files/src/__project_name___backend/src/lib.rs
=> fix: update Rust canister template

Cargo.lock
=> chore: Update tempfile dep

e2e/tests-dfx/identity_command.bash, e2e/tests-dfx/identity_encryption.bash, src/dfx/src/lib/manifest.rs
=> style: replace `XXX` with `EOF`

CHANGELOG.md, e2e/tests-dfx/deploy.bash, src/dfx/src/commands/deploy.rs, src/dfx/src/lib/operations/canister/deploy_canisters.rs
=> fix: Stop `dfx deploy` from creating a wallet if all canisters exist

CHANGELOG.md
Subsequent changes should go in the new UNRELEASED section.
=> chore: update changelog for dfx 0.14.0

CHANGELOG.md, README.md, docs/cli-reference/dfx-cache.md, src/dfx/src/commands/quickstart.rs
Cleanup of copy and docs
Not needed, only docs were edited.
=> fix: cleanup of documentation

CHANGELOG.md, nix/sources.json, src/dfx/assets/dfx-asset-sources.toml
=> chore: update ic-ref

docs/cli-reference/dfx-parent.md
Fixes broken links reported by Daniel in https://dfinity.slack.com/archives/C04FA6QG1UJ/p1686315691610789
=> fix: broken links in docs

CHANGELOG.md, nix/sources.json, src/dfx/assets/dfx-asset-sources.toml
> Most prominently it features the new incremental garbage collector (which we regard as beta quality), and also catches up with the newest system interface improvements.
Covered by CI
=> chore: update Motoko to 0.9.3

e2e/assets/inspect_message/main.mo, e2e/assets/inspect_message/patch.bash, e2e/tests-dfx/basic-project.bash
Added a basic motoko test for inspect_message.
=> test: add e2e test (mo) for inspect message

e2e/assets/inter/src/inter2_rs/Cargo.toml, e2e/assets/inter/src/inter_rs/Cargo.toml, nix/sources.json, src/dfx/assets/dfx-asset-sources.toml
Release files have changed. This PR updates the hashes to reflect the latest state
e2e
=> chore: update replica version to release candidate 0ab9178c

src/dfx/src/lib/operations/canister/create_canister.rs
We're going to add a way for `dfx deploy` and `dfx canister create` to create canisters directly from ICP (see https://dfinity.atlassian.net/browse/SDK-1172), using the same mechanism as `dfx ledger create-canister`.  This PR extracts two methods from `create_canister()` and also flattens it a bit.
Covered by CI
=> refactor: extract two methods from create_canister, and reduce nesting

CHANGELOG.md
Adds a 0.15.0 section to the changelog.
=> chore: Update changelog for 0.15.0

.github/workflows/e2e.yml, CONTRIBUTING.md, e2e/tests-dfx/assetscanister.bash, e2e/tests-dfx/basic-project.bash, e2e/tests-dfx/bootstrap.bash, e2e/tests-dfx/create.bash, e2e/tests-dfx/delete.bash, e2e/tests-dfx/deps.bash, e2e/tests-dfx/frontend.bash, e2e/tests-dfx/info.bash, e2e/tests-dfx/install.bash, e2e/tests-dfx/migrate.bash, e2e/tests-dfx/mode_reinstall.bash, e2e/tests-dfx/ping.bash, e2e/tests-dfx/print.bash, e2e/tests-dfx/project_local_network.bash, e2e/tests-dfx/provider.bash, e2e/tests-dfx/shared_local_network.bash, e2e/tests-dfx/start.bash, e2e/utils/_.bash, scripts/workflows/e2e-matrix.py
We've been asked to remove usage of ic-ref from CI.
Fixes https://dfinity.atlassian.net/browse/SDK-1221
=> test: remove ic ref mode from CI

src/dfx-core/src/extension/manifest/extension.rs, src/dfx/src/lib/project/import.rs
ports https://github.com/dfinity/sdk/pull/3297 into the new dfx release 
covered by CI
=> feat(extension): allow specifying number of values for subcommand's args

CHANGELOG.md, nix/sources.json, src/dfx/assets/dfx-asset-sources.toml
=> chore: Revert: chore: update Motoko version to 0.10.0

README.md
adds instruction to install dfx in GitHub Action
N/A
=> docs: Update README with `dfinity/setup-dfx` GHA install instructions

CHANGELOG.md, src/dfx/assets/new_project_rust_files/src/__project_name___backend/Cargo.toml
Update the dependencies for new rust projects
Covered by CI
=> chore: update new rust project dependencies

CHANGELOG.md, Cargo.lock, Cargo.toml, src/dfx/src/util/mod.rs
Bump candid
* Fix Typescript binding for init args.
=> chore: bump candid

CHANGELOG.md
Also refine the changelog a little bit:
- put the breaking changes at the top.
-  add a clarification of `dfx canister logs`
=> chore: changelog header 0.18.0

docs/cli-reference/dfx-cycles.mdx
=> fix: docs typo

CHANGELOG.md
Includes everything up to #3675
=> chore: Add the 0.19.0 header to the changelog

.github/workflows/update-motoko.yml, .github/workflows/update-replica-version.yml, scripts/release.sh
Followup after deleting the mergify configuration.
=> chore: remove references to automerge-squash label

src/dfx/src/lib/environment.rs
=> refactor: remove unreferenced is_in_project method

CHANGELOG.md
Adds changelog heading for 0.20.1-beta.0
=> chore: add 0.20.1 changelog header

.github/workflows/broadcast-frontend-hash.yml
Sample failure:
https://github.com/dfinity/sdk/actions/runs/8978111480/job/24657990562#step:7:48
=> ci: missing backslash

docs/cli-reference/dfx-envars.mdx
Documents an env var introduced in https://github.com/dfinity/sdk/pull/3445
=> docs: mention DFX_DISABLE_QUERY_VERIFICATION

CHANGELOG.md, Cargo.lock, Cargo.toml, e2e/tests-dfx/create.bash
Also reqwest: 0.11.23 -> 0.12.4
=> chore: update to agent-rs 0.35.0

e2e/utils/_.bash
This part of dfx_start has always bothered me.  If there are no parameters it uses a dynamic port, but any parameter means use the fixed port? No.
Main motivation: I want to use `--artificial-delay` to force a configuration change.  But I can't pass it because it's always passed by this method.
If the e2e tests pass, it works
=> refactor: add host and artifical-delay only if not passed

CONTRIBUTING.md
=> docs: fix link in CONTRIBUTING.md

src/canisters/frontend/ic-asset/src/canister_api/methods/asset_properties.rs
Adds retry logic with exponential backoff to get_assets_properties. Additionally the `get_assets_properties` concurrency has been increased to 50, as a suggested safe value by @r-birkner.
Fixes:
- https://dfinity.atlassian.net/browse/SDK-1612
- the issue where the `get_assets_properties` semaphor gets released immediately after calling `acquire`
No tests were added.
=> feat: add retry/backoff logic for get_assets_properties

src/dfx-core/src/error/dfx_config.rs
This makes the error source consistent with other errors
Not specifically tested
=> fix: denote GetWasmMemoryLimitFailed error source

docs/cli-reference/dfx-ping.mdx
=> docs: deprecate and use the proper API domain

scripts/release.sh, scripts/update-frontend-canister.sh
=> chore: Add tool check to update script

e2e/tests-dfx/bitcoin.bash, e2e/tests-dfx/canister_http.bash, e2e/tests-dfx/start.bash
The error codes has been changed on the IC replica side a while ago.
=> chore: RUN-1034: Minor error code fixes in comments

CHANGELOG.md, src/dfx/assets/project_templates/svelte/src/__frontend_name__/static/.ic-assets.json5
=> fix: relax content security policy for sveltekit starter

src/dfx/src/commands/new.rs
Remove a type that isn't referenced anymore
=> refactor: delete unused Extra type

README.md
=> docs: Update README with Rust installation instructions

docs/cli-reference/dfx-envars.mdx
=> docs: add additional env vars 

docs/cli-reference/dfx-deploy.mdx
=> fix: Candid docs link

docs/cli-reference/dfx-deps.mdx
=> docs: add link to pullable config instructions

.github/BOT_APPROVED_FILES
Context: https://dfinity.slack.com/archives/CH4CADCJX/p1733844276935979
=> chore: add BOT_APPROVED_FILES

.github/repo_policies/BOT_APPROVED_FILES
Context https://dfinity.slack.com/archives/G01814XQ3K5/p1734522993460959 and https://dfinity.slack.com/archives/CH4CADCJX/p1733844276935979
=> chore: add CHANGELOG.md to BOT_APPROVED_FILES

docs/cli-reference/dfx-sns.mdx
=> docs: fix formatting of dfx-sns.mdx

src/dfx-core/src/config/directories.rs, src/dfx-core/src/error/config.rs, src/dfx-core/src/error/identity.rs, src/dfx-core/src/error/network_config.rs, src/dfx-core/src/network/provider.rs
cherry-pick https://github.com/dfinity/sdk/pull/4174 onto the release-0.26.0 branch in preparation for porting https://github.com/dfinity/sdk/pull/4175
=> refactor: error return for get_shared_network_data_directory

CHANGELOG.md, e2e/tests-dfx/error_context.bash, e2e/tests-dfx/network.bash, e2e/tests-dfx/project_local_network.bash, e2e/tests-dfx/wallet.bash, e2e/utils/_.bash, src/dfx-core/src/config/directories.rs, src/dfx-core/src/config/model/network_descriptor.rs, src/dfx-core/src/error/config.rs, src/dfx-core/src/error/identity.rs, src/dfx-core/src/error/network_config.rs, src/dfx-core/src/error/wallet_config.rs, src/dfx-core/src/identity/mod.rs, src/dfx-core/src/identity/wallet.rs, src/dfx-core/src/network/provider.rs
This ports https://github.com/dfinity/sdk/pull/4175 to the release-0.26.0 branch.
=> fix: store wallets.json with backend data files

docs/process/release.md
=> docs: Update release.md to include portal repo CI check step

docs/process/release.md
=> chore: update release doc

.github/workflows/update-ic-did.yml
The title will be "chore: update `ic.did` from portal repo"
=> ci: fix the PR title created by update-ic-did

docs/cli-reference/dfx-build.mdx, docs/cli-reference/dfx-canister.mdx, docs/cli-reference/dfx-deploy.mdx, docs/cli-reference/dfx-deps.mdx, docs/cli-reference/dfx-identity.mdx, docs/cli-reference/dfx-info.mdx, docs/cli-reference/dfx-parent.mdx, docs/cli-reference/dfx-start.mdx, docs/cli-reference/dfx-stop.mdx, docs/cli-reference/dfx-wallet.mdx, docs/dfx-json-schema.json
=> docs: local replica -> PocketIC & canister execution environment -> development environment

.github/workflows/bitcoin-canister-update.yml, .github/workflows/update-motoko.yml, .github/workflows/update-replica-version.yml, scripts/update-btc-canister.sh, scripts/update-motoko.sh, scripts/update-replica.sh
`sponge` is missing from the containers. This fixes the check in the workflows and installs it.
=> ci: fix github workflows

e2e/tests-dfx/assetscanister.bash, e2e/utils/assertions.bash, src/dfx/assets/build.rs
=> chore: fix some typos in comment

src/dfx/assets/project_templates/react/src/__frontend_name__/package.json, src/dfx/assets/project_templates/react/src/__frontend_name__/public/.ic-assets.json5, src/dfx/assets/project_templates/svelte/src/__frontend_name__/package.json, src/dfx/assets/project_templates/svelte/src/__frontend_name__/static/.ic-assets.json5, src/dfx/assets/project_templates/svelte/src/__frontend_name__/svelte.config.js, src/dfx/assets/project_templates/vanilla_js/src/__frontend_name__/package.json, src/dfx/assets/project_templates/vue/src/__frontend_name__/package.json
=> chore: Update .ic-assets.json5 for template
